import { SourceFile, Node, SyntaxKind } from 'ts-morph';
import { relativeImport } from '../utils/path';

/**
 * Generates a test file for barrel/index files that only re-export.
 * These files typically get 0% coverage because nothing tests the re-exports directly.
 */
export function generateBarrelTest(
    sourceFile: SourceFile,
    testFilePath: string,
    sourceFilePath: string
): string | null {
    const exports = getReExports(sourceFile);
    if (exports.length === 0) return null;

    const importPath = relativeImport(testFilePath, sourceFilePath);
    const lines: string[] = [];

    lines.push('/** @generated by react-testgen - deterministic output */');
    lines.push(`import * as barrel from "${importPath}";`);
    lines.push('');
    lines.push('describe("barrel exports", () => {');

    // Test that the barrel module is importable
    lines.push('  it("exports the expected modules", () => {');
    lines.push('    expect(barrel).toBeDefined();');

    for (const exp of exports) {
        lines.push(`    expect(barrel.${exp}).toBeDefined();`);
    }

    lines.push('  });');
    lines.push('});');
    lines.push('');

    return lines.join('\n');
}

function getReExports(sourceFile: SourceFile): string[] {
    const exports: string[] = [];

    // Named re-exports: export { Foo } from './foo'
    // and named exports: export { Foo }
    for (const decl of sourceFile.getExportDeclarations()) {
        for (const named of decl.getNamedExports()) {
            const name = named.getAliasNode()?.getText() || named.getName();
            if (name && name !== 'default') {
                exports.push(name);
            }
        }
    }

    // Variable export declarations: export const foo = ...
    for (const stmt of sourceFile.getVariableStatements()) {
        if (stmt.isExported()) {
            for (const decl of stmt.getDeclarations()) {
                exports.push(decl.getName());
            }
        }
    }

    // Function export declarations: export function foo() {}
    for (const func of sourceFile.getFunctions()) {
        if (func.isExported() && func.getName()) {
            exports.push(func.getName()!);
        }
    }

    // Export assignments won't be captured as named so skip
    // Also handle: export * from './module' - these get re-exported under original names
    // We can't easily enumerate star exports without resolving, but we record the fact

    return exports;
}
