import { SourceFile, Node, SyntaxKind, TypeChecker } from 'ts-morph';
import { relativeImport } from '../utils/path';
import * as path from 'path';

interface ContextExport {
    providerName: string | null;
    hookName: string | null;
    contextName: string | null;
}

/**
 * Generates tests for React Context provider files.
 * Context files typically export a Provider component and a useXxx hook.
 * They need special testing because:
 * - Provider must wrap children
 * - Hook must be called within provider
 * - State changes must be triggered through the hook's returned functions
 */
export function generateContextTest(
    sourceFile: SourceFile,
    checker: TypeChecker,
    testFilePath: string,
    sourceFilePath: string
): string | null {
    const ctxExports = detectContextExports(sourceFile);
    if (!ctxExports.providerName && !ctxExports.hookName) return null;

    const importPath = relativeImport(testFilePath, sourceFilePath);
    const lines: string[] = [];

    const sourceText = sourceFile.getText();
    const needsRouter = sourceText.includes('useNavigate') || sourceText.includes('useLocation') || sourceText.includes('useParams') || sourceText.includes('react-router');
    const needsQueryClient = sourceText.includes('useQuery') || sourceText.includes('useMutation') || sourceText.includes('@tanstack/react-query');
    // Detect if this context depends on other contexts (e.g. useNotification)
    const needsNotificationProvider = sourceText.includes('useNotification') || sourceText.includes('NotificationContext');

    lines.push('/** @generated by react-testgen - deterministic output */');
    lines.push('import React from "react";');
    lines.push('import { render, screen, renderHook, act } from "@testing-library/react";');
    if (needsRouter) {
        lines.push('import { MemoryRouter } from "react-router-dom";');
    }
    if (needsQueryClient) {
        lines.push('import { QueryClient, QueryClientProvider } from "@tanstack/react-query";');
    }
    if (needsNotificationProvider) {
        // Detect the import path for NotificationContext relative to the test file
        const notifImportPath = detectSiblingContextImport(sourceFile, 'NotificationProvider', testFilePath);
        if (notifImportPath) {
            lines.push(`import { NotificationProvider } from "${notifImportPath}";`);
        }
    }

    // Build import list
    const imports: string[] = [];
    if (ctxExports.providerName) imports.push(ctxExports.providerName);
    if (ctxExports.hookName) imports.push(ctxExports.hookName);
    if (ctxExports.contextName) imports.push(ctxExports.contextName);

    if (imports.length > 0) {
        lines.push(`import { ${imports.join(', ')} } from "${importPath}";`);
    }

    if (needsQueryClient) {
        lines.push('');
        lines.push('const createTestQueryClient = () => new QueryClient({');
        lines.push('  defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },');
        lines.push('});');
    }

    lines.push('');

    // Build wrapper components for provider tests
    const openWrappers: string[] = [];
    const closeWrappers: string[] = [];
    if (needsQueryClient) {
        openWrappers.push('<QueryClientProvider client={createTestQueryClient()}>');
        closeWrappers.unshift('</QueryClientProvider>');
    }
    if (needsRouter) {
        openWrappers.push('<MemoryRouter>');
        closeWrappers.unshift('</MemoryRouter>');
    }
    if (needsNotificationProvider) {
        openWrappers.push('<NotificationProvider>');
        closeWrappers.unshift('</NotificationProvider>');
    }

    // Provider tests
    if (ctxExports.providerName) {
        lines.push(`describe("${ctxExports.providerName}", () => {`);
        lines.push(`  it("renders children without crashing", () => {`);
        lines.push(`    render(`);
        for (const w of openWrappers) lines.push(`      ${w}`);
        lines.push(`      <${ctxExports.providerName}>`);
        lines.push(`        <div data-testid="child">Test Child</div>`);
        lines.push(`      </${ctxExports.providerName}>`);
        for (const w of closeWrappers) lines.push(`      ${w}`);
        lines.push(`    );`);
        lines.push(`    expect(screen.getByTestId("child")).toBeInTheDocument();`);
        lines.push(`  });`);
        lines.push('');
        lines.push(`  it("provides context to children", () => {`);
        lines.push(`    const { container } = render(`);
        for (const w of openWrappers) lines.push(`      ${w}`);
        lines.push(`      <${ctxExports.providerName}>`);
        lines.push(`        <div>Context Consumer</div>`);
        lines.push(`      </${ctxExports.providerName}>`);
        for (const w of closeWrappers) lines.push(`      ${w}`);
        lines.push(`    );`);
        lines.push(`    expect(container).toBeInTheDocument();`);
        lines.push(`  });`);
        lines.push('});');
        lines.push('');
    }

    // Hook tests (must be wrapped in provider)
    if (ctxExports.hookName) {
        const wrapperName = ctxExports.providerName || 'React.Fragment';
        lines.push(`describe("${ctxExports.hookName}", () => {`);

        if (ctxExports.providerName) {
            lines.push(`  const wrapper = ({ children }: { children: React.ReactNode }) => (`);
            for (const w of openWrappers) lines.push(`    ${w}`);
            lines.push(`    <${ctxExports.providerName}>{children}</${ctxExports.providerName}>`);
            for (const w of closeWrappers) lines.push(`    ${w}`);
            lines.push(`  );`);
            lines.push('');
        }

        const wrapperOption = ctxExports.providerName ? '{ wrapper }' : '';

        lines.push(`  it("returns context value", () => {`);
        lines.push(`    const { result } = renderHook(() => ${ctxExports.hookName}(), ${wrapperOption});`);
        lines.push(`    expect(result.current).toBeDefined();`);
        lines.push(`  });`);
        lines.push('');

        // Detect what the hook returns and generate tests for each method
        const hookReturnMethods = detectHookReturnMethods(sourceFile, ctxExports.hookName);
        for (const method of hookReturnMethods) {
            lines.push(`  it("provides ${method} function", () => {`);
            lines.push(`    const { result } = renderHook(() => ${ctxExports.hookName}(), ${wrapperOption});`);
            lines.push(`    expect(typeof result.current.${method}).toBe("function");`);
            lines.push(`  });`);
            lines.push('');
        }

        // Detect returned state values
        const hookReturnState = detectHookReturnState(sourceFile, ctxExports.hookName);
        for (const state of hookReturnState) {
            lines.push(`  it("provides ${state} state", () => {`);
            lines.push(`    const { result } = renderHook(() => ${ctxExports.hookName}(), ${wrapperOption});`);
            lines.push(`    expect(result.current.${state}).toBeDefined();`);
            lines.push(`  });`);
            lines.push('');
        }

        lines.push('});');
        lines.push('');
    }

    return lines.join('\n');
}

function detectContextExports(sourceFile: SourceFile): ContextExport {
    let providerName: string | null = null;
    let hookName: string | null = null;
    let contextName: string | null = null;

    const exported = sourceFile.getExportedDeclarations();
    for (const [name] of exported) {
        if (/Provider$/.test(name)) {
            providerName = name;
        } else if (/^use[A-Z]/.test(name)) {
            hookName = name;
        } else if (/Context$/.test(name)) {
            contextName = name;
        }
    }

    return { providerName, hookName, contextName };
}

function detectHookReturnMethods(sourceFile: SourceFile, hookName: string): string[] {
    const methods: string[] = [];

    // Look for the hook function and find its return statement
    const hookFunc = findFunctionByName(sourceFile, hookName);
    if (!hookFunc) return methods;

    const returnStatements = hookFunc.getDescendantsOfKind(SyntaxKind.ReturnStatement);
    for (const ret of returnStatements) {
        const expr = ret.getExpression();
        if (!expr) continue;

        // Look for object literal returns: return { login, logout, ... }
        if (Node.isObjectLiteralExpression(expr)) {
            for (const prop of expr.getProperties()) {
                if (Node.isShorthandPropertyAssignment(prop) || Node.isPropertyAssignment(prop)) {
                    const name = prop.getName();
                    // Methods are typically named with action verbs
                    if (/^(set|add|remove|update|delete|toggle|fetch|load|save|clear|reset|login|logout|register|create|edit|submit|handle|dispatch|notify)/.test(name)) {
                        methods.push(name);
                    }
                }
            }
        }
    }

    return methods;
}

function detectHookReturnState(sourceFile: SourceFile, hookName: string): string[] {
    const state: string[] = [];

    const hookFunc = findFunctionByName(sourceFile, hookName);
    if (!hookFunc) return state;

    const returnStatements = hookFunc.getDescendantsOfKind(SyntaxKind.ReturnStatement);
    for (const ret of returnStatements) {
        const expr = ret.getExpression();
        if (!expr) continue;

        if (Node.isObjectLiteralExpression(expr)) {
            for (const prop of expr.getProperties()) {
                if (Node.isShorthandPropertyAssignment(prop) || Node.isPropertyAssignment(prop)) {
                    const name = prop.getName();
                    // State values are typically nouns or is/has prefixed booleans
                    if (/^(is|has|can|should|loading|error|data|items|list|user|token|theme|state|count|total|current|selected)/.test(name)) {
                        state.push(name);
                    }
                }
            }
        }
    }

    return state;
}

function findFunctionByName(sourceFile: SourceFile, name: string): Node | null {
    // Check function declarations
    for (const func of sourceFile.getFunctions()) {
        if (func.getName() === name) return func;
    }

    // Check variable declarations (arrow functions)
    for (const variable of sourceFile.getVariableDeclarations()) {
        if (variable.getName() === name) {
            const init = variable.getInitializer();
            if (init && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))) {
                return init;
            }
        }
    }

    return null;
}

/**
 * Detect the import path for a sibling context provider.
 * When a context file imports from another context (e.g. NotificationContext),
 * we need to find that import and make it relative to the test file location.
 */
function detectSiblingContextImport(sourceFile: SourceFile, providerName: string, testFilePath: string): string | null {
    // Look for import declarations that reference the provider
    for (const imp of sourceFile.getImportDeclarations()) {
        const moduleSpecifier = imp.getModuleSpecifierValue();
        for (const named of imp.getNamedImports()) {
            const importedName = named.getName();
            // Check if this import brings in useNotification or NotificationContext etc.
            if (importedName.includes('Notification') || importedName.includes('notification')) {
                // Resolve the import relative to the source file, then make it relative to the test file
                const sourceDir = path.dirname(sourceFile.getFilePath());
                const resolvedPath = path.resolve(sourceDir, moduleSpecifier);
                // testFilePath is like .../contexts/__tests__/BudgetContext.test.tsx
                const testDir = path.dirname(testFilePath);
                let relativePath = path.relative(testDir, resolvedPath).replace(/\\/g, '/');
                if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
                // Remove file extension if present
                relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
                return relativePath;
            }
        }
    }
    return null;
}
