import { Node, SourceFile, SyntaxKind, TypeChecker } from 'ts-morph';
import path from 'node:path';
import { CONTEXT_DETECTION_CONFIG } from '../config';
import { relativeImport } from '../utils/path';
import { buildDomMatchersImport, buildTestGlobalsImport } from '../utils/framework';

interface ContextExport {
  providerName: string | null;
  hookName: string | null;
  contextName: string | null;
}

interface ContextDependencies {
  needsRouter: boolean;
  needsQueryClient: boolean;
  needsNotificationProvider: boolean;
}

interface WrapperTags {
  open: string[];
  close: string[];
}

function appendLines(lines: string[], ...entries: string[]): void {
  lines.push(...entries);
}

function normalizeSlashes(value: string): string {
  return value.split('\\').join('/');
}

/**
 * Generates tests for React Context provider files.
 * Context files typically export a Provider component and a useXxx hook.
 */
export function generateContextTest(
  sourceFile: SourceFile,
  _checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string
): string | null {
  const ctxExports = detectContextExports(sourceFile);
  if (!ctxExports.providerName && !ctxExports.hookName) return null;

  const importPath = relativeImport(testFilePath, sourceFilePath);
  const sourceText = sourceFile.getText();
  const dependencies = detectDependencies(sourceText, sourceFile);

  // If NotificationProvider dependency detected but import path can't be resolved,
  // skip the wrapper to avoid generating code that references an undefined component.
  if (dependencies.needsNotificationProvider) {
    if (!detectSiblingContextImport(sourceFile, testFilePath)) {
      dependencies.needsNotificationProvider = false;
    }
  }

  const wrappers = buildWrappers(dependencies);
  const lines: string[] = [];

  appendImportSection(lines, sourceFile, testFilePath, ctxExports, importPath, dependencies);

  if (dependencies.needsQueryClient) {
    appendLines(
      lines,
      '',
      'const createTestQueryClient = () => new QueryClient({',
      '  defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },',
      '});'
    );
  }

  appendLines(lines, '');

  if (ctxExports.providerName) {
    appendProviderTests(lines, ctxExports.providerName, wrappers);
  }

  if (ctxExports.hookName) {
    appendHookTests(lines, sourceFile, ctxExports, wrappers);
  }

  return lines.join('\n');
}

function appendImportSection(
  lines: string[],
  sourceFile: SourceFile,
  testFilePath: string,
  ctxExports: ContextExport,
  importPath: string,
  dependencies: ContextDependencies
): void {
  appendLines(
    lines,
    '/** @generated by react-testgen - deterministic output */',
    buildTestGlobalsImport(['describe', 'it', 'expect']),
    buildDomMatchersImport(),
    'import React from "react";',
    'import { render, screen, renderHook } from "@testing-library/react";'
  );

  if (dependencies.needsRouter) {
    appendLines(lines, 'import { MemoryRouter } from "react-router-dom";');
  }

  if (dependencies.needsQueryClient) {
    appendLines(lines, 'import { QueryClient, QueryClientProvider } from "@tanstack/react-query";');
  }

  if (dependencies.needsNotificationProvider) {
    const notifImportPath = detectSiblingContextImport(sourceFile, testFilePath);
    if (notifImportPath) {
      appendLines(lines, `import { NotificationProvider } from "${notifImportPath}";`);
    }
  }

  const imports = [ctxExports.providerName, ctxExports.hookName, ctxExports.contextName].filter(
    (name): name is string => Boolean(name)
  );

  if (imports.length > 0) {
    appendLines(lines, `import { ${imports.join(', ')} } from "${importPath}";`);
  }
}

function appendProviderTests(lines: string[], providerName: string, wrappers: WrapperTags): void {
  appendLines(
    lines,
    `describe("${providerName}", () => {`,
    '  it("renders children without crashing", () => {',
    '    render('
  );

  for (const wrapper of wrappers.open) {
    appendLines(lines, `      ${wrapper}`);
  }

  appendLines(
    lines,
    `      <${providerName}>`,
    '        <div data-testid="child">Test Child</div>',
    `      </${providerName}>`
  );

  for (const wrapper of wrappers.close) {
    appendLines(lines, `      ${wrapper}`);
  }

  appendLines(
    lines,
    '    );',
    '    expect(screen.getByTestId("child")).toBeInTheDocument();',
    '  });',
    '',
    '  it("provides context to children", () => {',
    '    const { container } = render('
  );

  for (const wrapper of wrappers.open) {
    appendLines(lines, `      ${wrapper}`);
  }

  appendLines(
    lines,
    `      <${providerName}>`,
    '        <div>Context Consumer</div>',
    `      </${providerName}>`
  );

  for (const wrapper of wrappers.close) {
    appendLines(lines, `      ${wrapper}`);
  }

  appendLines(lines, '    );', '    expect(container).toBeInTheDocument();', '  });', '});', '');
}

function appendHookTests(
  lines: string[],
  sourceFile: SourceFile,
  ctxExports: ContextExport,
  wrappers: WrapperTags
): void {
  const hookName = ctxExports.hookName;
  if (!hookName) return;

  appendLines(lines, `describe("${hookName}", () => {`);

  if (ctxExports.providerName) {
    appendLines(lines, '  const wrapper = ({ children }: { children: React.ReactNode }) => (');
    for (const wrapperTag of wrappers.open) {
      appendLines(lines, `    ${wrapperTag}`);
    }
    appendLines(lines, `    <${ctxExports.providerName}>{children}</${ctxExports.providerName}>`);
    for (const wrapperTag of wrappers.close) {
      appendLines(lines, `    ${wrapperTag}`);
    }
    appendLines(lines, '  );', '');
  }

  const wrapperOption = ctxExports.providerName ? '{ wrapper }' : '';

  appendLines(
    lines,
    '  it("returns context value", () => {',
    `    const { result } = renderHook(() => ${hookName}(), ${wrapperOption});`,
    '    expect(result.current).toBeDefined();',
    '  });',
    ''
  );

  const hookReturnMethods = detectHookReturnMethods(sourceFile, hookName);
  for (const method of hookReturnMethods) {
    appendLines(
      lines,
      `  it("provides ${method} function", () => {`,
      `    const { result } = renderHook(() => ${hookName}(), ${wrapperOption});`,
      `    expect(typeof result.current.${method}).toBe("function");`,
      '  });',
      ''
    );
  }

  const hookReturnState = detectHookReturnState(sourceFile, hookName);
  for (const state of hookReturnState) {
    appendLines(
      lines,
      `  it("provides ${state} state", () => {`,
      `    const { result } = renderHook(() => ${hookName}(), ${wrapperOption});`,
      `    expect(result.current).toHaveProperty("${state}");`,
      '  });',
      ''
    );
  }

  appendLines(lines, '});', '');
}

function detectDependencies(sourceText: string, sourceFile: SourceFile): ContextDependencies {
  const { router, reactQuery, customContexts } = CONTEXT_DETECTION_CONFIG;

  // Collect exported names so we can skip self-references.
  // E.g. ExpenseContext.tsx exports "ExpenseProvider" / "ExpenseContext" and should
  // NOT match itself as a dependency when those names appear in customContexts.
  const exportedNames = new Set<string>();
  for (const [name] of sourceFile.getExportedDeclarations()) {
    exportedNames.add(name);
  }

  const needsRouter =
    router.hooks.some((hook) => sourceText.includes(hook)) ||
    router.imports.some((imp) => sourceText.includes(imp));

  const needsQueryClient =
    reactQuery.hooks.some((hook) => sourceText.includes(hook)) ||
    reactQuery.imports.some((imp) => sourceText.includes(imp));

  const needsNotificationProvider = customContexts.some((ctx) => {
    // Skip self-references: if this file exports the provider or context, it IS this context
    if (exportedNames.has(ctx.providerName) || exportedNames.has(ctx.contextName)) return false;

    return (
      ctx.hooks.some((hook) => sourceText.includes(hook)) ||
      sourceText.includes(ctx.contextName) ||
      sourceText.includes(ctx.providerName)
    );
  });

  return {
    needsRouter,
    needsQueryClient,
    needsNotificationProvider,
  };
}

function buildWrappers(dependencies: ContextDependencies): WrapperTags {
  const open: string[] = [];
  const close: string[] = [];

  if (dependencies.needsQueryClient) {
    open.push('<QueryClientProvider client={createTestQueryClient()}>');
    close.unshift('</QueryClientProvider>');
  }
  if (dependencies.needsRouter) {
    open.push('<MemoryRouter>');
    close.unshift('</MemoryRouter>');
  }
  if (dependencies.needsNotificationProvider) {
    open.push('<NotificationProvider>');
    close.unshift('</NotificationProvider>');
  }

  return { open, close };
}

function detectContextExports(sourceFile: SourceFile): ContextExport {
  let providerName: string | null = null;
  let hookName: string | null = null;
  let contextName: string | null = null;

  const exported = sourceFile.getExportedDeclarations();
  for (const [name] of exported) {
    if (name.endsWith('Provider')) {
      providerName = name;
    } else if (/^use[A-Z]/.test(name)) {
      hookName = name;
    } else if (name.endsWith('Context')) {
      contextName = name;
    }
  }

  return { providerName, hookName, contextName };
}

function detectHookReturnMethods(sourceFile: SourceFile, hookName: string): string[] {
  return detectHookReturnPropsByPrefixes(
    sourceFile,
    hookName,
    CONTEXT_DETECTION_CONFIG.methodPatterns
  );
}

function detectHookReturnState(sourceFile: SourceFile, hookName: string): string[] {
  return detectHookReturnPropsByPrefixes(
    sourceFile,
    hookName,
    CONTEXT_DETECTION_CONFIG.statePatterns
  );
}

function detectHookReturnPropsByPrefixes(
  sourceFile: SourceFile,
  hookName: string,
  prefixes: string[]
): string[] {
  const foundNames: string[] = [];
  const hookFunc = findFunctionByName(sourceFile, hookName);
  if (!hookFunc) return foundNames;

  const prefixRegex = new RegExp(`^(${prefixes.join('|')})`);
  const returnStatements = hookFunc.getDescendantsOfKind(SyntaxKind.ReturnStatement);

  for (const ret of returnStatements) {
    const expr = ret.getExpression();
    if (!expr || !Node.isObjectLiteralExpression(expr)) continue;

    for (const prop of expr.getProperties()) {
      if (!Node.isShorthandPropertyAssignment(prop) && !Node.isPropertyAssignment(prop)) {
        continue;
      }

      const name = prop.getName();
      if (prefixRegex.test(name)) {
        foundNames.push(name);
      }
    }
  }

  return foundNames;
}

function findFunctionByName(sourceFile: SourceFile, name: string): Node | null {
  for (const func of sourceFile.getFunctions()) {
    if (func.getName() === name) return func;
  }

  for (const variable of sourceFile.getVariableDeclarations()) {
    if (variable.getName() !== name) continue;
    const init = variable.getInitializer();
    if (init && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))) {
      return init;
    }
  }

  return null;
}

/**
 * Detect the import path for a sibling context provider.
 * When a context file imports from another context (e.g. NotificationContext),
 * we need to find that import and make it relative to the test file location.
 */
function detectSiblingContextImport(sourceFile: SourceFile, testFilePath: string): string | null {
  for (const imp of sourceFile.getImportDeclarations()) {
    const moduleSpecifier = imp.getModuleSpecifierValue();
    const hasNotificationImport = imp
      .getNamedImports()
      .some((named) => /notification/i.test(named.getName()));

    if (!hasNotificationImport) continue;

    const sourceDir = normalizeSlashes(path.dirname(sourceFile.getFilePath()));
    let resolvedPath: string;

    if (moduleSpecifier.startsWith('.')) {
      // Relative import — resolve directly
      resolvedPath = path.resolve(sourceDir, moduleSpecifier);
    } else if (moduleSpecifier.startsWith('@/') || moduleSpecifier.startsWith('~/')) {
      // Path alias (e.g. @/contexts/NotificationContext)
      // Resolve by finding the project's src/ directory
      const srcDir = findAncestorSrcDir(sourceDir);
      if (!srcDir) continue;
      resolvedPath = path.resolve(srcDir, moduleSpecifier.replace(/^[@~]\//, ''));
    } else {
      // Package import — not a sibling context, skip
      continue;
    }

    const testDir = path.dirname(testFilePath);

    let relativePath = normalizeSlashes(path.relative(testDir, resolvedPath));
    if (!relativePath.startsWith('.')) {
      relativePath = `./${relativePath}`;
    }

    return relativePath.replace(/\.(tsx?|jsx?)$/, '');
  }

  return null;
}

/**
 * Walk up directory tree to find the nearest ancestor `src/` directory.
 * Returns the full path to the src directory, or null if not found.
 */
function findAncestorSrcDir(dir: string): string | null {
  let current = dir;
  while (current.length > 1) {
    if (current.endsWith('/src')) return current;
    const srcIdx = current.lastIndexOf('/src/');
    if (srcIdx !== -1) return current.substring(0, srcIdx + 4);
    const parent = normalizeSlashes(path.dirname(current));
    if (parent === current) break;
    current = parent;
  }
  return null;
}
