/**
 * Generator for state management store files:
 * - Zustand stores (create / createStore from 'zustand')
 * - Redux Toolkit slices (createSlice from '@reduxjs/toolkit')
 * - Jotai atoms (atom from 'jotai')
 */

import { Node, SourceFile, SyntaxKind, TypeChecker } from 'ts-morph';
import { relativeImport } from '../utils/path';
import { buildTestGlobalsImport } from '../utils/framework';

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export function generateStoreTest(
  sourceFile: SourceFile,
  checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string
): string | null {
  const sourceText = sourceFile.getText();

  const isZustand =
    sourceText.includes("from 'zustand'") || sourceText.includes('from "zustand"');
  const isRTK =
    sourceText.includes("from '@reduxjs/toolkit'") ||
    sourceText.includes('from "@reduxjs/toolkit"');
  const isJotai =
    sourceText.includes("from 'jotai'") || sourceText.includes('from "jotai"');

  if (isZustand) {
    return generateZustandTest(sourceFile, checker, testFilePath, sourceFilePath);
  }

  if (isRTK) {
    return generateRTKSliceTest(sourceFile, checker, testFilePath, sourceFilePath);
  }

  if (isJotai) {
    return generateJotaiTest(sourceFile, checker, testFilePath, sourceFilePath);
  }

  return null;
}

// ---------------------------------------------------------------------------
// Zustand store test generation
// ---------------------------------------------------------------------------

interface ZustandStoreInfo {
  hookName: string; // e.g. "useAppStore", "useAuthStore"
  stateKeys: string[]; // detected state keys
  actionKeys: string[]; // detected action / setter keys
}

function generateZustandTest(
  sourceFile: SourceFile,
  _checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string
): string | null {
  const stores = detectZustandStores(sourceFile);
  if (stores.length === 0) return null;

  const importPath = relativeImport(testFilePath, sourceFilePath);
  const hookNames = stores.map((s) => s.hookName);
  const lines: string[] = [];

  lines.push('/** @generated by react-testgen - deterministic output */');
  lines.push('');
  lines.push(buildTestGlobalsImport(['describe', 'it', 'expect', 'beforeEach']));
  lines.push('');
  lines.push('import { renderHook, act } from "@testing-library/react";');
  lines.push(`import { ${hookNames.join(', ')} } from "${importPath}";`);
  lines.push('');

  for (const store of stores) {
    lines.push(`describe("${store.hookName}", () => {`);

    // Reset store before each test (Zustand stores persist state across tests)
    lines.push('  beforeEach(() => {');
    lines.push(`    // Reset store to initial state between tests`);
    lines.push(`    const state = ${store.hookName}.getState?.();`);
    lines.push(`    if (state && typeof state === "object") {`);
    lines.push(`      // Attempt to call reset action if it exists`);
    lines.push(`      (state as any).reset?.();`);
    lines.push(`    }`);
    lines.push('  });');
    lines.push('');

    // Basic render test
    lines.push('  it("initializes with defined state", () => {');
    lines.push(`    const { result } = renderHook(() => ${store.hookName}());`);
    lines.push('    expect(result.current).toBeDefined();');
    lines.push('  });');
    lines.push('');

    // Test each detected state key
    for (const key of store.stateKeys.slice(0, 4)) {
      lines.push(`  it("exposes \\"${key}\\" in state", () => {`);
      lines.push(`    const { result } = renderHook(() => ${store.hookName}());`);
      lines.push(`    expect(result.current).toHaveProperty("${key}");`);
      lines.push('  });');
      lines.push('');
    }

    // Test each detected action key
    for (const action of store.actionKeys.slice(0, 4)) {
      lines.push(`  it("exposes callable action \\"${action}\\"", () => {`);
      lines.push(`    const { result } = renderHook(() => ${store.hookName}());`);
      lines.push(`    expect(typeof result.current.${action}).toBe("function");`);
      lines.push('  });');
      lines.push('');

      // Only safe no-arg reset-like actions
      if (isSafeToCallNoArgs(action)) {
        lines.push(`  it("can invoke \\"${action}\\" with act", () => {`);
        lines.push(`    const { result } = renderHook(() => ${store.hookName}());`);
        lines.push('    act(() => {');
        lines.push(`      result.current.${action}();`);
        lines.push('    });');
        lines.push('    expect(result.current).toBeDefined();');
        lines.push('  });');
        lines.push('');
      }
    }

    // Snapshot of initial shape
    lines.push('  it("has stable initial shape", () => {');
    lines.push(`    const { result } = renderHook(() => ${store.hookName}());`);
    lines.push('    expect(typeof result.current).toBe("object");');
    lines.push('  });');
    lines.push('');

    lines.push('});');
    lines.push('');
  }

  return lines.join('\n');
}

function isSafeToCallNoArgs(name: string): boolean {
  return /^(reset|clear|toggle|open|close|show|hide|init|initialize|logout|signOut)/i.test(name);
}

function detectZustandStores(sourceFile: SourceFile): ZustandStoreInfo[] {
  const stores: ZustandStoreInfo[] = [];

  const exported = sourceFile.getExportedDeclarations();

  for (const [name, decls] of exported) {
    // Store hooks are typically named useXxxStore or useXxx
    if (!/^use[A-Z]/.test(name)) continue;

    for (const decl of decls) {
      const declText = decl.getText();
      // Detect if this is a Zustand store (created via create())
      if (!declText.includes('create(') && !declText.includes('create<')) continue;

      const stateKeys: string[] = [];
      const actionKeys: string[] = [];

      // Try to extract state/action keys from the create() call body
      extractZustandKeys(decl, stateKeys, actionKeys);

      stores.push({ hookName: name, stateKeys, actionKeys });
      break;
    }
  }

  // Also look for variable declarations that use create()
  for (const varDecl of sourceFile.getVariableDeclarations()) {
    const varName = varDecl.getName();
    // Skip if already found or doesn't look like a store hook
    if (stores.some((s) => s.hookName === varName)) continue;
    if (!/^use[A-Z]/.test(varName) && !/Store$/.test(varName)) continue;

    const init = varDecl.getInitializer();
    if (!init) continue;

    const initText = init.getText();
    if (!initText.includes('create(') && !initText.includes('create<')) continue;

    // Check if it's exported
    const stmt = varDecl.getVariableStatement();
    if (!stmt?.isExported()) continue;

    const stateKeys: string[] = [];
    const actionKeys: string[] = [];
    extractZustandKeys(varDecl, stateKeys, actionKeys);

    const hookName = /^use/.test(varName) ? varName : `use${varName.charAt(0).toUpperCase()}${varName.slice(1)}`;
    stores.push({ hookName, stateKeys, actionKeys });
  }

  return stores;
}

function extractZustandKeys(node: Node, stateKeys: string[], actionKeys: string[]): void {
  const text = node.getText();

  // Look for object literal property assignments inside the create() callback
  const propertyAssignments = node.getDescendantsOfKind(SyntaxKind.PropertyAssignment);
  const shorthandProps = node.getDescendantsOfKind(SyntaxKind.ShorthandPropertyAssignment);
  const methodDecls = node.getDescendantsOfKind(SyntaxKind.MethodDeclaration);

  const seen = new Set<string>();

  for (const prop of propertyAssignments) {
    const name = prop.getName();
    if (!name || seen.has(name) || name === 'default') continue;
    seen.add(name);

    const value = prop.getInitializer();
    const isAction =
      (value && (Node.isArrowFunction(value) || Node.isFunctionExpression(value))) ||
      /^(set|add|remove|update|delete|toggle|reset|clear|fetch|load|save|login|logout|open|close|show|hide|dispatch|handle)[A-Z]/.test(name);

    if (isAction) {
      actionKeys.push(name);
    } else {
      stateKeys.push(name);
    }
  }

  for (const prop of shorthandProps) {
    const name = prop.getName();
    if (!name || seen.has(name)) continue;
    seen.add(name);

    if (/^(set|add|remove|update|delete|toggle|reset|clear)[A-Z]/.test(name)) {
      actionKeys.push(name);
    } else {
      stateKeys.push(name);
    }
  }

  for (const method of methodDecls) {
    const name = method.getName();
    if (!name || seen.has(name)) continue;
    seen.add(name);
    actionKeys.push(name);
  }

  // Fallback: scan text for common patterns
  if (stateKeys.length === 0 && actionKeys.length === 0) {
    const patterns = [
      /(\w+):\s*\[/g,   // items: [
      /(\w+):\s*\d+/g,  // count: 0
      /(\w+):\s*false/g, // isOpen: false
      /(\w+):\s*true/g, // isLoaded: true
      /(\w+):\s*null/g, // user: null
      /(\w+):\s*""/g,   // name: ""
    ];
    for (const pattern of patterns) {
      let m: RegExpExecArray | null;
      while ((m = pattern.exec(text)) !== null) {
        const key = m[1];
        if (!seen.has(key) && key !== 'set' && key !== 'get') {
          seen.add(key);
          stateKeys.push(key);
        }
      }
    }

    const actionPattern = /\b(set\w+|reset|clear|toggle\w*|add\w*|remove\w*|update\w*|delete\w*|fetch\w*|load\w*)\s*:/g;
    let am: RegExpExecArray | null;
    while ((am = actionPattern.exec(text)) !== null) {
      const key = am[1];
      if (!seen.has(key)) {
        seen.add(key);
        actionKeys.push(key);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Redux Toolkit slice test generation
// ---------------------------------------------------------------------------

interface RTKSliceInfo {
  sliceName: string;
  reducerExport: string; // default export name for the reducer
  actionNames: string[]; // named action creator exports
  initialStateKeys: string[];
  asyncThunkNames: string[];
}

function generateRTKSliceTest(
  sourceFile: SourceFile,
  _checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string
): string | null {
  const slice = detectRTKSlice(sourceFile);
  if (!slice) return null;

  const importPath = relativeImport(testFilePath, sourceFilePath);
  const lines: string[] = [];

  lines.push('/** @generated by react-testgen - deterministic output */');
  lines.push('');
  lines.push(buildTestGlobalsImport(['describe', 'it', 'expect', 'beforeEach']));
  lines.push('');

  // Import the reducer and action creators
  const namedImports: string[] = [...slice.actionNames];
  if (slice.asyncThunkNames.length > 0) {
    namedImports.push(...slice.asyncThunkNames);
  }

  if (namedImports.length > 0) {
    lines.push(`import reducer, { ${namedImports.join(', ')} } from "${importPath}";`);
  } else {
    lines.push(`import reducer from "${importPath}";`);
  }
  lines.push('import { configureStore } from "@reduxjs/toolkit";');
  lines.push('');

  lines.push(`describe("${slice.sliceName} slice", () => {`);
  lines.push('  let store: ReturnType<typeof configureStore>;');
  lines.push('');
  lines.push('  beforeEach(() => {');
  lines.push('    store = configureStore({');
  lines.push(`      reducer: { ${slice.sliceName}: reducer },`);
  lines.push('    });');
  lines.push('  });');
  lines.push('');

  // Initial state test
  lines.push('  it("has defined initial state", () => {');
  lines.push(`    const state = (store.getState() as any).${slice.sliceName};`);
  lines.push('    expect(state).toBeDefined();');
  lines.push('  });');
  lines.push('');

  // Test each detected initial state key
  for (const key of slice.initialStateKeys.slice(0, 4)) {
    lines.push(`  it("initial state has \\"${key}\\" property", () => {`);
    lines.push(`    const state = (store.getState() as any).${slice.sliceName};`);
    lines.push(`    expect(state).toHaveProperty("${key}");`);
    lines.push('  });');
    lines.push('');
  }

  // Test each action creator
  for (const action of slice.actionNames.slice(0, 6)) {
    lines.push(`  describe("${action}", () => {`);
    lines.push(`    it("is a valid action creator", () => {`);
    lines.push(`      expect(typeof ${action}).toBe("function");`);
    lines.push(`      const action = ${action}();`);
    lines.push(`      expect(action.type).toBeDefined();`);
    lines.push('    });');
    lines.push('');
    lines.push(`    it("can be dispatched without throwing", () => {`);
    lines.push(`      expect(() => store.dispatch(${action}())).not.toThrow();`);
    lines.push('    });');
    lines.push('  });');
    lines.push('');
  }

  // Test async thunks
  for (const thunk of slice.asyncThunkNames.slice(0, 3)) {
    lines.push(`  describe("${thunk}", () => {`);
    lines.push(`    it("is a valid async thunk", () => {`);
    lines.push(`      expect(typeof ${thunk}).toBe("function");`);
    lines.push(`      expect(${thunk}.pending?.type).toBeDefined();`);
    lines.push(`      expect(${thunk}.fulfilled?.type).toBeDefined();`);
    lines.push(`      expect(${thunk}.rejected?.type).toBeDefined();`);
    lines.push('    });');
    lines.push('  });');
    lines.push('');
  }

  // Reducer test
  lines.push('  it("reducer handles unknown action without throwing", () => {');
  lines.push('    const state = reducer(undefined, { type: "__UNKNOWN_ACTION__" });');
  lines.push('    expect(state).toBeDefined();');
  lines.push('  });');
  lines.push('');

  lines.push('});');
  lines.push('');

  return lines.join('\n');
}

function detectRTKSlice(sourceFile: SourceFile): RTKSliceInfo | null {
  const sourceText = sourceFile.getText();

  // Find createSlice call
  const createSliceCalls = sourceFile
    .getDescendantsOfKind(SyntaxKind.CallExpression)
    .filter((call) => call.getExpression().getText() === 'createSlice');

  if (createSliceCalls.length === 0) return null;

  const call = createSliceCalls[0];
  const args = call.getArguments();
  if (args.length === 0) return null;

  const configArg = args[0];
  if (!Node.isObjectLiteralExpression(configArg)) return null;

  let sliceName = 'app';
  const nameProperty = configArg.getProperty('name');
  if (nameProperty && Node.isPropertyAssignment(nameProperty)) {
    const nameValue = nameProperty.getInitializer();
    if (nameValue && Node.isStringLiteral(nameValue)) {
      sliceName = nameValue.getLiteralText();
    }
  }

  // Extract initial state keys
  const initialStateKeys: string[] = [];
  const initialStateProp = configArg.getProperty('initialState');
  if (initialStateProp && Node.isPropertyAssignment(initialStateProp)) {
    const stateValue = initialStateProp.getInitializer();
    if (stateValue && Node.isObjectLiteralExpression(stateValue)) {
      for (const prop of stateValue.getProperties()) {
        if (Node.isPropertyAssignment(prop) || Node.isShorthandPropertyAssignment(prop)) {
          initialStateKeys.push(prop.getName());
        }
      }
    }
  }

  // Detect exported action names from slice.actions pattern
  const actionNames: string[] = [];

  // Look for: export const { actionA, actionB } = mySlice.actions;
  const destructured = sourceFile.getDescendantsOfKind(SyntaxKind.ObjectBindingPattern);
  for (const pattern of destructured) {
    const parent = pattern.getParent();
    if (!Node.isVariableDeclaration(parent)) continue;
    const init = parent.getInitializer();
    if (!init || !init.getText().includes('.actions')) continue;

    for (const element of pattern.getElements()) {
      const name = element.getName();
      if (name) actionNames.push(name);
    }
  }

  // Also look for named exports that reference slice actions
  const exported = sourceFile.getExportedDeclarations();
  for (const [name] of exported) {
    if (
      name !== 'default' &&
      !actionNames.includes(name) &&
      /^[a-z]/.test(name) &&
      sourceText.includes(`${name}.type`)
    ) {
      actionNames.push(name);
    }
  }

  // Detect async thunks
  const asyncThunkNames: string[] = [];
  const thunkCalls = sourceFile
    .getDescendantsOfKind(SyntaxKind.CallExpression)
    .filter((call) => call.getExpression().getText() === 'createAsyncThunk');

  for (const thunk of thunkCalls) {
    // Find the variable this is assigned to
    let current: Node | undefined = thunk.getParent();
    while (current) {
      if (Node.isVariableDeclaration(current)) {
        const name = current.getName();
        if (name) asyncThunkNames.push(name);
        break;
      }
      current = current.getParent();
    }
  }

  return {
    sliceName,
    reducerExport: 'default',
    actionNames,
    initialStateKeys,
    asyncThunkNames,
  };
}

// ---------------------------------------------------------------------------
// Jotai atom test generation
// ---------------------------------------------------------------------------

interface JotaiAtomInfo {
  atomName: string;
  isWritable: boolean; // atom vs atomWithReset / readonlyAtom
  initialValue: string;
}

function generateJotaiTest(
  sourceFile: SourceFile,
  _checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string
): string | null {
  const atoms = detectJotaiAtoms(sourceFile);
  if (atoms.length === 0) return null;

  const importPath = relativeImport(testFilePath, sourceFilePath);
  const atomNames = atoms.map((a) => a.atomName);
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * @generated by react-testgen - deterministic output');
  lines.push(' * Jotai atom tests using @testing-library/react and Provider');
  lines.push(' */');
  lines.push('');
  lines.push(buildTestGlobalsImport(['describe', 'it', 'expect']));
  lines.push('');
  lines.push('import { renderHook, act } from "@testing-library/react";');
  lines.push('import { useAtom, useAtomValue, useSetAtom, createStore, Provider } from "jotai";');
  lines.push('import React from "react";');
  lines.push(`import { ${atomNames.join(', ')} } from "${importPath}";`);
  lines.push('');

  lines.push('/** Create a fresh Jotai store for each test to avoid state pollution */');
  lines.push('function makeWrapper() {');
  lines.push('  const store = createStore();');
  lines.push('  return ({ children }: { children: React.ReactNode }) =>');
  lines.push('    React.createElement(Provider, { store }, children);');
  lines.push('}');
  lines.push('');

  for (const atom of atoms) {
    lines.push(`describe("${atom.atomName}", () => {`);

    // Read initial value
    lines.push('  it("has a defined initial value", () => {');
    lines.push(`    const { result } = renderHook(() => useAtomValue(${atom.atomName}), {`);
    lines.push('      wrapper: makeWrapper(),');
    lines.push('    });');
    lines.push('    expect(result.current).toBeDefined();');
    lines.push('  });');
    lines.push('');

    if (atom.isWritable) {
      // Read + write
      lines.push('  it("can be read and written via useAtom", () => {');
      lines.push(`    const { result } = renderHook(() => useAtom(${atom.atomName}), {`);
      lines.push('      wrapper: makeWrapper(),');
      lines.push('    });');
      lines.push('    const [value, setValue] = result.current;');
      lines.push('    expect(value).toBeDefined();');
      lines.push('    expect(typeof setValue).toBe("function");');
      lines.push('  });');
      lines.push('');

      // Write new value
      lines.push('  it("updates value on write", () => {');
      lines.push(`    const { result } = renderHook(() => useAtom(${atom.atomName}), {`);
      lines.push('      wrapper: makeWrapper(),');
      lines.push('    });');
      lines.push('    const initialValue = result.current[0];');
      lines.push('    act(() => {');
      // Generate a write value based on initial value detection
      const writeValue = getJotaiWriteValue(atom);
      lines.push(`      result.current[1](${writeValue});`);
      lines.push('    });');
      lines.push('    expect(result.current[0]).toBeDefined();');
      lines.push('  });');
      lines.push('');
    }

    // Setter only
    lines.push('  it("exposes a setter via useSetAtom", () => {');
    lines.push(`    const { result } = renderHook(() => useSetAtom(${atom.atomName}), {`);
    lines.push('      wrapper: makeWrapper(),');
    lines.push('    });');
    lines.push('    expect(typeof result.current).toBe("function");');
    lines.push('  });');
    lines.push('');

    lines.push('});');
    lines.push('');
  }

  return lines.join('\n');
}

function getJotaiWriteValue(atom: JotaiAtomInfo): string {
  const initial = atom.initialValue.toLowerCase();
  if (initial === 'false' || initial === 'true') return 'true';
  if (/^\d+$/.test(initial)) return '42';
  if (initial.startsWith('"') || initial.startsWith("'")) return '"updated"';
  if (initial === '[]' || initial === 'null') return '[]';
  return '{}';
}

function detectJotaiAtoms(sourceFile: SourceFile): JotaiAtomInfo[] {
  const atoms: JotaiAtomInfo[] = [];
  const exported = sourceFile.getExportedDeclarations();

  for (const [name, decls] of exported) {
    for (const decl of decls) {
      const declText = decl.getText();
      // Detect atom() / atomWithReset() / atomWithStorage() calls
      if (!declText.includes('atom(') && !declText.includes('atom<')) continue;

      let initialValue = 'null';
      let isWritable = true;

      // Try to extract the initial value from atom(initialValue)
      const atomCallMatch = declText.match(/atom(?:<[^>]+>)?\(([^)]+)\)/);
      if (atomCallMatch) {
        const rawValue = atomCallMatch[1].trim();
        // Simple values only
        if (/^(null|undefined|false|true|[\d.]+|"[^"]*"|'[^']*'|\[\]|\{\})$/.test(rawValue)) {
          initialValue = rawValue;
        }
        // Read-only atoms (atom with getter fn but no setter)
        isWritable = !rawValue.startsWith('(get)') && !rawValue.startsWith('(get,');
      }

      // atomWithReset is always writable
      if (declText.includes('atomWithReset')) isWritable = true;
      // readAtom or selectAtom or computed atoms are read-only
      if (
        declText.includes('readAtom') ||
        (declText.includes('selectAtom') && !declText.includes('setAtom'))
      ) {
        isWritable = false;
      }

      atoms.push({ atomName: name, isWritable, initialValue });
      break;
    }
  }

  return atoms;
}
