import { ComponentInfo } from '../analyzer';
import { resolveRenderHelper } from '../utils/path';
import { ResolvedImportSymbol } from './semanticPlan';

export function buildHeader(): string {
  return '/** @generated by react-testgen - deterministic output */';
}

export function buildImports(importPlan: ResolvedImportSymbol[]): string {
  const sideEffectImports: string[] = [];
  const moduleEntries = new Map<string, {
    defaultImport?: string;
    namespaceImport?: string;
    namedImports: Array<{ symbolName: string; alias?: string }>;
  }>();

  for (const entry of importPlan) {
    if (entry.importKind === 'side-effect') {
      sideEffectImports.push(`import "${entry.modulePath}";`);
      continue;
    }

    const moduleEntry = moduleEntries.get(entry.modulePath) ?? { namedImports: [] as Array<{ symbolName: string; alias?: string }> };
    if (entry.importKind === 'default' && entry.symbolName) {
      moduleEntry.defaultImport = entry.symbolName;
    }
    if (entry.importKind === 'namespace' && entry.symbolName) {
      moduleEntry.namespaceImport = entry.symbolName;
    }
    if (entry.importKind === 'named' && entry.symbolName) {
      moduleEntry.namedImports.push({ symbolName: entry.symbolName, alias: entry.alias });
    }
    moduleEntries.set(entry.modulePath, moduleEntry);
  }

  const groupedImports = [...moduleEntries.entries()].map(([modulePath, entry]) => {
    const namedPart = entry.namedImports.length > 0
      ? `{ ${entry.namedImports.map((namedImport) => namedImport.alias ? `${namedImport.symbolName} as ${namedImport.alias}` : namedImport.symbolName).join(', ')} }`
      : '';
    const parts = [entry.defaultImport, entry.namespaceImport ? `* as ${entry.namespaceImport}` : undefined, namedPart]
      .filter((value): value is string => Boolean(value));
    return `import ${parts.join(', ')} from "${modulePath}";`;
  });

  return dedupeLines([...groupedImports, ...sideEffectImports]).join('\n');
}

export function getRenderFunctionName(component: ComponentInfo, sourceFilePath: string): string {
  if (component.usesRouter) return 'render';
  const helper = resolveRenderHelper(sourceFilePath);
  return helper ? helper.exportName : 'render';
}

export function buildDescribeStart(component: ComponentInfo): string {
  return `describe("${component.name}", () => {`;
}

export function buildDescribeEnd(): string {
  return '});';
}

export function buildTestBlock(title: string, bodyLines: string[]): string {
  const safeTitle = title.replace(/"/g, '\\"');
  const lines = [`  it("${safeTitle}", () => {`];
  for (const line of bodyLines) {
    lines.push(`    ${line}`);
  }
  lines.push('  });');
  return lines.join('\n');
}

export function buildAsyncTestBlock(title: string, bodyLines: string[]): string {
  const safeTitle = title.replace(/"/g, '\\"');
  const lines = [`  it("${safeTitle}", async () => {`];
  for (const line of bodyLines) {
    lines.push(`    ${line}`);
  }
  lines.push('  });');
  return lines.join('\n');
}

export function joinBlocks(blocks: string[]): string {
  return blocks.filter((block) => block.trim().length > 0).join('\n\n');
}

export function buildFileContent(parts: string[]): string {
  return parts.filter((part) => part.trim().length > 0).join('\n\n') + '\n';
}

function dedupeLines(lines: string[]): string[] {
  return [...new Set(lines.filter((line) => line.trim().length > 0))];
}
