import { relativeImport, resolveRenderHelper } from '../utils/path';
import { ComponentInfo } from '../analyzer';
import { buildDomMatchersImport, buildTestGlobalsImport, mockGlobalName } from '../utils/framework';
import type { RepairPlan } from '../healer/knowledge-base';

export interface TemplateOptions {
  testFilePath: string;
  sourceFilePath: string;
  usesUserEvent: boolean;
  needsScreen: boolean;
  /** Repair plan from the self-healing system. */
  repairPlan?: RepairPlan;
}

export function buildHeader(): string {
  return '/** @generated by react-testgen - deterministic output */';
}

export function buildImports(components: ComponentInfo[], options: TemplateOptions): string {
  const defaultComponents = components.filter((c) => c.exportType === 'default');
  const namedComponents = components.filter((c) => c.exportType === 'named');
  const componentImport = relativeImport(options.testFilePath, options.sourceFilePath);

  const imports: string[] = [];
  const needsPlainRender = components.some((c) => c.usesRouter);
  const needsProviders = components.some((c) => !c.usesRouter);
  const needsMockGlobal = components.some((c) => c.props.some((p) => p.isCallback));

  // Check if repair plan forces renderWithProviders
  const forceCustomRender = options.repairPlan?.actions.some(
    (a) => a.kind === 'use-render-helper' && a.helper === 'renderWithProviders'
  );

  const testGlobals = ['describe', 'it', 'expect'];
  if (needsMockGlobal) testGlobals.push(mockGlobalName());
  imports.push(buildTestGlobalsImport(testGlobals));
  imports.push(buildDomMatchersImport());

  // Check if a custom render helper exists in this project
  const renderHelper = resolveRenderHelper(options.sourceFilePath);
  const hasCustomRender = renderHelper !== null;

  if ((needsPlainRender || !hasCustomRender) && !forceCustomRender) {
    // Use plain render from RTL (either for router components, or when custom render doesn't exist)
    const rtlImports = ['render'];
    if (options.needsScreen) rtlImports.push('screen');
    // Check if repair plan needs async handling imports
    if (options.repairPlan?.actions.some((a) => a.kind === 'add-async-handling')) {
      const strategy = options.repairPlan.actions.find((a) => a.kind === 'add-async-handling');
      if (strategy && 'strategy' in strategy) {
        if (strategy.strategy === 'waitFor' && !rtlImports.includes('waitFor')) {
          rtlImports.push('waitFor');
        }
        if (strategy.strategy === 'act' && !rtlImports.includes('act')) {
          rtlImports.push('act');
        }
      }
    }
    imports.push(`import { ${rtlImports.join(', ')} } from "@testing-library/react";`);
  }

  if ((needsProviders && hasCustomRender) || (forceCustomRender && hasCustomRender)) {
    const testUtilsImport = relativeImport(options.testFilePath, renderHelper!.path);
    const renderFnName = renderHelper!.exportName;
    const testingImports = [renderFnName];
    if (!needsPlainRender && options.needsScreen) testingImports.push('screen');
    imports.push(`import { ${testingImports.join(', ')} } from "${testUtilsImport}";`);
  }

  if (options.usesUserEvent) {
    imports.push('import userEvent from "@testing-library/user-event";');
  }

  if (defaultComponents.length > 0 && namedComponents.length > 0) {
    imports.push(
      `import ${defaultComponents[0].name}, { ${namedComponents
        .map((c) => c.name)
        .join(', ')} } from "${componentImport}";`
    );
  } else if (defaultComponents.length > 0) {
    imports.push(`import ${defaultComponents[0].name} from "${componentImport}";`);
  } else {
    imports.push(
      `import { ${namedComponents.map((c) => c.name).join(', ')} } from "${componentImport}";`
    );
  }

  // Apply repair plan: add extra imports (idempotent — deduplicated)
  if (options.repairPlan) {
    const existingImportText = imports.join('\n');
    for (const action of options.repairPlan.actions) {
      if (action.kind === 'ensure-import' && action.module !== 'unknown') {
        const importLine = action.symbol
          ? `import { ${action.symbol} } from "${action.module}";`
          : `import "${action.module}";`;
        // Idempotent: don't add if already present
        if (!existingImportText.includes(action.module)) {
          imports.push(importLine);
        }
      }
      if (action.kind === 'add-wrapper') {
        // Add import for wrapper component if not already imported
        if (!existingImportText.includes(action.importFrom)) {
          if (action.wrapper === 'QueryClientProvider') {
            imports.push(`import { QueryClientProvider, QueryClient } from "${action.importFrom}";`);
          } else {
            imports.push(`import { ${action.wrapper} } from "${action.importFrom}";`);
          }
        }
      }
    }
  }

  return imports.join('\n');
}

/**
 * Determines which render function to use based on project structure.
 * Returns the actual export name from the detected render helper.
 */
export function getRenderFunctionName(component: ComponentInfo, sourceFilePath: string): string {
  if (component.usesRouter) return 'render';
  const helper = resolveRenderHelper(sourceFilePath);
  return helper ? helper.exportName : 'render';
}

export function buildDescribeStart(component: ComponentInfo): string {
  return `describe("${component.name}", () => {`;
}

export function buildDescribeEnd(): string {
  return '});';
}

export function buildTestBlock(title: string, bodyLines: string[]): string {
  const safeTitle = title.replace(/"/g, '\\"');
  const lines = [`  it("${safeTitle}", () => {`];
  for (const line of bodyLines) {
    lines.push(`    ${line}`);
  }
  lines.push('  });');
  return lines.join('\n');
}

export function buildAsyncTestBlock(title: string, bodyLines: string[]): string {
  const safeTitle = title.replace(/"/g, '\\"');
  const lines = [`  it("${safeTitle}", async () => {`];
  for (const line of bodyLines) {
    lines.push(`    ${line}`);
  }
  lines.push('  });');
  return lines.join('\n');
}

export function joinBlocks(blocks: string[]): string {
  return blocks.filter((b) => b.trim().length > 0).join('\n\n');
}

export function buildFileContent(parts: string[]): string {
  return parts.filter((p) => p.trim().length > 0).join('\n\n') + '\n';
}
