import path from 'path';
import fs from 'fs';
import { relativeImport } from '../utils/path';
import { listFilesRecursive } from '../fs';
import { ComponentInfo } from '../analyzer';

export interface TemplateOptions {
    testFilePath: string;
    sourceFilePath: string;
    usesUserEvent: boolean;
    needsScreen: boolean;
    renderFunction: string;
    renderImportLine?: string;
}

interface RenderHelperCandidate {
    file: string;
    exportName: string;
}

const RENDER_HELPER_CANDIDATES: RenderHelperCandidate[] = [
    { file: 'src/test-utils/renderWithProviders.tsx', exportName: 'renderWithProviders' },
    { file: 'src/test-utils/renderWithProviders.ts', exportName: 'renderWithProviders' },
    { file: 'src/util/testHelpers.tsx', exportName: 'renderWithProviders' },
    { file: 'src/util/testHelpers.ts', exportName: 'renderWithProviders' },
    { file: 'src/utils/testHelpers.tsx', exportName: 'renderWithProviders' },
    { file: 'src/utils/testHelpers.ts', exportName: 'renderWithProviders' },
];

let discoveredRenderHelpers: RenderHelperCandidate[] | null = null;

function discoverRenderHelperCandidates(): RenderHelperCandidate[] {
    if (discoveredRenderHelpers) {
        return discoveredRenderHelpers;
    }

    const srcRoot = path.join(process.cwd(), 'src');
    const dynamicHelpers: RenderHelperCandidate[] = [];

    if (fs.existsSync(srcRoot)) {
        const sourceFiles = listFilesRecursive(srcRoot).filter((file) => /\.(ts|tsx)$/.test(file));

        for (const sourceFile of sourceFiles) {
            const content = fs.readFileSync(sourceFile, 'utf8');
            const hasNamedExport = /export\s+(const|function)\s+renderWithProviders\b/.test(content);
            const hasReExport = /export\s*\{[^}]*\brenderWithProviders\b[^}]*\}/.test(content);

            if (!hasNamedExport && !hasReExport) {
                continue;
            }

            dynamicHelpers.push({
                file: path.relative(process.cwd(), sourceFile).replace(/\\/g, '/'),
                exportName: 'renderWithProviders',
            });
        }
    }

    const seen = new Set<string>();
    discoveredRenderHelpers = [...RENDER_HELPER_CANDIDATES, ...dynamicHelpers].filter((candidate) => {
        const key = `${candidate.file}:${candidate.exportName}`;
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
    });

    return discoveredRenderHelpers;
}

function pathDistance(fromFile: string, toFile: string): number {
    const fromParts = path.dirname(fromFile).split(path.sep).filter(Boolean);
    const toParts = path.dirname(toFile).split(path.sep).filter(Boolean);

    let i = 0;
    while (i < fromParts.length && i < toParts.length && fromParts[i] === toParts[i]) {
        i += 1;
    }

    return (fromParts.length - i) + (toParts.length - i);
}

export function resolveRenderFunction(testFilePath: string): { name: string; importLine?: string } {
    const candidates = discoverRenderHelperCandidates();

    const resolved = candidates
        .map((candidate) => ({
            ...candidate,
            absolute: path.join(process.cwd(), candidate.file),
        }))
        .filter((candidate) => fs.existsSync(candidate.absolute))
        .sort((a, b) => pathDistance(testFilePath, a.absolute) - pathDistance(testFilePath, b.absolute))[0];

    if (resolved) {
        const helperImport = relativeImport(testFilePath, resolved.absolute);
        return {
            name: resolved.exportName,
            importLine: `import { ${resolved.exportName} } from "${helperImport}";`,
        };
    }

    return { name: 'render' };
}

export function buildHeader(): string {
    return '/** @generated by react-testgen - deterministic output */';
}

export function buildImports(
    components: ComponentInfo[],
    options: TemplateOptions
): string {
    const defaultComponents = components.filter((c) => c.exportType === 'default');
    const namedComponents = components.filter((c) => c.exportType === 'named');
    const componentImport = relativeImport(options.testFilePath, options.sourceFilePath);

    const imports: string[] = [];
    const rtlImports = new Set<string>();

    if (options.needsScreen) {
        rtlImports.add('screen');
    }

    if (options.renderFunction === 'render') {
        rtlImports.add('render');
    }

    if (rtlImports.size > 0) {
        imports.push(`import { ${Array.from(rtlImports).join(', ')} } from "@testing-library/react";`);
    }

    if (options.renderFunction !== 'render' && options.renderImportLine) {
        imports.push(options.renderImportLine);
    }

    if (options.usesUserEvent) {
        imports.push('import userEvent from "@testing-library/user-event";');
    }

    if (defaultComponents.length > 0 && namedComponents.length > 0) {
        imports.push(
            `import ${defaultComponents[0].name}, { ${namedComponents
                .map((c) => c.name)
                .join(', ')} } from "${componentImport}";`
        );
    } else if (defaultComponents.length > 0) {
        imports.push(`import ${defaultComponents[0].name} from "${componentImport}";`);
    } else {
        imports.push(`import { ${namedComponents.map((c) => c.name).join(', ')} } from "${componentImport}";`);
    }

    return imports.join('\n');
}

export function buildDescribeStart(component: ComponentInfo): string {
    return `describe("${component.name}", () => {`;
}

export function buildDescribeEnd(): string {
    return '});';
}

export function buildTestBlock(title: string, bodyLines: string[]): string {
    const lines = [`  it("${title}", () => {`];
    for (const line of bodyLines) {
        lines.push(`    ${line}`);
    }
    lines.push('  });');
    return lines.join('\n');
}

export function buildAsyncTestBlock(title: string, bodyLines: string[]): string {
    const lines = [`  it("${title}", async () => {`];
    for (const line of bodyLines) {
        lines.push(`    ${line}`);
    }
    lines.push('  });');
    return lines.join('\n');
}

export function joinBlocks(blocks: string[]): string {
    return blocks.filter((b) => b.trim().length > 0).join('\n\n');
}

export function buildFileContent(parts: string[]): string {
    return parts.filter((p) => p.trim().length > 0).join('\n\n') + '\n';
}
