import path from 'node:path';
import fs from 'node:fs';
import {
  SourceFile,
  Node,
  SyntaxKind,
  FunctionDeclaration,
  TypeChecker,
  ReturnStatement,
} from 'ts-morph';
import { relativeImport, resolveRenderHelper } from '../utils/path';
import { buildTestGlobalsImport, mockFn, mockGlobalName, mockModuleFn } from '../utils/framework';
import { CONTEXT_DETECTION_CONFIG } from '../config';

interface ExportedFunction {
  name: string;
  params: ParamInfo[];
  returnType: string;
  isAsync: boolean;
  hasBody: boolean;
  parentObjectName?: string; // e.g., "authService" for authService.login
  sourceNode?: Node; // AST node for deeper analysis
}

interface ParamInfo {
  name: string;
  type: string;
  isOptional: boolean;
  hasDefault: boolean;
}

interface SwitchCaseInfo {
  paramName: string;
  values: string[];
  /** When the switch is on a property (e.g. action.type), this holds the property name */
  propertyPath?: string;
}

class LineBuilder {
  private readonly entries: string[] = [];

  get length(): number {
    return this.entries.length;
  }

  add(...values: string[]): void {
    this.entries.push(...values);
  }

  join(separator: string): string {
    return this.entries.join(separator);
  }
}

/**
 * Generates tests for non-component TypeScript files:
 * utility functions, helpers, formatters, validators, services, hooks, etc.
 */
export function generateUtilityTest( // NOSONAR - generator intentionally builds deterministic output through exhaustive branch templates
  sourceFile: SourceFile,
  checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string,
  fileType?: 'service' | 'utility'
): string | null {
  const functions = getExportedFunctions(sourceFile, checker);
  if (functions.length === 0) return null;

  const importPath = relativeImport(testFilePath, sourceFilePath);
  const lines = new LineBuilder();
  const sourceText = sourceFile.getText();

  lines.add('/** @generated by react-testgen - deterministic output */');

  // Detect if we need module-level mocks for service files
  // Also detect when a service file imports from a local api module (e.g., import api from './api')
  // These files use axios indirectly and need the api module to be mocked
  const apiImportPath = detectApiImportPath(sourceFile, testFilePath);
  const needsAxiosMock =
    sourceText.includes('axios') ||
    sourceText.includes("from 'axios'") ||
    sourceText.includes('from "axios"');
  const needsApiMockOnly = !needsAxiosMock && apiImportPath !== null && fileType === 'service';
  const needsLocalStorageMock = sourceText.includes('localStorage');
  const needsURLMock =
    sourceText.includes('URL.createObjectURL') || sourceText.includes('URL.revokeObjectURL');
  const needsClipboardMock = sourceText.includes('navigator.clipboard');
  const usesFunctionLikeParams = functions.some((func) =>
    func.params.some(
      (param) =>
        param.type.includes('=>') ||
        /\bfunction\b/i.test(param.type) ||
        /^(on|handle|set|update|change|toggle|add|remove|delete|clear)[A-Z]/.test(param.name)
    )
  );
  const needsLifecycleHooks = needsURLMock || needsClipboardMock || needsLocalStorageMock;
  const needsMockGlobal =
    needsAxiosMock || needsApiMockOnly || needsLifecycleHooks || usesFunctionLikeParams;
  const testGlobals = ['describe', 'it', 'expect'];
  if (needsLifecycleHooks) testGlobals.push('beforeEach');
  if (needsURLMock) testGlobals.push('afterEach');
  if (needsMockGlobal) testGlobals.push(mockGlobalName());
  lines.add(buildTestGlobalsImport(testGlobals));
  lines.add('');

  if (needsAxiosMock) {
    const mockModule = mockModuleFn();
    lines.add('');
    // Create a comprehensive mock that handles axios.create() returning a mock instance
    // The response interceptor's success handler is called with response.data, so we mock accordingly
    lines.add(`const mockAxiosInstance = {`);
    lines.add(`  get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  interceptors: {`);
    lines.add(`    request: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.add(`    response: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.add(`  },`);
    lines.add(`  defaults: { headers: { common: {} } },`);
    lines.add(`};`);
    lines.add('');
    lines.add(`${mockModule}('axios', () => ({`);
    lines.add('  __esModule: true,');
    lines.add('  default: {');
    lines.add('    create: () => mockAxiosInstance,');
    lines.add(`    get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`    post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`    put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`    delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`    patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`    defaults: { headers: { common: {} } },`);
    lines.add(
      `    interceptors: { request: { use: ${mockFn()} }, response: { use: ${mockFn()} } },`
    );
    lines.add('  },');
    lines.add('  create: () => mockAxiosInstance,');
    lines.add(`  get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  defaults: { headers: { common: {} } },`);
    lines.add(`  interceptors: { request: { use: ${mockFn()} }, response: { use: ${mockFn()} } },`);
    lines.add('}));');
    lines.add('');
    // Also mock the local api module if it exists, to bypass interceptors
    if (apiImportPath) {
      lines.add('// Mock the local api module to bypass interceptors');
      lines.add(`${mockModule}("${apiImportPath}", () => ({`);
      lines.add('  __esModule: true,');
      lines.add('  default: mockAxiosInstance,');
      lines.add('}));');
    }
  }

  // For service files that import from a local api module but don't use axios directly
  if (needsApiMockOnly && apiImportPath) {
    const mockModule = mockModuleFn();
    lines.add('');
    lines.add(`const mockAxiosInstance = {`);
    lines.add(`  get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.add(`  interceptors: {`);
    lines.add(`    request: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.add(`    response: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.add(`  },`);
    lines.add(`  defaults: { headers: { common: {} } },`);
    lines.add(`};`);
    lines.add('');
    lines.add('// Mock the local api module to intercept HTTP calls');
    lines.add(`${mockModule}("${apiImportPath}", () => ({`);
    lines.add('  __esModule: true,');
    lines.add('  default: mockAxiosInstance,');
    // Also export named exports that might be used (e.g., setAuthToken, clearAuthTokens)
    lines.add(`  setAuthToken: ${mockFn()},`);
    lines.add(`  setRefreshToken: ${mockFn()},`);
    lines.add(`  clearAuthTokens: ${mockFn()},`);
    lines.add('}));');
  }

  if (needsURLMock) {
    const addCloseHookBlock = () => lines.add('});');
    lines.add('');
    lines.add('beforeEach(() => {');
    lines.add(`  global.URL.createObjectURL = ${mockFn()}.mockImplementation(() => "blob:mock-url");`);
    lines.add(`  global.URL.revokeObjectURL = ${mockFn()};`);
    addCloseHookBlock();
    lines.add('afterEach(() => {');
    lines.add('  (global.URL.createObjectURL as any) = undefined;');
    lines.add('  (global.URL.revokeObjectURL as any) = undefined;');
    addCloseHookBlock();
  }

  if (needsClipboardMock) {
    lines.add('');
    lines.add('beforeEach(() => {');
    lines.add('  Object.assign(navigator, {');
    lines.add('    clipboard: {');
    lines.add(`      writeText: ${mockFn()}.mockResolvedValue(undefined),`);
    lines.add(`      readText: ${mockFn()}.mockResolvedValue(""),`);
    lines.add('    },');
    lines.add('  });');
    lines.add('});');
  }

  if (needsLocalStorageMock) {
    lines.add('');
    lines.add('const mockStorage: Record<string, string> = {};');
    lines.add('beforeEach(() => {');
    lines.add('  Object.keys(mockStorage).forEach(k => delete mockStorage[k]);');
    lines.add('  Object.defineProperty(window, "localStorage", {');
    lines.add('    value: {');
    lines.add(
      `      getItem: ${mockFn()}.mockImplementation((key: string) => mockStorage[key] ?? null),`
    );
    lines.add(
      `      setItem: ${mockFn()}.mockImplementation((key: string, val: string) => { mockStorage[key] = val; }),`
    );
    lines.add(
      `      removeItem: ${mockFn()}.mockImplementation((key: string) => { delete mockStorage[key]; }),`
    );
    lines.add(
      `      clear: ${mockFn()}.mockImplementation(() => { Object.keys(mockStorage).forEach(k => delete mockStorage[k]); }),`
    );
    lines.add('      length: 0,');
    lines.add(`      key: ${mockFn()}.mockReturnValue(null),`);
    lines.add('    },');
    lines.add('    writable: true,');
    lines.add('  });');
    lines.add('});');
  }

  // Build imports - group by parentObjectName
  const objectExports = new Set<string>();
  const directExports: ExportedFunction[] = [];
  const defaultExport = functions.find((f) => f.name === 'default');

  for (const func of functions) {
    if (func.name === 'default') continue;
    if (func.parentObjectName) {
      objectExports.add(func.parentObjectName);
    } else {
      directExports.push(func);
    }
  }

  const importNames = [...directExports.map((f) => f.name), ...Array.from(objectExports)];

  if (importNames.length > 0) {
    lines.add(`import { ${importNames.join(', ')} } from "${importPath}";`);
  }
  if (defaultExport) {
    lines.add(`import defaultExport from "${importPath}";`);
  }

  lines.add('');

  // Check if any function is a React hook
  const hasHooks = functions.some((f) => /^use[A-Z]/.test(f.name));
  const needsQueryClient =
    sourceText.includes('useQuery') ||
    sourceText.includes('useMutation') ||
    sourceText.includes('@tanstack/react-query');
  // Detect if hooks use context providers that require wrapping with renderWithProviders
  // Uses CONTEXT_DETECTION_CONFIG.customContexts so no hardcoded names are needed here
  const needsProviderWrapper = CONTEXT_DETECTION_CONFIG.customContexts.some((ctx) =>
    ctx.hooks.some((h) => sourceText.includes(h))
  );
  // Check if a custom render helper (renderWithProviders) exists in the project
  const renderHelper = resolveRenderHelper(sourceFilePath);
  const useRenderWithProviders = hasHooks && needsProviderWrapper && renderHelper !== null;

  // For hooks needing providers, needsQueryClient wrapper is always true
  const effectiveNeedsQueryClient = needsQueryClient || useRenderWithProviders;

  if (hasHooks) {
    lines.add('import { renderHook, act } from "@testing-library/react";');
    if (useRenderWithProviders) {
      lines.add('import { QueryClient, QueryClientProvider } from "@tanstack/react-query";');
      lines.add('import React from "react";');
      // Import the context providers this hook depends on
      const providerImports = detectHookProviderImports(sourceFile, sourceText, testFilePath);
      for (const pi of providerImports) {
        lines.add(pi);
      }
      lines.add('');
      lines.add('const createTestQueryClient = () => new QueryClient({');
      lines.add(
        '  defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },'
      );
      lines.add('});');
      lines.add('');
      lines.add('function createWrapper() {');
      lines.add('  const queryClient = createTestQueryClient();');
      lines.add('  return ({ children }: { children: React.ReactNode }) => {');
      // Build nested providers using React.createElement (outermost first)
      const providerNames = detectRequiredProviders(sourceText);
      let wrapperExpr = 'children';
      // Wrap innermost to outermost (reverse so outermost is applied last)
      for (const prov of [...providerNames].reverse()) {
        wrapperExpr = `React.createElement(${prov}, null, ${wrapperExpr})`;
      }
      wrapperExpr = `React.createElement(QueryClientProvider, { client: queryClient }, ${wrapperExpr})`;
      lines.add(`    return ${wrapperExpr};`);
      lines.add('  };');
      lines.add('}');
    } else if (needsQueryClient) {
      lines.add('import { QueryClient, QueryClientProvider } from "@tanstack/react-query";');
      lines.add('import React from "react";');
      lines.add('');
      lines.add('const createTestQueryClient = () => new QueryClient({');
      lines.add(
        '  defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },'
      );
      lines.add('});');
      lines.add('');
      lines.add('function createWrapper() {');
      lines.add('  const queryClient = createTestQueryClient();');
      lines.add('  return ({ children }: { children: React.ReactNode }) =>');
      lines.add('    React.createElement(QueryClientProvider, { client: queryClient }, children);');
      lines.add('}');
    }
    lines.add('');
  }

  // Generate tests grouped by parentObjectName
  const grouped = groupByParent(functions.filter((f) => f.name !== 'default'));

  for (const [parentName, funcs] of grouped) {
    if (parentName) {
      // Object-exported methods: describe("authService", () => { ... })
      lines.add(`describe("${parentName}", () => {`);
      for (const func of funcs) {
        if (/^use[A-Z]/.test(func.name)) {
          generateHookTests(lines, func, sourceFile, '  ', effectiveNeedsQueryClient);
        } else {
          generateObjectMethodTests(lines, func, sourceFile, '  ');
        }
      }
      lines.add('});');
      lines.add('');
    } else {
      // Direct exports
      for (const func of funcs) {
        if (/^use[A-Z]/.test(func.name)) {
          generateHookTests(lines, func, sourceFile, '', effectiveNeedsQueryClient);
        } else {
          generateFunctionTests(lines, func, sourceFile, '');
        }
      }
    }
  }

  if (lines.length <= 3) return null;
  lines.add('');
  return lines.join('\n');
}

/**
 * Group functions by their parentObjectName
 */
function groupByParent(functions: ExportedFunction[]): Map<string | undefined, ExportedFunction[]> {
  const map = new Map<string | undefined, ExportedFunction[]>();
  for (const func of functions) {
    const key = func.parentObjectName;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(func);
  }
  return map;
}

/**
 * Tests for methods on an exported object (e.g., authService.login)
 */
function generateObjectMethodTests( // NOSONAR - template-style test generation intentionally branches by signature shape
  lines: LineBuilder,
  func: ExportedFunction,
  sourceFile: SourceFile,
  indent: string
): void {
  const parent = func.parentObjectName!;
  const callExpr = `${parent}.${func.name}`;

  lines.add(`${indent}describe("${func.name}", () => {`);

  // Test 1: Method exists and is callable
  lines.add(`${indent}  it("is defined", () => {`);
  lines.add(`${indent}    expect(${callExpr}).toBeDefined();`);
  lines.add(`${indent}    expect(typeof ${callExpr}).toBe("function");`);
  lines.add(`${indent}  });`);
  lines.add('');

  // Test 2: Call with typical args
  const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
  const isVoid = func.returnType === 'void' || func.returnType === 'Promise<void>';

  if (func.isAsync) {
    lines.add(`${indent}  it("resolves without throwing", async () => {`);
    lines.add(`${indent}    try {`);
    if (isVoid) {
      lines.add(`${indent}      await ${callExpr}(${mockArgs});`);
    } else {
      lines.add(`${indent}      const result = await ${callExpr}(${mockArgs});`);
      lines.add(`${indent}      expect(result).toBeDefined();`);
    }
    lines.add(`${indent}    } catch (error) {`);
    lines.add(`${indent}      expect(error).toBeDefined();`);
    lines.add(`${indent}    }`);
    lines.add(`${indent}  });`);
  } else {
    // Sync path: use try/catch for non-void functions because service methods that look up
    // data by ID (e.g. updateExpense, findById) throw when the test-data ID is not found.
    lines.add(`${indent}  it("returns without throwing", () => {`);
    if (isVoid) {
      lines.add(`${indent}    expect(() => ${callExpr}(${mockArgs})).not.toThrow();`);
    } else {
      lines.add(`${indent}    try {`);
      lines.add(`${indent}      const result = ${callExpr}(${mockArgs});`);
      lines.add(`${indent}      expect(result).toBeDefined();`);
      lines.add(`${indent}    } catch (error) {`);
      lines.add(`${indent}      expect(error).toBeDefined();`);
      lines.add(`${indent}    }`);
    }
    lines.add(`${indent}  });`);
  }
  lines.add('');

  // Test 3: Minimal args if there are optional params
  const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
  if (requiredParams.length < func.params.length) {
    const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
    if (func.isAsync) {
      lines.add(`${indent}  it("works with minimal arguments", async () => {`);
      lines.add(`${indent}    try {`);
      if (isVoid) {
        lines.add(`${indent}      await ${callExpr}(${minArgs});`);
      } else {
        lines.add(`${indent}      const result = await ${callExpr}(${minArgs});`);
        lines.add(`${indent}      expect(result).toBeDefined();`);
      }
      lines.add(`${indent}    } catch (error) {`);
      lines.add(`${indent}      expect(error).toBeDefined();`);
      lines.add(`${indent}    }`);
      lines.add(`${indent}  });`);
    } else {
      lines.add(`${indent}  it("works with minimal arguments", () => {`);
      if (isVoid) {
        lines.add(`${indent}    expect(() => ${callExpr}(${minArgs})).not.toThrow();`);
      } else {
        lines.add(`${indent}    try {`);
        lines.add(`${indent}      const result = ${callExpr}(${minArgs});`);
        lines.add(`${indent}      expect(result).toBeDefined();`);
        lines.add(`${indent}    } catch (error) {`);
        lines.add(`${indent}      expect(error).toBeDefined();`);
        lines.add(`${indent}    }`);
      }
      lines.add(`${indent}  });`);
    }
    lines.add('');
  }

  // Test 4: Error path for async methods
  if (func.isAsync) {
    lines.add(`${indent}  it("handles errors gracefully", async () => {`);
    lines.add(`${indent}    try {`);
    lines.add(`${indent}      await ${callExpr}(${mockArgs});`);
    lines.add(`${indent}    } catch (error) {`);
    lines.add(`${indent}      expect(error).toBeDefined();`);
    lines.add(`${indent}    }`);
    lines.add(`${indent}  });`);
    lines.add('');
  }

  // Test 5: Edge cases (wrapped in try-catch to handle expected errors like invalid inputs)
  for (const param of func.params.slice(0, 3)) {
    const edgeCases = getEdgeCases(param);
    for (const edgeCase of edgeCases) {
      const argsWithEdge = func.params
        .map((p) => (p.name === param.name ? edgeCase.value : mockValueForParam(p)))
        .join(', ');

      if (func.isAsync) {
        lines.add(`${indent}  it("handles ${edgeCase.label} for ${param.name}", async () => {`);
        lines.add(`${indent}    try {`);
        if (isVoid) {
          lines.add(`${indent}      await ${callExpr}(${argsWithEdge});`);
        } else {
          lines.add(`${indent}      const result = await ${callExpr}(${argsWithEdge});`);
          lines.add(`${indent}      expect(result).toBeDefined();`);
        }
        lines.add(`${indent}    } catch (error) {`);
        lines.add(`${indent}      expect(error).toBeDefined();`);
        lines.add(`${indent}    }`);
        lines.add(`${indent}  });`);
      } else {
        lines.add(`${indent}  it("handles ${edgeCase.label} for ${param.name}", () => {`);
        lines.add(`${indent}    try {`);
        if (isVoid) {
          lines.add(`${indent}      ${callExpr}(${argsWithEdge});`);
        } else {
          lines.add(`${indent}      const result = ${callExpr}(${argsWithEdge});`);
          lines.add(`${indent}      expect(result).toBeDefined();`);
        }
        lines.add(`${indent}    } catch (error) {`);
        lines.add(`${indent}      expect(error).toBeDefined();`);
        lines.add(`${indent}    }`);
        lines.add(`${indent}  });`);
      }
      lines.add('');
    }
  }

  lines.add(`${indent}});`);
  lines.add('');
}

function generateFunctionTests( // NOSONAR - template-style test generation intentionally branches by signature shape
  lines: LineBuilder,
  func: ExportedFunction,
  sourceFile: SourceFile,
  indent: string
): void {
  lines.add(`${indent}describe("${func.name}", () => {`);

  // Test 1: Function exists and is callable
  lines.add(`${indent}  it("is defined", () => {`);
  lines.add(`${indent}    expect(${func.name}).toBeDefined();`);
  lines.add(`${indent}    expect(typeof ${func.name}).toBe("function");`);
  lines.add(`${indent}  });`);
  lines.add('');

  // Test 2: Call with typical args
  const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
  const isVoid = func.returnType === 'void' || func.returnType === 'Promise<void>';

  if (func.isAsync) {
    lines.add(`${indent}  it("resolves without throwing", async () => {`);
    lines.add(`${indent}    try {`);
    if (isVoid) {
      lines.add(`${indent}      await ${func.name}(${mockArgs});`);
    } else {
      lines.add(`${indent}      const result = await ${func.name}(${mockArgs});`);
      lines.add(`${indent}      expect(result).toBeDefined();`);
    }
    lines.add(`${indent}    } catch (error) {`);
    lines.add(`${indent}      expect(error).toBeDefined();`);
    lines.add(`${indent}    }`);
    lines.add(`${indent}  });`);
  } else {
    // Sync path: use try/catch for non-void functions — utility/helper functions can throw
    // for certain inputs (e.g. invalid arguments, missing data lookups).
    lines.add(`${indent}  it("returns without throwing", () => {`);
    if (isVoid) {
      lines.add(`${indent}    expect(() => ${func.name}(${mockArgs})).not.toThrow();`);
    } else {
      lines.add(`${indent}    try {`);
      lines.add(`${indent}      const result = ${func.name}(${mockArgs});`);
      lines.add(`${indent}      expect(result).toBeDefined();`);
      lines.add(`${indent}    } catch (error) {`);
      lines.add(`${indent}      expect(error).toBeDefined();`);
      lines.add(`${indent}    }`);
    }
    lines.add(`${indent}  });`);
  }
  lines.add('');

  // Test 3: For functions with optional params, call with minimal args
  const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
  if (requiredParams.length < func.params.length) {
    const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
    if (func.isAsync) {
      lines.add(`${indent}  it("works with minimal arguments", async () => {`);
      lines.add(`${indent}    try {`);
      if (isVoid) {
        lines.add(`${indent}      await ${func.name}(${minArgs});`);
      } else {
        lines.add(`${indent}      const result = await ${func.name}(${minArgs});`);
        lines.add(`${indent}      expect(result).toBeDefined();`);
      }
      lines.add(`${indent}    } catch (error) {`);
      lines.add(`${indent}      expect(error).toBeDefined();`);
      lines.add(`${indent}    }`);
      lines.add(`${indent}  });`);
    } else {
      lines.add(`${indent}  it("works with minimal arguments", () => {`);
      if (isVoid) {
        lines.add(`${indent}    expect(() => ${func.name}(${minArgs})).not.toThrow();`);
      } else {
        lines.add(`${indent}    try {`);
        lines.add(`${indent}      const result = ${func.name}(${minArgs});`);
        lines.add(`${indent}      expect(result).toBeDefined();`);
        lines.add(`${indent}    } catch (error) {`);
        lines.add(`${indent}      expect(error).toBeDefined();`);
        lines.add(`${indent}    }`);
      }
      lines.add(`${indent}  });`);
    }
    lines.add('');
  }

  // Test 4: Edge cases for specific param types
  // Edge cases can throw (e.g., invalid currency code, negative decimals for toFixed),
  // so wrap in try-catch to ensure the test doesn't fail unexpectedly
  for (const param of func.params.slice(0, 3)) {
    const edgeCases = getEdgeCases(param);
    for (const edgeCase of edgeCases) {
      const argsWithEdge = func.params
        .map((p) => (p.name === param.name ? edgeCase.value : mockValueForParam(p)))
        .join(', ');

      if (func.isAsync) {
        lines.add(`${indent}  it("handles ${edgeCase.label} for ${param.name}", async () => {`);
        lines.add(`${indent}    try {`);
        if (isVoid) {
          lines.add(`${indent}      await ${func.name}(${argsWithEdge});`);
        } else {
          lines.add(`${indent}      const result = await ${func.name}(${argsWithEdge});`);
          lines.add(`${indent}      expect(result).toBeDefined();`);
        }
        lines.add(`${indent}    } catch (error) {`);
        lines.add(`${indent}      expect(error).toBeDefined();`);
        lines.add(`${indent}    }`);
        lines.add(`${indent}  });`);
      } else {
        lines.add(`${indent}  it("handles ${edgeCase.label} for ${param.name}", () => {`);
        lines.add(`${indent}    try {`);
        if (isVoid) {
          lines.add(`${indent}      ${func.name}(${argsWithEdge});`);
        } else {
          lines.add(`${indent}      const result = ${func.name}(${argsWithEdge});`);
          lines.add(`${indent}      expect(result).toBeDefined();`);
        }
        lines.add(`${indent}    } catch (error) {`);
        lines.add(`${indent}      expect(error).toBeDefined();`);
        lines.add(`${indent}    }`);
        lines.add(`${indent}  });`);
      }
      lines.add('');
    }
  }

  // Test 5: Switch/case branch coverage
  const switchCases = detectSwitchCases(func, sourceFile);
  for (const switchCase of switchCases) {
    for (const caseValue of switchCase.values) {
      // When the switch is on a property (e.g. `action.type`), wrap the case value
      // in an object: { type: "ADD_TOAST" } instead of passing "ADD_TOAST" directly
      const paramValue = switchCase.propertyPath
        ? `{ ${switchCase.propertyPath}: ${caseValue} }`
        : caseValue;

      const argsWithCase = func.params
        .map((p) => (p.name === switchCase.paramName ? paramValue : mockValueForParam(p)))
        .join(', ');

      // Strip outer quotes so the title string stays valid JS
      // e.g. "DISMISS_TOAST" → DISMISS_TOAST (no embedded quotes in the it() string)
      const displayValue = caseValue.replace(/^['"`]|['"`]$/g, '');
      lines.add(`${indent}  it("handles case ${displayValue} for ${switchCase.paramName}", () => {`);
      lines.add(`${indent}    const result = ${func.name}(${argsWithCase});`);
      lines.add(`${indent}    expect(result).toBeDefined();`);
      lines.add(`${indent}  });`);
      lines.add('');
    }
  }

  // Test 6: For functions that return functions (debounce, throttle patterns)
  if (func.returnType.includes('=>') || func.returnType.includes('Function')) {
    lines.add(`${indent}  it("returns a callable function", () => {`);
    lines.add(`${indent}    const result = ${func.name}(${mockArgs});`);
    lines.add(`${indent}    expect(typeof result).toBe("function");`);
    lines.add(`${indent}    result();`);
    lines.add(`${indent}  });`);
    lines.add('');
  }

  lines.add(`${indent}});`);
  lines.add('');
}

function generateHookTests( // NOSONAR - hook template generation requires conditional paths for tuple/object/query wrappers
  lines: LineBuilder,
  func: ExportedFunction,
  sourceFile: SourceFile,
  indent: string,
  needsQueryClient = false
): void {
  lines.add(`${indent}describe("${func.name}", () => {`);

  const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
  const argsString = mockArgs ? `() => ${func.name}(${mockArgs})` : `() => ${func.name}()`;
  const wrapperOpt = needsQueryClient ? ', { wrapper: createWrapper() }' : '';

  lines.add(`${indent}  it("initializes without error", () => {`);
  lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
  lines.add(`${indent}    expect(result.current).toBeDefined();`);
  lines.add(`${indent}  });`);
  lines.add('');

  // Test with minimal args if there are optional params
  const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
  if (requiredParams.length < func.params.length) {
    const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
    const minArgsString = minArgs ? `() => ${func.name}(${minArgs})` : `() => ${func.name}()`;
    lines.add(`${indent}  it("works with minimal arguments", () => {`);
    lines.add(`${indent}    const { result } = renderHook(${minArgsString}${wrapperOpt});`);
    lines.add(`${indent}    expect(result.current).toBeDefined();`);
    lines.add(`${indent}  });`);
    lines.add('');
  }

  // Detect return shape and generate targeted tests
  const returnShape = detectHookReturnShape(func, sourceFile);

  if (returnShape.type === 'tuple') {
    // Array/tuple return like [value, setValue, removeValue]
    lines.add(`${indent}  it("returns expected tuple structure", () => {`);
    lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
    lines.add(`${indent}    expect(Array.isArray(result.current)).toBe(true);`);
    if (returnShape.length) {
      lines.add(`${indent}    expect(result.current).toHaveLength(${returnShape.length});`);
    }
    lines.add(`${indent}  });`);
    lines.add('');

    // Test each function in the tuple
    for (const idx of returnShape.functionIndices) {
      lines.add(`${indent}  it("provides callable function at index ${idx}", () => {`);
      lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.add(`${indent}    expect(typeof result.current[${idx}]).toBe("function");`);
      lines.add(`${indent}  });`);
      lines.add('');

      lines.add(`${indent}  it("can call function at index ${idx} with act", () => {`);
      lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.add(`${indent}    act(() => {`);
      lines.add(`${indent}      result.current[${idx}]("test-value");`);
      lines.add(`${indent}    });`);
      lines.add(`${indent}    expect(result.current).toBeDefined();`);
      lines.add(`${indent}  });`);
      lines.add('');
    }
  } else if (returnShape.type === 'object') {
    // Object return like { data, isLoading, error, fetchData }
    for (const method of returnShape.methods) {
      lines.add(`${indent}  it("provides ${method} function", () => {`);
      lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.add(`${indent}    expect(typeof result.current.${method}).toBe("function");`);
      lines.add(`${indent}  });`);
      lines.add('');

      if (isSafeHookMethodToInvoke(method)) {
        lines.add(`${indent}  it("can call ${method} with act", () => {`);
        lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
        lines.add(`${indent}    act(() => {`);
        lines.add(`${indent}      result.current.${method}();`);
        lines.add(`${indent}    });`);
        lines.add(`${indent}    expect(result.current).toBeDefined();`);
        lines.add(`${indent}  });`);
        lines.add('');
      }
    }

    for (const state of returnShape.stateProps) {
      lines.add(`${indent}  it("provides ${state} state", () => {`);
      lines.add(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.add(`${indent}    expect(result.current).toHaveProperty("${state}");`);
      lines.add(`${indent}  });`);
      lines.add('');
    }
  }

  // Rerender test if hook has params
  if (func.params.length > 0) {
    const rerenderArgs = func.params.map((p) => mockValueForParam(p, true)).join(', ');
    const rerenderWrapperOpt = needsQueryClient ? ', wrapper: createWrapper()' : '';
    const hookPropArgs = func.params.map((_, i) => `props.p${i}`).join(', ');
    const initialProps = func.params.map((p, i) => `p${i}: ${mockValueForParam(p)}`).join(', ');
    const rerenderValues = rerenderArgs.split(', ');
    const rerenderProps = func.params
      .map((p, i) => `p${i}: ${rerenderValues[i] || mockValueForParam(p, true)}`)
      .join(', ');
    lines.add(`${indent}  it("handles rerender with new arguments", () => {`);
    lines.add(`${indent}    const { result, rerender } = renderHook(`);
    lines.add(`${indent}      (props) => ${func.name}(${hookPropArgs}),`);
    lines.add(`${indent}      { initialProps: { ${initialProps} }${rerenderWrapperOpt} }`);
    lines.add(`${indent}    );`);
    lines.add(`${indent}    rerender({ ${rerenderProps} });`);
    lines.add(`${indent}    expect(result.current).toBeDefined();`);
    lines.add(`${indent}  });`);
    lines.add('');
  }

  lines.add(`${indent}});`);
  lines.add('');
}

// --- Analysis helpers ---

interface HookReturnShape {
  type: 'tuple' | 'object' | 'unknown';
  length?: number;
  functionIndices: number[];
  methods: string[];
  stateProps: string[];
}

function detectHookReturnShape(func: ExportedFunction, sourceFile: SourceFile): HookReturnShape {
  const shape: HookReturnShape = {
    type: 'unknown',
    functionIndices: [],
    methods: [],
    stateProps: [],
  };

  const funcNode = findFunctionByName(sourceFile, func.name);
  if (!funcNode) return shape;

  const returnStatements = getDirectReturnStatements(funcNode);

  for (const ret of returnStatements) {
    const expr = ret.getExpression();
    if (!expr) continue;

    if (Node.isArrayLiteralExpression(expr)) {
      analyzeTupleReturn(expr, shape);
      return shape;
    }

    if (Node.isObjectLiteralExpression(expr)) {
      analyzeObjectReturn(expr, shape);
      return shape;
    }
  }

  return shape;
}

function getDirectReturnStatements(funcNode: Node): ReturnStatement[] {
  return funcNode.getDescendantsOfKind(SyntaxKind.ReturnStatement).filter((ret) => {
    let parent: Node | undefined = ret.getParent();
    while (parent && parent !== funcNode) {
      if (
        Node.isArrowFunction(parent) ||
        Node.isFunctionExpression(parent) ||
        Node.isMethodDeclaration(parent) ||
        Node.isFunctionDeclaration(parent)
      ) {
        return false;
      }
      parent = parent.getParent();
    }
    return parent === funcNode;
  });
}

function isLikelyTupleFunctionName(text: string): boolean {
  return (
    /^set[A-Z]/.test(text) ||
    /^(handle|toggle|remove|clear|reset|add|update|delete|fetch|load|save|dispatch)/.test(text)
  );
}

function maybeAddTupleFunctionIndex(shape: HookReturnShape, idx: number): void {
  if (!shape.functionIndices.includes(idx)) {
    shape.functionIndices.push(idx);
  }
}

function analyzeTupleReturn(expr: Node, shape: HookReturnShape): void {
  if (!Node.isArrayLiteralExpression(expr)) return;
  shape.type = 'tuple';
  const elements = expr.getElements();
  shape.length = elements.length;

  elements.forEach((el, idx) => {
    const text = el.getText();
    if (isLikelyTupleFunctionName(text)) {
      maybeAddTupleFunctionIndex(shape, idx);
    }

    if (!Node.isIdentifier(el)) return;
    const name = el.getText();
    if (
      /^set[A-Z]/.test(name) ||
      name.startsWith('remove') ||
      name.startsWith('toggle') ||
      name.startsWith('clear')
    ) {
      maybeAddTupleFunctionIndex(shape, idx);
    }
  });
}

function classifyHookObjectProperty(name: string): 'method' | 'state' | 'unknown' {
  const methodPrefix = CONTEXT_DETECTION_CONFIG.methodPatterns.join('|');
  const statePrefix = CONTEXT_DETECTION_CONFIG.statePatterns.join('|');

  if (new RegExp(`^(${methodPrefix}|mutate|invalidate|refetch|bulk)`).test(name)) {
    return 'method';
  }
  if (
    new RegExp(
      `^(${statePrefix}|expenses|categories|budgets|notifications|pagination|filters|sort)`
    ).test(name)
  ) {
    return 'state';
  }
  return 'unknown';
}

function analyzeObjectReturn(expr: Node, shape: HookReturnShape): void {
  if (!Node.isObjectLiteralExpression(expr)) return;
  shape.type = 'object';

  for (const prop of expr.getProperties()) {
    if (Node.isMethodDeclaration(prop)) {
      shape.methods.push(prop.getName());
      continue;
    }

    if (!Node.isShorthandPropertyAssignment(prop) && !Node.isPropertyAssignment(prop)) {
      continue;
    }

    const name = prop.getName();
    const category = classifyHookObjectProperty(name);
    if (category === 'method') shape.methods.push(name);
    if (category === 'state') shape.stateProps.push(name);
  }
}

function isSafeHookMethodToInvoke(methodName: string): boolean {
  return /^(set|toggle|reset|clear|open|close|show|hide|select|deselect)/i.test(methodName);
}

function detectSwitchCases(func: ExportedFunction, sourceFile: SourceFile): SwitchCaseInfo[] {
  const results: SwitchCaseInfo[] = [];

  const funcNode = findFunctionByName(sourceFile, func.name);
  if (!funcNode) return results;

  const switchStatements = funcNode.getDescendantsOfKind(SyntaxKind.SwitchStatement);
  for (const switchStmt of switchStatements) {
    const switchExpr = switchStmt.getExpression().getText();

    // Detect property access patterns like `action.type`
    let matchedParam: ParamInfo | undefined;
    let propertyPath: string | undefined;

    // First try exact match (switch on param directly)
    matchedParam = func.params.find((p) => switchExpr === p.name);

    if (!matchedParam) {
      // Try property access: e.g. `action.type` → param = action, propertyPath = type
      const dotIndex = switchExpr.indexOf('.');
      if (dotIndex > 0) {
        const baseName = switchExpr.slice(0, dotIndex);
        matchedParam = func.params.find((p) => p.name === baseName);
        if (matchedParam) {
          propertyPath = switchExpr.slice(dotIndex + 1);
        }
      }
    }

    if (!matchedParam) {
      // Fallback: loose match (switch expr includes param name)
      matchedParam = func.params.find(
        (p) => switchExpr.endsWith(`.${p.name}`) || switchExpr.includes(p.name)
      );
    }

    if (!matchedParam) continue;

    const values: string[] = [];
    for (const clause of switchStmt.getClauses()) {
      if (Node.isCaseClause(clause)) {
        const exprText = clause.getExpression().getText();
        // Only include string/number literals
        if (/^['"]/.test(exprText) || /^\d+$/.test(exprText)) {
          values.push(exprText);
        }
      }
    }

    if (values.length > 0) {
      results.push({ paramName: matchedParam.name, values, propertyPath });
    }
  }

  return results;
}

function findFunctionByName(sourceFile: SourceFile, name: string): Node | null {
  // Check function declarations
  for (const func of sourceFile.getFunctions()) {
    if (func.getName() === name) return func;
  }

  // Check variable declarations (arrow functions)
  for (const variable of sourceFile.getVariableDeclarations()) {
    if (variable.getName() === name) {
      const init = variable.getInitializer();
      if (init && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))) {
        return init;
      }
    }
  }

  return null;
}

function getExportedFunctions(sourceFile: SourceFile, checker: TypeChecker): ExportedFunction[] {
  const functions: ExportedFunction[] = [];

  collectExportedFunctionDeclarations(functions, sourceFile, checker);
  collectExportedVariableFunctions(functions, sourceFile, checker);

  return functions;
}

function collectExportedFunctionDeclarations(
  functions: ExportedFunction[],
  sourceFile: SourceFile,
  checker: TypeChecker
): void {
  for (const func of sourceFile.getFunctions()) {
    if (!func.isExported()) continue;
    const name = func.getName();
    if (!name) continue;

    functions.push({
      name,
      params: extractParams(func.getParameters(), checker),
      returnType: func.getReturnType().getText(),
      isAsync: func.isAsync(),
      hasBody: func.getBody() !== undefined,
      sourceNode: func,
    });
  }
}

function collectExportedVariableFunctions(
  functions: ExportedFunction[],
  sourceFile: SourceFile,
  checker: TypeChecker
): void {
  for (const stmt of sourceFile.getVariableStatements()) {
    if (!stmt.isExported()) continue;

    for (const decl of stmt.getDeclarations()) {
      const init = decl.getInitializer();
      if (!init) continue;

      if (Node.isArrowFunction(init) || Node.isFunctionExpression(init)) {
        functions.push({
          name: decl.getName(),
          params: extractParams(init.getParameters(), checker),
          returnType: init.getReturnType().getText(),
          isAsync: init.isAsync(),
          hasBody: true,
          sourceNode: init,
        });
      }

      if (Node.isObjectLiteralExpression(init)) {
        collectObjectLiteralExportMethods(functions, sourceFile, checker, decl.getName(), init);
      }
    }
  }
}

function collectObjectLiteralExportMethods(
  functions: ExportedFunction[],
  sourceFile: SourceFile,
  checker: TypeChecker,
  parentName: string,
  objectLiteral: Node
): void {
  if (!Node.isObjectLiteralExpression(objectLiteral)) return;

  for (const prop of objectLiteral.getProperties()) {
    if (Node.isMethodDeclaration(prop)) {
      functions.push({
        name: prop.getName(),
        params: extractParams(prop.getParameters(), checker),
        returnType: prop.getReturnType().getText(),
        isAsync: prop.isAsync(),
        hasBody: prop.getBody() !== undefined,
        parentObjectName: parentName,
        sourceNode: prop,
      });
      continue;
    }

    if (Node.isPropertyAssignment(prop)) {
      const value = prop.getInitializer();
      if (value && (Node.isArrowFunction(value) || Node.isFunctionExpression(value))) {
        functions.push({
          name: prop.getName(),
          params: extractParams(value.getParameters(), checker),
          returnType: value.getReturnType().getText(),
          isAsync: value.isAsync(),
          hasBody: true,
          parentObjectName: parentName,
          sourceNode: value,
        });
      }
      continue;
    }

    if (!Node.isShorthandPropertyAssignment(prop)) continue;

    const propName = prop.getName();
    const resolvedFunc = findFunctionByName(sourceFile, propName);
    if (!resolvedFunc) continue;

    const params = resolvedFunc.getDescendantsOfKind(SyntaxKind.Parameter);
    functions.push({
      name: propName,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      params: extractParams(params as any, checker),
      returnType: 'unknown',
      isAsync: resolvedFunc.getText().includes('async'),
      hasBody: true,
      parentObjectName: parentName,
      sourceNode: resolvedFunc,
    });
  }
}

function extractParams(
  params: ReturnType<FunctionDeclaration['getParameters']>,
  checker: TypeChecker
): ParamInfo[] {
  return params.map((param) => {
    let typeText = 'unknown';
    try {
      const type = checker.getTypeAtLocation(param);
      typeText = type.getText();
    } catch {
      // Type resolution may fail for complex generics
    }
    return {
      name: param.getName(),
      type: typeText,
      isOptional: param.isOptional(),
      hasDefault: param.hasInitializer(),
    };
  });
}

function mockValueForParam(param: ParamInfo, alternate = false): string {
  const type = param.type.toLowerCase();
  const name = param.name.toLowerCase();

  if (/^options?$/.test(name)) return '{ enabled: false }';

  const direct = matchDirectParamMock(type, name, alternate);
  if (direct) return direct;

  const fallback = matchNameFallbackMock(name, alternate);
  return fallback ?? '{}';
}

function contextualMock(name: string, type: string, alternate = false): string {
  if (type === 'string') return resolveContextMock(name, alternate, STRING_CONTEXT_RULES);
  if (type === 'number') return resolveContextMock(name, alternate, NUMBER_CONTEXT_RULES);
  return '{}';
}

function matchDirectParamMock(type: string, name: string, alternate: boolean): string | null {
  if (isFunctionLikeType(type, name)) return mockFn();

  const typeRuleResult = resolveTypeRuleMock(type, name, alternate);
  if (typeRuleResult !== null) return typeRuleResult;

  if (type.includes('{') || type.includes('record') || type === 'object') return '{}';
  if (type.includes('null')) return 'null';
  if (type.includes('undefined')) return 'undefined';
  return null;
}

function resolveContextMock(
  name: string,
  alternate: boolean,
  rules: Array<{ pattern: RegExp; primary: string; alternate: string }>
): string {
  const matchedRule = rules.find((rule) => rule.pattern.test(name));
  if (matchedRule) return alternate ? matchedRule.alternate : matchedRule.primary;
  if (rules === STRING_CONTEXT_RULES) {
    return alternate ? '"other-value"' : '"test-value"';
  }
  return alternate ? '2' : '1';
}

function isFunctionLikeType(type: string, name: string): boolean {
  if (type.includes('=>') || type.includes('function')) return true;
  return /^(fn|func|callback|handler|listener|predicate|comparator|reducer|mapper|transformer)$/i.test(
    name
  );
}

function resolveTypeRuleMock(type: string, name: string, alternate: boolean): string | null {
  if (type === 'string') return contextualMock(name, 'string', alternate);
  if (type === 'number') return contextualMock(name, 'number', alternate);
  if (type === 'boolean') return alternate ? 'false' : 'true';
  if (type.includes('[]')) return alternate ? '[{ id: "1" }]' : '[]';
  if (type === 'date' || type === 'Date') {
    return alternate ? 'new Date("2025-06-15")' : 'new Date("2024-01-01")';
  }
  return null;
}

function matchNameFallbackMock(name: string, alternate: boolean): string | null {
  const stringRules: Array<{ pattern: RegExp; primary: string; alternate: string }> = [
    { pattern: /id$/i, primary: '"test-id"', alternate: '"test-id-2"' },
    { pattern: /name$/i, primary: '"Test"', alternate: '"Other"' },
    { pattern: /email/i, primary: '"test@example.com"', alternate: '"other@example.com"' },
    { pattern: /url|path/i, primary: '"/test"', alternate: '"/other"' },
  ];

  for (const rule of stringRules) {
    if (rule.pattern.test(name)) return alternate ? rule.alternate : rule.primary;
  }

  const numberRules: Array<{ pattern: RegExp; primary: string; alternate: string }> = [
    { pattern: /amount|price|value/i, primary: '100', alternate: '200' },
    { pattern: /count|index/i, primary: '0', alternate: '1' },
  ];

  for (const rule of numberRules) {
    if (rule.pattern.test(name)) return alternate ? rule.alternate : rule.primary;
  }

  return null;
}

const STRING_CONTEXT_RULES: Array<{ pattern: RegExp; primary: string; alternate: string }> = [
  { pattern: /date/i, primary: '"2024-01-01"', alternate: '"2025-06-15"' },
  { pattern: /email/i, primary: '"test@example.com"', alternate: '"other@example.com"' },
  { pattern: /url/i, primary: '"https://example.com"', alternate: '"https://other.com"' },
  { pattern: /key/i, primary: '"test-key"', alternate: '"other-key"' },
  { pattern: /format/i, primary: '"default"', alternate: '"custom"' },
  { pattern: /type|kind|status|mode/i, primary: '"primary"', alternate: '"secondary"' },
  { pattern: /query|search|filter/i, primary: '"test"', alternate: '"other"' },
  { pattern: /token/i, primary: '"test-token"', alternate: '"other-token"' },
  { pattern: /password/i, primary: '"test-pass"', alternate: '"other-pass"' },
  { pattern: /currency/i, primary: '"USD"', alternate: '"EUR"' },
];

const NUMBER_CONTEXT_RULES: Array<{ pattern: RegExp; primary: string; alternate: string }> = [
  { pattern: /amount|price/i, primary: '100', alternate: '200' },
  { pattern: /page/i, primary: '1', alternate: '2' },
  { pattern: /limit|size/i, primary: '10', alternate: '20' },
  { pattern: /year/i, primary: '2024', alternate: '2025' },
];

interface EdgeCase {
  label: string;
  value: string;
}

/**
 * Detect provider imports needed for hook tests.
 * When a hook uses useNotification, useAuth, etc., we need to import the corresponding providers.
 */
function detectHookProviderImports( // NOSONAR - provider import resolution handles aliases, filesystem fallbacks, and import variants
  sourceFile: SourceFile,
  sourceText: string,
  testFilePath: string
): string[] {
  const imports: string[] = [];
  const imported = new Set<string>();

  // Build context map from CONTEXT_DETECTION_CONFIG.customContexts — no hardcoded names
  const contextMap = CONTEXT_DETECTION_CONFIG.customContexts.flatMap((ctx) =>
    ctx.hooks.map((hook) => ({
      pattern: hook,
      providerName: ctx.providerName,
      contextFile: ctx.contextName,
    }))
  );

  for (const ctx of contextMap) {
    if (sourceText.includes(ctx.pattern) && !imported.has(ctx.providerName)) {
      // Find the actual import path from the source file
      for (const imp of sourceFile.getImportDeclarations()) {
        const moduleSpec = imp.getModuleSpecifierValue();
        for (const named of imp.getNamedImports()) {
          if (named.getName() === ctx.pattern || named.getName() === ctx.providerName) {
            const sourceDir = path.dirname(sourceFile.getFilePath());
            const testDir = path.dirname(testFilePath);

            // Handle path aliases like @/contexts, ~/contexts
            if (moduleSpec.startsWith('@/') || moduleSpec.startsWith('~/')) {
              // @/ typically maps to src/ — find the src root
              const aliasPath = moduleSpec.replace(/^[@~]\//, '');
              // Walk up from sourceDir to find the src root
              let srcRoot = sourceDir;
              while (
                srcRoot &&
                !fs.existsSync(path.join(srcRoot, aliasPath + '.ts')) &&
                !fs.existsSync(path.join(srcRoot, aliasPath + '.tsx')) &&
                !fs.existsSync(path.join(srcRoot, aliasPath, 'index.ts')) &&
                !fs.existsSync(path.join(srcRoot, aliasPath, 'index.tsx'))
              ) {
                const parent = path.dirname(srcRoot);
                if (parent === srcRoot) break;
                srcRoot = parent;
              }
              const resolvedPath = path.resolve(srcRoot, aliasPath);
              let relativePath = path.relative(testDir, resolvedPath).replace(/\\/g, '/'); // NOSONAR - replaceAll unavailable for current TS target
              if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
              relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
              imports.push(`import { ${ctx.providerName} } from "${relativePath}";`);
              imported.add(ctx.providerName);
              break;
            }

            // Regular relative import
            const resolvedPath = path.resolve(sourceDir, moduleSpec);
            let relativePath = path.relative(testDir, resolvedPath).replace(/\\/g, '/'); // NOSONAR - replaceAll unavailable for current TS target
            if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
            relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
            imports.push(`import { ${ctx.providerName} } from "${relativePath}";`);
            imported.add(ctx.providerName);
            break;
          }
        }
        if (imported.has(ctx.providerName)) break;
      }

      // Fallback: try to construct the import path from convention
      if (!imported.has(ctx.providerName)) {
        // Try common patterns: ../contexts/NotificationContext
        const testDir = path.dirname(testFilePath);
        const possiblePaths = [
          `../contexts/${ctx.contextFile}`,
          `../../contexts/${ctx.contextFile}`,
          `../context/${ctx.contextFile}`,
        ];
        for (const pp of possiblePaths) {
          const absPath = path.resolve(testDir, pp);
          const extensions = ['.tsx', '.ts', '.jsx', '.js'];
          for (const ext of extensions) {
            try {
              if (fs.existsSync(absPath + ext)) {
                imports.push(`import { ${ctx.providerName} } from "${pp}";`);
                imported.add(ctx.providerName);
                break;
              }
            } catch {
              /* ignore */
            }
          }
          if (imported.has(ctx.providerName)) break;
        }
      }
    }
  }

  return imports;
}

/**
 * Detect which providers a hook needs by analyzing its source text.
 */
/**
 * Detect if the source file imports from a local api module (e.g., './api', '../services/api')
 * Returns the import path as-is so we can mock it.
 */
function detectApiImportPath(sourceFile: SourceFile, testFilePath?: string): string | null {
  for (const imp of sourceFile.getImportDeclarations()) {
    const moduleSpec = imp.getModuleSpecifierValue();
    // Match local imports that look like api modules
    if (moduleSpec.startsWith('.') && /\bapi\b/i.test(moduleSpec)) {
      // If we have a testFilePath, resolve the module path relative to the test file location
      if (testFilePath) {
        const sourceDir = path.dirname(sourceFile.getFilePath());
        const resolvedModule = path.resolve(sourceDir, moduleSpec);
        const testDir = path.dirname(testFilePath);
        let relativePath = path.relative(testDir, resolvedModule).replace(/\\/g, '/'); // NOSONAR - replaceAll unavailable for current TS target
        if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
        return relativePath;
      }
      return moduleSpec;
    }
  }
  return null;
}

function detectRequiredProviders(sourceText: string): string[] {
  // Driven by CONTEXT_DETECTION_CONFIG.customContexts — no hardcoded names
  // Order matters: outermost providers first (as listed in config)
  const providers: string[] = [];
  for (const ctx of CONTEXT_DETECTION_CONFIG.customContexts) {
    if (ctx.hooks.some((h) => sourceText.includes(h))) {
      providers.push(ctx.providerName);
    }
  }
  return providers;
}

function getEdgeCases(param: ParamInfo): EdgeCase[] {
  const type = param.type.toLowerCase();
  const cases: EdgeCase[] = [];

  if (type === 'string' || type.includes('string')) {
    cases.push(
      { label: 'empty string', value: '""' },
      { label: 'long string', value: '"' + 'a'.repeat(200) + '"' }
    );
  }
  if (type === 'number' || type.includes('number')) {
    cases.push(
      { label: 'zero', value: '0' },
      { label: 'negative number', value: '-1' },
      { label: 'large number', value: '999999' }
    );
  }
  if (type.includes('[]')) {
    cases.push(
      { label: 'empty array', value: '[]' },
      { label: 'single item array', value: '[{ id: "1" }]' }
    );
  }
  if (type.includes('boolean')) {
    cases.push({ label: 'false value', value: 'false' });
  }

  return cases;
}
