import { SourceFile, Node, SyntaxKind, FunctionDeclaration, VariableDeclaration, Type, TypeChecker } from 'ts-morph';
import { relativeImport } from '../utils/path';
import { mockFn } from '../utils/framework';

interface ExportedFunction {
    name: string;
    params: ParamInfo[];
    returnType: string;
    isAsync: boolean;
    hasBody: boolean;
}

interface ParamInfo {
    name: string;
    type: string;
    isOptional: boolean;
    hasDefault: boolean;
}

/**
 * Generates tests for non-component TypeScript files:
 * utility functions, helpers, formatters, validators, services, hooks, etc.
 */
export function generateUtilityTest(
    sourceFile: SourceFile,
    checker: TypeChecker,
    testFilePath: string,
    sourceFilePath: string
): string | null {
    const functions = getExportedFunctions(sourceFile, checker);
    if (functions.length === 0) return null;

    const importPath = relativeImport(testFilePath, sourceFilePath);
    const lines: string[] = [];

    lines.push('/** @generated by react-testgen - deterministic output */');

    // Determine import style
    const defaultExport = functions.find((f) => f.name === 'default');
    const namedExports = functions.filter((f) => f.name !== 'default');

    if (namedExports.length > 0) {
        lines.push(`import { ${namedExports.map((f) => f.name).join(', ')} } from "${importPath}";`);
    }
    if (defaultExport) {
        lines.push(`import defaultExport from "${importPath}";`);
    }

    lines.push('');

    // Check if any function is a React hook
    const hasHooks = functions.some((f) => /^use[A-Z]/.test(f.name));
    if (hasHooks) {
        lines.push('import { renderHook, act } from "@testing-library/react";');
        lines.push('');
    }

    for (const func of namedExports) {
        if (/^use[A-Z]/.test(func.name)) {
            generateHookTests(lines, func);
        } else {
            generateFunctionTests(lines, func);
        }
    }

    if (lines.length <= 3) return null;
    lines.push('');
    return lines.join('\n');
}

function generateFunctionTests(lines: string[], func: ExportedFunction): void {
    lines.push(`describe("${func.name}", () => {`);

    // Test 1: Function exists and is callable
    lines.push(`  it("is defined", () => {`);
    lines.push(`    expect(${func.name}).toBeDefined();`);
    lines.push(`    expect(typeof ${func.name}).toBe("function");`);
    lines.push(`  });`);
    lines.push('');

    // Test 2: Call with typical args
    const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');

    if (func.isAsync) {
        lines.push(`  it("resolves without throwing", async () => {`);
        lines.push(`    await expect(${func.name}(${mockArgs})).resolves.toBeDefined();`);
        lines.push(`  });`);
    } else {
        lines.push(`  it("returns without throwing", () => {`);
        lines.push(`    const result = ${func.name}(${mockArgs});`);
        lines.push(`    expect(result).toBeDefined();`);
        lines.push(`  });`);
    }
    lines.push('');

    // Test 3: For functions with optional params, call with minimal args
    const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
    if (requiredParams.length < func.params.length) {
        const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
        if (func.isAsync) {
            lines.push(`  it("works with minimal arguments", async () => {`);
            lines.push(`    const result = await ${func.name}(${minArgs});`);
            lines.push(`    expect(result).toBeDefined();`);
            lines.push(`  });`);
        } else {
            lines.push(`  it("works with minimal arguments", () => {`);
            lines.push(`    const result = ${func.name}(${minArgs});`);
            lines.push(`    expect(result).toBeDefined();`);
            lines.push(`  });`);
        }
        lines.push('');
    }

    // Test 4: Edge cases for specific param types
    for (const param of func.params.slice(0, 3)) {
        const edgeCases = getEdgeCases(param);
        for (const edgeCase of edgeCases) {
            const argsWithEdge = func.params.map((p) =>
                p.name === param.name ? edgeCase.value : mockValueForParam(p)
            ).join(', ');

            if (func.isAsync) {
                lines.push(`  it("handles ${edgeCase.label} for ${param.name}", async () => {`);
                lines.push(`    const result = await ${func.name}(${argsWithEdge});`);
                lines.push(`    expect(result).toBeDefined();`);
                lines.push(`  });`);
            } else {
                lines.push(`  it("handles ${edgeCase.label} for ${param.name}", () => {`);
                lines.push(`    const result = ${func.name}(${argsWithEdge});`);
                lines.push(`    expect(result).toBeDefined();`);
                lines.push(`  });`);
            }
            lines.push('');
        }
    }

    lines.push('});');
    lines.push('');
}

function generateHookTests(lines: string[], func: ExportedFunction): void {
    lines.push(`describe("${func.name}", () => {`);

    const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
    const argsString = mockArgs ? `() => ${func.name}(${mockArgs})` : `() => ${func.name}()`;

    lines.push(`  it("initializes without error", () => {`);
    lines.push(`    const { result } = renderHook(${argsString});`);
    lines.push(`    expect(result.current).toBeDefined();`);
    lines.push(`  });`);
    lines.push('');

    // Test with minimal args if there are optional params
    const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
    if (requiredParams.length < func.params.length && requiredParams.length >= 0) {
        const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
        const minArgsString = minArgs ? `() => ${func.name}(${minArgs})` : `() => ${func.name}()`;
        lines.push(`  it("works with minimal arguments", () => {`);
        lines.push(`    const { result } = renderHook(${minArgsString});`);
        lines.push(`    expect(result.current).toBeDefined();`);
        lines.push(`  });`);
        lines.push('');
    }

    lines.push('});');
    lines.push('');
}

function getExportedFunctions(sourceFile: SourceFile, checker: TypeChecker): ExportedFunction[] {
    const functions: ExportedFunction[] = [];

    // Exported function declarations
    for (const func of sourceFile.getFunctions()) {
        if (!func.isExported()) continue;
        const name = func.getName();
        if (!name) continue;

        functions.push({
            name,
            params: extractParams(func.getParameters(), checker),
            returnType: func.getReturnType().getText(),
            isAsync: func.isAsync(),
            hasBody: func.getBody() !== undefined,
        });
    }

    // Exported variable declarations (arrow functions, const functions)
    for (const stmt of sourceFile.getVariableStatements()) {
        if (!stmt.isExported()) continue;
        for (const decl of stmt.getDeclarations()) {
            const init = decl.getInitializer();
            if (!init) continue;

            if (Node.isArrowFunction(init) || Node.isFunctionExpression(init)) {
                functions.push({
                    name: decl.getName(),
                    params: extractParams(init.getParameters(), checker),
                    returnType: init.getReturnType().getText(),
                    isAsync: init.isAsync(),
                    hasBody: true,
                });
            }
        }
    }

    return functions;
}

function extractParams(
    params: ReturnType<FunctionDeclaration['getParameters']>,
    checker: TypeChecker
): ParamInfo[] {
    return params.map((param) => {
        const type = checker.getTypeAtLocation(param);
        return {
            name: param.getName(),
            type: type.getText(),
            isOptional: param.isOptional(),
            hasDefault: param.hasInitializer(),
        };
    });
}

function mockValueForParam(param: ParamInfo): string {
    const type = param.type.toLowerCase();
    const name = param.name.toLowerCase();

    if (type.includes('=>') || type.includes('function')) return mockFn();
    if (type === 'string') return contextualMock(name, 'string');
    if (type === 'number') return contextualMock(name, 'number');
    if (type === 'boolean') return 'true';
    if (type.includes('[]')) return '[]';
    if (type.includes('date')) return 'new Date("2024-01-01")';
    if (type.includes('null')) return 'null';
    if (type.includes('undefined')) return 'undefined';
    if (type.includes('{') || type === 'object' || type.includes('record')) return '{}';

    // Name-based fallbacks
    if (/id$/i.test(name)) return '"test-id"';
    if (/name$/i.test(name)) return '"Test"';
    if (/email/i.test(name)) return '"test@example.com"';
    if (/url/i.test(name) || /path/i.test(name)) return '"/test"';
    if (/amount/i.test(name) || /price/i.test(name) || /value/i.test(name)) return '100';
    if (/count/i.test(name) || /index/i.test(name)) return '0';

    return '{}';
}

function contextualMock(name: string, type: string): string {
    if (type === 'string') {
        if (/date/i.test(name)) return '"2024-01-01"';
        if (/email/i.test(name)) return '"test@example.com"';
        if (/url/i.test(name)) return '"https://example.com"';
        if (/key/i.test(name)) return '"test-key"';
        if (/format/i.test(name)) return '"default"';
        return '"test-value"';
    }
    if (type === 'number') {
        if (/amount/i.test(name) || /price/i.test(name)) return '100';
        if (/page/i.test(name)) return '1';
        if (/limit/i.test(name) || /size/i.test(name)) return '10';
        return '1';
    }
    return '{}';
}

interface EdgeCase {
    label: string;
    value: string;
}

function getEdgeCases(param: ParamInfo): EdgeCase[] {
    const type = param.type.toLowerCase();
    const cases: EdgeCase[] = [];

    if (type === 'string' || type.includes('string')) {
        cases.push({ label: 'empty string', value: '""' });
    }
    if (type === 'number' || type.includes('number')) {
        cases.push({ label: 'zero', value: '0' });
    }
    if (type.includes('[]')) {
        cases.push({ label: 'empty array', value: '[]' });
    }

    return cases;
}
