import path from 'path';
import fs from 'fs';
import { SourceFile, Node, SyntaxKind, FunctionDeclaration, TypeChecker } from 'ts-morph';
import { relativeImport, resolveRenderHelper } from '../utils/path';
import { mockFn, mockModuleFn } from '../utils/framework';
import { CONTEXT_DETECTION_CONFIG } from '../config';

interface ExportedFunction {
  name: string;
  params: ParamInfo[];
  returnType: string;
  isAsync: boolean;
  hasBody: boolean;
  parentObjectName?: string; // e.g., "authService" for authService.login
  sourceNode?: Node; // AST node for deeper analysis
}

interface ParamInfo {
  name: string;
  type: string;
  isOptional: boolean;
  hasDefault: boolean;
}

interface SwitchCaseInfo {
  paramName: string;
  values: string[];
}

/**
 * Generates tests for non-component TypeScript files:
 * utility functions, helpers, formatters, validators, services, hooks, etc.
 */
export function generateUtilityTest(
  sourceFile: SourceFile,
  checker: TypeChecker,
  testFilePath: string,
  sourceFilePath: string,
  fileType?: 'service' | 'utility'
): string | null {
  const functions = getExportedFunctions(sourceFile, checker);
  if (functions.length === 0) return null;

  const importPath = relativeImport(testFilePath, sourceFilePath);
  const lines: string[] = [];
  const sourceText = sourceFile.getText();

  lines.push('/** @generated by react-testgen - deterministic output */');

  // Detect if we need module-level mocks for service files
  // Also detect when a service file imports from a local api module (e.g., import api from './api')
  // These files use axios indirectly and need the api module to be mocked
  const apiImportPath = detectApiImportPath(sourceFile, testFilePath);
  const needsAxiosMock =
    sourceText.includes('axios') ||
    sourceText.includes("from 'axios'") ||
    sourceText.includes('from "axios"');
  const needsApiMockOnly = !needsAxiosMock && apiImportPath !== null && fileType === 'service';
  const needsLocalStorageMock = sourceText.includes('localStorage');

  if (needsAxiosMock) {
    const mockModule = mockModuleFn();
    lines.push('');
    // Create a comprehensive mock that handles axios.create() returning a mock instance
    // The response interceptor's success handler is called with response.data, so we mock accordingly
    lines.push(`const mockAxiosInstance = {`);
    lines.push(`  get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  interceptors: {`);
    lines.push(`    request: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.push(`    response: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.push(`  },`);
    lines.push(`  defaults: { headers: { common: {} } },`);
    lines.push(`};`);
    lines.push('');
    lines.push(`${mockModule}('axios', () => ({`);
    lines.push('  __esModule: true,');
    lines.push('  default: {');
    lines.push('    create: () => mockAxiosInstance,');
    lines.push(`    get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`    post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`    put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`    delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`    patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`    defaults: { headers: { common: {} } },`);
    lines.push(
      `    interceptors: { request: { use: ${mockFn()} }, response: { use: ${mockFn()} } },`
    );
    lines.push('  },');
    lines.push('  create: () => mockAxiosInstance,');
    lines.push(`  get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  defaults: { headers: { common: {} } },`);
    lines.push(
      `  interceptors: { request: { use: ${mockFn()} }, response: { use: ${mockFn()} } },`
    );
    lines.push('}));');
    lines.push('');
    // Also mock the local api module if it exists, to bypass interceptors
    if (apiImportPath) {
      lines.push('// Mock the local api module to bypass interceptors');
      lines.push(`${mockModule}("${apiImportPath}", () => ({`);
      lines.push('  __esModule: true,');
      lines.push('  default: mockAxiosInstance,');
      lines.push('}));');
    }
  }

  // For service files that import from a local api module but don't use axios directly
  if (needsApiMockOnly && apiImportPath) {
    const mockModule = mockModuleFn();
    lines.push('');
    lines.push(`const mockAxiosInstance = {`);
    lines.push(`  get: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  post: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  put: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  delete: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  patch: ${mockFn()}.mockResolvedValue({ data: {} }),`);
    lines.push(`  interceptors: {`);
    lines.push(`    request: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.push(`    response: { use: ${mockFn()}, eject: ${mockFn()} },`);
    lines.push(`  },`);
    lines.push(`  defaults: { headers: { common: {} } },`);
    lines.push(`};`);
    lines.push('');
    lines.push('// Mock the local api module to intercept HTTP calls');
    lines.push(`${mockModule}("${apiImportPath}", () => ({`);
    lines.push('  __esModule: true,');
    lines.push('  default: mockAxiosInstance,');
    // Also export named exports that might be used (e.g., setAuthToken, clearAuthTokens)
    lines.push(`  setAuthToken: ${mockFn()},`);
    lines.push(`  setRefreshToken: ${mockFn()},`);
    lines.push(`  clearAuthTokens: ${mockFn()},`);
    lines.push('}));');
  }

  // Detect browser API usage that needs mocking in jsdom
  const needsURLMock =
    sourceText.includes('URL.createObjectURL') || sourceText.includes('URL.revokeObjectURL');
  const needsClipboardMock = sourceText.includes('navigator.clipboard');

  if (needsURLMock) {
    lines.push('');
    lines.push('beforeEach(() => {');
    lines.push('  global.URL.createObjectURL = jest.fn(() => "blob:mock-url");');
    lines.push('  global.URL.revokeObjectURL = jest.fn();');
    lines.push('});');
    lines.push('afterEach(() => {');
    lines.push('  (global.URL.createObjectURL as any) = undefined;');
    lines.push('  (global.URL.revokeObjectURL as any) = undefined;');
    lines.push('});');
  }

  if (needsClipboardMock) {
    lines.push('');
    lines.push('beforeEach(() => {');
    lines.push('  Object.assign(navigator, {');
    lines.push('    clipboard: {');
    lines.push(`      writeText: ${mockFn()}.mockResolvedValue(undefined),`);
    lines.push(`      readText: ${mockFn()}.mockResolvedValue(""),`);
    lines.push('    },');
    lines.push('  });');
    lines.push('});');
  }

  if (needsLocalStorageMock) {
    lines.push('');
    lines.push('const mockStorage: Record<string, string> = {};');
    lines.push('beforeEach(() => {');
    lines.push('  Object.keys(mockStorage).forEach(k => delete mockStorage[k]);');
    lines.push('  Object.defineProperty(window, "localStorage", {');
    lines.push('    value: {');
    lines.push(
      `      getItem: ${mockFn()}.mockImplementation((key: string) => mockStorage[key] ?? null),`
    );
    lines.push(
      `      setItem: ${mockFn()}.mockImplementation((key: string, val: string) => { mockStorage[key] = val; }),`
    );
    lines.push(
      `      removeItem: ${mockFn()}.mockImplementation((key: string) => { delete mockStorage[key]; }),`
    );
    lines.push(
      `      clear: ${mockFn()}.mockImplementation(() => { Object.keys(mockStorage).forEach(k => delete mockStorage[k]); }),`
    );
    lines.push('      length: 0,');
    lines.push(`      key: ${mockFn()}.mockReturnValue(null),`);
    lines.push('    },');
    lines.push('    writable: true,');
    lines.push('  });');
    lines.push('});');
  }

  // Build imports - group by parentObjectName
  const objectExports = new Set<string>();
  const directExports: ExportedFunction[] = [];
  const defaultExport = functions.find((f) => f.name === 'default');

  for (const func of functions) {
    if (func.name === 'default') continue;
    if (func.parentObjectName) {
      objectExports.add(func.parentObjectName);
    } else {
      directExports.push(func);
    }
  }

  const importNames = [...directExports.map((f) => f.name), ...Array.from(objectExports)];

  if (importNames.length > 0) {
    lines.push(`import { ${importNames.join(', ')} } from "${importPath}";`);
  }
  if (defaultExport) {
    lines.push(`import defaultExport from "${importPath}";`);
  }

  lines.push('');

  // Check if any function is a React hook
  const hasHooks = functions.some((f) => /^use[A-Z]/.test(f.name));
  const needsQueryClient =
    sourceText.includes('useQuery') ||
    sourceText.includes('useMutation') ||
    sourceText.includes('@tanstack/react-query');
  // Detect if hooks use context providers that require wrapping with renderWithProviders
  // Uses CONTEXT_DETECTION_CONFIG.customContexts so no hardcoded names are needed here
  const needsProviderWrapper = CONTEXT_DETECTION_CONFIG.customContexts.some((ctx) =>
    ctx.hooks.some((h) => sourceText.includes(h))
  );
  // Check if a custom render helper (renderWithProviders) exists in the project
  const renderHelper = resolveRenderHelper(sourceFilePath);
  const useRenderWithProviders = hasHooks && needsProviderWrapper && renderHelper !== null;

  // For hooks needing providers, needsQueryClient wrapper is always true
  const effectiveNeedsQueryClient = needsQueryClient || useRenderWithProviders;

  if (hasHooks) {
    lines.push('import { renderHook, act } from "@testing-library/react";');
    if (useRenderWithProviders) {
      lines.push('import { QueryClient, QueryClientProvider } from "@tanstack/react-query";');
      lines.push('import React from "react";');
      // Import the context providers this hook depends on
      const providerImports = detectHookProviderImports(sourceFile, sourceText, testFilePath);
      for (const pi of providerImports) {
        lines.push(pi);
      }
      lines.push('');
      lines.push('const createTestQueryClient = () => new QueryClient({');
      lines.push(
        '  defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },'
      );
      lines.push('});');
      lines.push('');
      lines.push('function createWrapper() {');
      lines.push('  const queryClient = createTestQueryClient();');
      lines.push('  return ({ children }: { children: React.ReactNode }) => {');
      // Build nested providers using React.createElement (outermost first)
      const providerNames = detectRequiredProviders(sourceText);
      let wrapperExpr = 'children';
      // Wrap innermost to outermost (reverse so outermost is applied last)
      for (const prov of [...providerNames].reverse()) {
        wrapperExpr = `React.createElement(${prov}, null, ${wrapperExpr})`;
      }
      wrapperExpr = `React.createElement(QueryClientProvider, { client: queryClient }, ${wrapperExpr})`;
      lines.push(`    return ${wrapperExpr};`);
      lines.push('  };');
      lines.push('}');
    } else if (needsQueryClient) {
      lines.push('import { QueryClient, QueryClientProvider } from "@tanstack/react-query";');
      lines.push('import React from "react";');
      lines.push('');
      lines.push('const createTestQueryClient = () => new QueryClient({');
      lines.push(
        '  defaultOptions: { queries: { retry: false, gcTime: 0 }, mutations: { retry: false } },'
      );
      lines.push('});');
      lines.push('');
      lines.push('function createWrapper() {');
      lines.push('  const queryClient = createTestQueryClient();');
      lines.push('  return ({ children }: { children: React.ReactNode }) =>');
      lines.push(
        '    React.createElement(QueryClientProvider, { client: queryClient }, children);'
      );
      lines.push('}');
    }
    lines.push('');
  }

  // Generate tests grouped by parentObjectName
  const grouped = groupByParent(functions.filter((f) => f.name !== 'default'));

  for (const [parentName, funcs] of grouped) {
    if (parentName) {
      // Object-exported methods: describe("authService", () => { ... })
      lines.push(`describe("${parentName}", () => {`);
      for (const func of funcs) {
        if (/^use[A-Z]/.test(func.name)) {
          generateHookTests(lines, func, sourceFile, '  ', effectiveNeedsQueryClient);
        } else {
          generateObjectMethodTests(lines, func, sourceFile, '  ');
        }
      }
      lines.push('});');
      lines.push('');
    } else {
      // Direct exports
      for (const func of funcs) {
        if (/^use[A-Z]/.test(func.name)) {
          generateHookTests(lines, func, sourceFile, '', effectiveNeedsQueryClient);
        } else {
          generateFunctionTests(lines, func, sourceFile, '');
        }
      }
    }
  }

  if (lines.length <= 3) return null;
  lines.push('');
  return lines.join('\n');
}

/**
 * Group functions by their parentObjectName
 */
function groupByParent(functions: ExportedFunction[]): Map<string | undefined, ExportedFunction[]> {
  const map = new Map<string | undefined, ExportedFunction[]>();
  for (const func of functions) {
    const key = func.parentObjectName;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(func);
  }
  return map;
}

/**
 * Tests for methods on an exported object (e.g., authService.login)
 */
function generateObjectMethodTests(
  lines: string[],
  func: ExportedFunction,
  sourceFile: SourceFile,
  indent: string
): void {
  const parent = func.parentObjectName!;
  const callExpr = `${parent}.${func.name}`;

  lines.push(`${indent}describe("${func.name}", () => {`);

  // Test 1: Method exists and is callable
  lines.push(`${indent}  it("is defined", () => {`);
  lines.push(`${indent}    expect(${callExpr}).toBeDefined();`);
  lines.push(`${indent}    expect(typeof ${callExpr}).toBe("function");`);
  lines.push(`${indent}  });`);
  lines.push('');

  // Test 2: Call with typical args
  const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
  const isVoid = func.returnType === 'void' || func.returnType === 'Promise<void>';

  if (func.isAsync) {
    lines.push(`${indent}  it("resolves without throwing", async () => {`);
    lines.push(`${indent}    try {`);
    if (isVoid) {
      lines.push(`${indent}      await ${callExpr}(${mockArgs});`);
    } else {
      lines.push(`${indent}      const result = await ${callExpr}(${mockArgs});`);
      lines.push(`${indent}      expect(result).toBeDefined();`);
    }
    lines.push(`${indent}    } catch (error) {`);
    lines.push(`${indent}      expect(error).toBeDefined();`);
    lines.push(`${indent}    }`);
    lines.push(`${indent}  });`);
  } else {
    lines.push(`${indent}  it("returns without throwing", () => {`);
    if (isVoid) {
      lines.push(`${indent}    expect(() => ${callExpr}(${mockArgs})).not.toThrow();`);
    } else {
      lines.push(`${indent}    const result = ${callExpr}(${mockArgs});`);
      lines.push(`${indent}    expect(result).toBeDefined();`);
    }
    lines.push(`${indent}  });`);
  }
  lines.push('');

  // Test 3: Minimal args if there are optional params
  const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
  if (requiredParams.length < func.params.length) {
    const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
    if (func.isAsync) {
      lines.push(`${indent}  it("works with minimal arguments", async () => {`);
      lines.push(`${indent}    try {`);
      if (isVoid) {
        lines.push(`${indent}      await ${callExpr}(${minArgs});`);
      } else {
        lines.push(`${indent}      const result = await ${callExpr}(${minArgs});`);
        lines.push(`${indent}      expect(result).toBeDefined();`);
      }
      lines.push(`${indent}    } catch (error) {`);
      lines.push(`${indent}      expect(error).toBeDefined();`);
      lines.push(`${indent}    }`);
      lines.push(`${indent}  });`);
    } else {
      lines.push(`${indent}  it("works with minimal arguments", () => {`);
      if (isVoid) {
        lines.push(`${indent}    expect(() => ${callExpr}(${minArgs})).not.toThrow();`);
      } else {
        lines.push(`${indent}    const result = ${callExpr}(${minArgs});`);
        lines.push(`${indent}    expect(result).toBeDefined();`);
      }
      lines.push(`${indent}  });`);
    }
    lines.push('');
  }

  // Test 4: Error path for async methods
  if (func.isAsync) {
    lines.push(`${indent}  it("handles errors gracefully", async () => {`);
    lines.push(`${indent}    try {`);
    lines.push(`${indent}      await ${callExpr}(${mockArgs});`);
    lines.push(`${indent}    } catch (error) {`);
    lines.push(`${indent}      expect(error).toBeDefined();`);
    lines.push(`${indent}    }`);
    lines.push(`${indent}  });`);
    lines.push('');
  }

  // Test 5: Edge cases (wrapped in try-catch to handle expected errors like invalid inputs)
  for (const param of func.params.slice(0, 3)) {
    const edgeCases = getEdgeCases(param);
    for (const edgeCase of edgeCases) {
      const argsWithEdge = func.params
        .map((p) => (p.name === param.name ? edgeCase.value : mockValueForParam(p)))
        .join(', ');

      if (func.isAsync) {
        lines.push(`${indent}  it("handles ${edgeCase.label} for ${param.name}", async () => {`);
        lines.push(`${indent}    try {`);
        if (isVoid) {
          lines.push(`${indent}      await ${callExpr}(${argsWithEdge});`);
        } else {
          lines.push(`${indent}      const result = await ${callExpr}(${argsWithEdge});`);
          lines.push(`${indent}      expect(result).toBeDefined();`);
        }
        lines.push(`${indent}    } catch (error) {`);
        lines.push(`${indent}      expect(error).toBeDefined();`);
        lines.push(`${indent}    }`);
        lines.push(`${indent}  });`);
      } else {
        lines.push(`${indent}  it("handles ${edgeCase.label} for ${param.name}", () => {`);
        lines.push(`${indent}    try {`);
        if (isVoid) {
          lines.push(`${indent}      ${callExpr}(${argsWithEdge});`);
        } else {
          lines.push(`${indent}      const result = ${callExpr}(${argsWithEdge});`);
          lines.push(`${indent}      expect(result).toBeDefined();`);
        }
        lines.push(`${indent}    } catch (error) {`);
        lines.push(`${indent}      expect(error).toBeDefined();`);
        lines.push(`${indent}    }`);
        lines.push(`${indent}  });`);
      }
      lines.push('');
    }
  }

  lines.push(`${indent}});`);
  lines.push('');
}

function generateFunctionTests(
  lines: string[],
  func: ExportedFunction,
  sourceFile: SourceFile,
  indent: string
): void {
  lines.push(`${indent}describe("${func.name}", () => {`);

  // Test 1: Function exists and is callable
  lines.push(`${indent}  it("is defined", () => {`);
  lines.push(`${indent}    expect(${func.name}).toBeDefined();`);
  lines.push(`${indent}    expect(typeof ${func.name}).toBe("function");`);
  lines.push(`${indent}  });`);
  lines.push('');

  // Test 2: Call with typical args
  const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
  const isVoid = func.returnType === 'void' || func.returnType === 'Promise<void>';

  if (func.isAsync) {
    lines.push(`${indent}  it("resolves without throwing", async () => {`);
    lines.push(`${indent}    try {`);
    if (isVoid) {
      lines.push(`${indent}      await ${func.name}(${mockArgs});`);
    } else {
      lines.push(`${indent}      const result = await ${func.name}(${mockArgs});`);
      lines.push(`${indent}      expect(result).toBeDefined();`);
    }
    lines.push(`${indent}    } catch (error) {`);
    lines.push(`${indent}      expect(error).toBeDefined();`);
    lines.push(`${indent}    }`);
    lines.push(`${indent}  });`);
  } else {
    lines.push(`${indent}  it("returns without throwing", () => {`);
    if (isVoid) {
      lines.push(`${indent}    expect(() => ${func.name}(${mockArgs})).not.toThrow();`);
    } else {
      lines.push(`${indent}    const result = ${func.name}(${mockArgs});`);
      lines.push(`${indent}    expect(result).toBeDefined();`);
    }
    lines.push(`${indent}  });`);
  }
  lines.push('');

  // Test 3: For functions with optional params, call with minimal args
  const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
  if (requiredParams.length < func.params.length) {
    const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
    if (func.isAsync) {
      lines.push(`${indent}  it("works with minimal arguments", async () => {`);
      lines.push(`${indent}    try {`);
      if (isVoid) {
        lines.push(`${indent}      await ${func.name}(${minArgs});`);
      } else {
        lines.push(`${indent}      const result = await ${func.name}(${minArgs});`);
        lines.push(`${indent}      expect(result).toBeDefined();`);
      }
      lines.push(`${indent}    } catch (error) {`);
      lines.push(`${indent}      expect(error).toBeDefined();`);
      lines.push(`${indent}    }`);
      lines.push(`${indent}  });`);
    } else {
      lines.push(`${indent}  it("works with minimal arguments", () => {`);
      if (isVoid) {
        lines.push(`${indent}    expect(() => ${func.name}(${minArgs})).not.toThrow();`);
      } else {
        lines.push(`${indent}    const result = ${func.name}(${minArgs});`);
        lines.push(`${indent}    expect(result).toBeDefined();`);
      }
      lines.push(`${indent}  });`);
    }
    lines.push('');
  }

  // Test 4: Edge cases for specific param types
  // Edge cases can throw (e.g., invalid currency code, negative decimals for toFixed),
  // so wrap in try-catch to ensure the test doesn't fail unexpectedly
  for (const param of func.params.slice(0, 3)) {
    const edgeCases = getEdgeCases(param);
    for (const edgeCase of edgeCases) {
      const argsWithEdge = func.params
        .map((p) => (p.name === param.name ? edgeCase.value : mockValueForParam(p)))
        .join(', ');

      if (func.isAsync) {
        lines.push(`${indent}  it("handles ${edgeCase.label} for ${param.name}", async () => {`);
        lines.push(`${indent}    try {`);
        if (isVoid) {
          lines.push(`${indent}      await ${func.name}(${argsWithEdge});`);
        } else {
          lines.push(`${indent}      const result = await ${func.name}(${argsWithEdge});`);
          lines.push(`${indent}      expect(result).toBeDefined();`);
        }
        lines.push(`${indent}    } catch (error) {`);
        lines.push(`${indent}      expect(error).toBeDefined();`);
        lines.push(`${indent}    }`);
        lines.push(`${indent}  });`);
      } else {
        lines.push(`${indent}  it("handles ${edgeCase.label} for ${param.name}", () => {`);
        lines.push(`${indent}    try {`);
        if (isVoid) {
          lines.push(`${indent}      ${func.name}(${argsWithEdge});`);
        } else {
          lines.push(`${indent}      const result = ${func.name}(${argsWithEdge});`);
          lines.push(`${indent}      expect(result).toBeDefined();`);
        }
        lines.push(`${indent}    } catch (error) {`);
        lines.push(`${indent}      expect(error).toBeDefined();`);
        lines.push(`${indent}    }`);
        lines.push(`${indent}  });`);
      }
      lines.push('');
    }
  }

  // Test 5: Switch/case branch coverage
  const switchCases = detectSwitchCases(func, sourceFile);
  for (const switchCase of switchCases) {
    for (const caseValue of switchCase.values) {
      const argsWithCase = func.params
        .map((p) => (p.name === switchCase.paramName ? caseValue : mockValueForParam(p)))
        .join(', ');

      lines.push(`${indent}  it("handles case ${caseValue} for ${switchCase.paramName}", () => {`);
      lines.push(`${indent}    const result = ${func.name}(${argsWithCase});`);
      lines.push(`${indent}    expect(result).toBeDefined();`);
      lines.push(`${indent}  });`);
      lines.push('');
    }
  }

  // Test 6: For functions that return functions (debounce, throttle patterns)
  if (func.returnType.includes('=>') || func.returnType.includes('Function')) {
    lines.push(`${indent}  it("returns a callable function", () => {`);
    lines.push(`${indent}    const result = ${func.name}(${mockArgs});`);
    lines.push(`${indent}    expect(typeof result).toBe("function");`);
    lines.push(`${indent}    result();`);
    lines.push(`${indent}  });`);
    lines.push('');
  }

  lines.push(`${indent}});`);
  lines.push('');
}

function generateHookTests(
  lines: string[],
  func: ExportedFunction,
  sourceFile: SourceFile,
  indent: string,
  needsQueryClient = false
): void {
  lines.push(`${indent}describe("${func.name}", () => {`);

  const mockArgs = func.params.map((p) => mockValueForParam(p)).join(', ');
  const argsString = mockArgs ? `() => ${func.name}(${mockArgs})` : `() => ${func.name}()`;
  const wrapperOpt = needsQueryClient ? ', { wrapper: createWrapper() }' : '';

  lines.push(`${indent}  it("initializes without error", () => {`);
  lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
  lines.push(`${indent}    expect(result.current).toBeDefined();`);
  lines.push(`${indent}  });`);
  lines.push('');

  // Test with minimal args if there are optional params
  const requiredParams = func.params.filter((p) => !p.isOptional && !p.hasDefault);
  if (requiredParams.length < func.params.length) {
    const minArgs = requiredParams.map((p) => mockValueForParam(p)).join(', ');
    const minArgsString = minArgs ? `() => ${func.name}(${minArgs})` : `() => ${func.name}()`;
    lines.push(`${indent}  it("works with minimal arguments", () => {`);
    lines.push(`${indent}    const { result } = renderHook(${minArgsString}${wrapperOpt});`);
    lines.push(`${indent}    expect(result.current).toBeDefined();`);
    lines.push(`${indent}  });`);
    lines.push('');
  }

  // Detect return shape and generate targeted tests
  const returnShape = detectHookReturnShape(func, sourceFile);

  if (returnShape.type === 'tuple') {
    // Array/tuple return like [value, setValue, removeValue]
    lines.push(`${indent}  it("returns expected tuple structure", () => {`);
    lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
    lines.push(`${indent}    expect(Array.isArray(result.current)).toBe(true);`);
    if (returnShape.length) {
      lines.push(`${indent}    expect(result.current).toHaveLength(${returnShape.length});`);
    }
    lines.push(`${indent}  });`);
    lines.push('');

    // Test each function in the tuple
    for (const idx of returnShape.functionIndices) {
      lines.push(`${indent}  it("provides callable function at index ${idx}", () => {`);
      lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.push(`${indent}    expect(typeof result.current[${idx}]).toBe("function");`);
      lines.push(`${indent}  });`);
      lines.push('');

      lines.push(`${indent}  it("can call function at index ${idx} with act", () => {`);
      lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.push(`${indent}    act(() => {`);
      lines.push(`${indent}      result.current[${idx}]("test-value");`);
      lines.push(`${indent}    });`);
      lines.push(`${indent}    expect(result.current).toBeDefined();`);
      lines.push(`${indent}  });`);
      lines.push('');
    }
  } else if (returnShape.type === 'object') {
    // Object return like { data, isLoading, error, fetchData }
    for (const method of returnShape.methods) {
      lines.push(`${indent}  it("provides ${method} function", () => {`);
      lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.push(`${indent}    expect(typeof result.current.${method}).toBe("function");`);
      lines.push(`${indent}  });`);
      lines.push('');

      if (isSafeHookMethodToInvoke(method)) {
        lines.push(`${indent}  it("can call ${method} with act", () => {`);
        lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
        lines.push(`${indent}    act(() => {`);
        lines.push(`${indent}      result.current.${method}();`);
        lines.push(`${indent}    });`);
        lines.push(`${indent}    expect(result.current).toBeDefined();`);
        lines.push(`${indent}  });`);
        lines.push('');
      }
    }

    for (const state of returnShape.stateProps) {
      lines.push(`${indent}  it("provides ${state} state", () => {`);
      lines.push(`${indent}    const { result } = renderHook(${argsString}${wrapperOpt});`);
      lines.push(`${indent}    expect(result.current).toHaveProperty("${state}");`);
      lines.push(`${indent}  });`);
      lines.push('');
    }
  }

  // Rerender test if hook has params
  if (func.params.length > 0) {
    const rerenderArgs = func.params.map((p) => mockValueForParam(p, true)).join(', ');
    const rerenderWrapperOpt = needsQueryClient ? ', wrapper: createWrapper()' : '';
    lines.push(`${indent}  it("handles rerender with new arguments", () => {`);
    lines.push(`${indent}    const { result, rerender } = renderHook(`);
    lines.push(
      `${indent}      (props) => ${func.name}(${func.params.map((_, i) => `props.p${i}`).join(', ')}),`
    );
    lines.push(
      `${indent}      { initialProps: { ${func.params.map((p, i) => `p${i}: ${mockValueForParam(p)}`).join(', ')} }${rerenderWrapperOpt} }`
    );
    lines.push(`${indent}    );`);
    lines.push(
      `${indent}    rerender({ ${func.params.map((p, i) => `p${i}: ${rerenderArgs.split(', ')[i] || mockValueForParam(p, true)}`).join(', ')} });`
    );
    lines.push(`${indent}    expect(result.current).toBeDefined();`);
    lines.push(`${indent}  });`);
    lines.push('');
  }

  lines.push(`${indent}});`);
  lines.push('');
}

// --- Analysis helpers ---

interface HookReturnShape {
  type: 'tuple' | 'object' | 'unknown';
  length?: number;
  functionIndices: number[];
  methods: string[];
  stateProps: string[];
}

function detectHookReturnShape(func: ExportedFunction, sourceFile: SourceFile): HookReturnShape {
  const shape: HookReturnShape = {
    type: 'unknown',
    functionIndices: [],
    methods: [],
    stateProps: [],
  };

  const funcNode = findFunctionByName(sourceFile, func.name);
  if (!funcNode) return shape;

  // Only look at DIRECT return statements in the function body, not nested ones
  // (e.g., returns inside .map(), .filter(), arrow callbacks, etc.)
  const returnStatements = funcNode
    .getDescendantsOfKind(SyntaxKind.ReturnStatement)
    .filter((ret) => {
      // Walk up the parent chain to ensure this return is directly in the hook function
      let parent: Node | undefined = ret.getParent();
      while (parent && parent !== funcNode) {
        // If we hit another function boundary (arrow function, function expression, method),
        // this return belongs to a nested function, not the hook itself
        if (
          Node.isArrowFunction(parent) ||
          Node.isFunctionExpression(parent) ||
          Node.isMethodDeclaration(parent) ||
          Node.isFunctionDeclaration(parent)
        ) {
          return false;
        }
        parent = parent.getParent();
      }
      return parent === funcNode;
    });

  for (const ret of returnStatements) {
    const expr = ret.getExpression();
    if (!expr) continue;

    // Array/tuple return: return [value, setValue, removeValue]
    if (Node.isArrayLiteralExpression(expr)) {
      shape.type = 'tuple';
      const elements = expr.getElements();
      shape.length = elements.length;
      elements.forEach((el, idx) => {
        const text = el.getText();
        // Functions are typically setters (set*), callbacks, or identifiers from useState
        if (
          /^set[A-Z]/.test(text) ||
          /^(handle|toggle|remove|clear|reset|add|update|delete|fetch|load|save|dispatch)/.test(
            text
          )
        ) {
          shape.functionIndices.push(idx);
        }
        // If element is an identifier that matches a destructured useState setter
        if (Node.isIdentifier(el)) {
          // Check if there's a corresponding useState call for this identifier
          const name = el.getText();
          if (
            /^set[A-Z]/.test(name) ||
            /^remove/.test(name) ||
            /^toggle/.test(name) ||
            /^clear/.test(name)
          ) {
            if (!shape.functionIndices.includes(idx)) {
              shape.functionIndices.push(idx);
            }
          }
        }
      });
      return shape;
    }

    // Object return: return { data, isLoading, fetchData, ... }
    if (Node.isObjectLiteralExpression(expr)) {
      shape.type = 'object';
      for (const prop of expr.getProperties()) {
        if (Node.isShorthandPropertyAssignment(prop) || Node.isPropertyAssignment(prop)) {
          const name = prop.getName();
          // Classify as method or state using CONTEXT_DETECTION_CONFIG patterns
          const methodPrefix = CONTEXT_DETECTION_CONFIG.methodPatterns.join('|');
          const statePrefix = CONTEXT_DETECTION_CONFIG.statePatterns.join('|');
          if (new RegExp(`^(${methodPrefix}|mutate|invalidate|refetch|bulk)`).test(name)) {
            shape.methods.push(name);
          } else if (
            new RegExp(
              `^(${statePrefix}|expenses|categories|budgets|notifications|pagination|filters|sort)`
            ).test(name)
          ) {
            shape.stateProps.push(name);
          }
        }
        if (Node.isMethodDeclaration(prop)) {
          shape.methods.push(prop.getName());
        }
      }
      return shape;
    }
  }

  return shape;
}

function isSafeHookMethodToInvoke(methodName: string): boolean {
  return /^(set|toggle|reset|clear|open|close|show|hide|select|deselect)/i.test(methodName);
}

function detectSwitchCases(func: ExportedFunction, sourceFile: SourceFile): SwitchCaseInfo[] {
  const results: SwitchCaseInfo[] = [];

  const funcNode = findFunctionByName(sourceFile, func.name);
  if (!funcNode) return results;

  const switchStatements = funcNode.getDescendantsOfKind(SyntaxKind.SwitchStatement);
  for (const switchStmt of switchStatements) {
    const switchExpr = switchStmt.getExpression().getText();

    // Try to match switch expression to a param name
    const matchedParam = func.params.find(
      (p) =>
        switchExpr === p.name || switchExpr.endsWith(`.${p.name}`) || switchExpr.includes(p.name)
    );

    if (!matchedParam) continue;

    const values: string[] = [];
    for (const clause of switchStmt.getClauses()) {
      if (Node.isCaseClause(clause)) {
        const exprText = clause.getExpression().getText();
        // Only include string/number literals
        if (/^['"]/.test(exprText) || /^\d+$/.test(exprText)) {
          values.push(exprText);
        }
      }
    }

    if (values.length > 0) {
      results.push({ paramName: matchedParam.name, values });
    }
  }

  return results;
}

function findFunctionByName(sourceFile: SourceFile, name: string): Node | null {
  // Check function declarations
  for (const func of sourceFile.getFunctions()) {
    if (func.getName() === name) return func;
  }

  // Check variable declarations (arrow functions)
  for (const variable of sourceFile.getVariableDeclarations()) {
    if (variable.getName() === name) {
      const init = variable.getInitializer();
      if (init && (Node.isArrowFunction(init) || Node.isFunctionExpression(init))) {
        return init;
      }
    }
  }

  return null;
}

function getExportedFunctions(sourceFile: SourceFile, checker: TypeChecker): ExportedFunction[] {
  const functions: ExportedFunction[] = [];

  // 1. Exported function declarations
  for (const func of sourceFile.getFunctions()) {
    if (!func.isExported()) continue;
    const name = func.getName();
    if (!name) continue;

    functions.push({
      name,
      params: extractParams(func.getParameters(), checker),
      returnType: func.getReturnType().getText(),
      isAsync: func.isAsync(),
      hasBody: func.getBody() !== undefined,
      sourceNode: func,
    });
  }

  // 2. Exported variable declarations (arrow functions, const functions)
  for (const stmt of sourceFile.getVariableStatements()) {
    if (!stmt.isExported()) continue;
    for (const decl of stmt.getDeclarations()) {
      const init = decl.getInitializer();
      if (!init) continue;

      if (Node.isArrowFunction(init) || Node.isFunctionExpression(init)) {
        functions.push({
          name: decl.getName(),
          params: extractParams(init.getParameters(), checker),
          returnType: init.getReturnType().getText(),
          isAsync: init.isAsync(),
          hasBody: true,
          sourceNode: init,
        });
      }

      // 3. Object-exported methods: export const myService = { async login() {...}, ... }
      if (Node.isObjectLiteralExpression(init)) {
        const parentName = decl.getName();
        for (const prop of init.getProperties()) {
          // Method declarations: { async login() { ... } }
          if (Node.isMethodDeclaration(prop)) {
            const methodName = prop.getName();
            functions.push({
              name: methodName,
              params: extractParams(prop.getParameters(), checker),
              returnType: prop.getReturnType().getText(),
              isAsync: prop.isAsync(),
              hasBody: prop.getBody() !== undefined,
              parentObjectName: parentName,
              sourceNode: prop,
            });
          }

          // Property assignments with function values: { login: async () => { ... } }
          if (Node.isPropertyAssignment(prop)) {
            const value = prop.getInitializer();
            if (value && (Node.isArrowFunction(value) || Node.isFunctionExpression(value))) {
              functions.push({
                name: prop.getName(),
                params: extractParams(value.getParameters(), checker),
                returnType: value.getReturnType().getText(),
                isAsync: value.isAsync(),
                hasBody: true,
                parentObjectName: parentName,
                sourceNode: value,
              });
            }
          }

          // Shorthand property assignment: { login } where login is defined elsewhere
          if (Node.isShorthandPropertyAssignment(prop)) {
            const propName = prop.getName();
            // Try to find the function definition in the same file
            const resolvedFunc = findFunctionByName(sourceFile, propName);
            if (resolvedFunc) {
              const params = resolvedFunc.getDescendantsOfKind(SyntaxKind.Parameter);
              functions.push({
                name: propName,
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                params: extractParams(params as any, checker),
                returnType: 'unknown',
                isAsync: resolvedFunc.getText().includes('async'),
                hasBody: true,
                parentObjectName: parentName,
                sourceNode: resolvedFunc,
              });
            }
          }
        }
      }
    }
  }

  return functions;
}

function extractParams(
  params: ReturnType<FunctionDeclaration['getParameters']>,
  checker: TypeChecker
): ParamInfo[] {
  return params.map((param) => {
    let typeText = 'unknown';
    try {
      const type = checker.getTypeAtLocation(param);
      typeText = type.getText();
    } catch {
      // Type resolution may fail for complex generics
    }
    return {
      name: param.getName(),
      type: typeText,
      isOptional: param.isOptional(),
      hasDefault: param.hasInitializer(),
    };
  });
}

function mockValueForParam(param: ParamInfo, alternate = false): string {
  const type = param.type.toLowerCase();
  const name = param.name.toLowerCase();

  // Common hook options bag pattern; disable fetches by default in tests when possible.
  if (/^options?$/.test(name)) return '{ enabled: false }';

  if (type.includes('=>') || type.includes('function')) return mockFn();
  // Name-based function detection for generic types that don't resolve to arrow syntax
  if (
    /^(fn|func|callback|handler|listener|predicate|comparator|reducer|mapper|transformer)$/i.test(
      name
    )
  )
    return mockFn();
  if (type === 'string') return contextualMock(name, 'string', alternate);
  if (type === 'number') return contextualMock(name, 'number', alternate);
  if (type === 'boolean') return alternate ? 'false' : 'true';
  if (type.includes('[]')) return alternate ? '[{ id: "1" }]' : '[]';
  if (type === 'date' || type === 'Date')
    return alternate ? 'new Date("2025-06-15")' : 'new Date("2024-01-01")';
  // Check for object/record BEFORE null/undefined since union types like Record<string, X | undefined> contain 'undefined'
  if (type.includes('{') || type.includes('record')) return '{}';
  if (type.includes('null')) return 'null';
  if (type.includes('undefined')) return 'undefined';
  if (type === 'object') return '{}';

  // Name-based fallbacks
  if (/id$/i.test(name)) return alternate ? '"test-id-2"' : '"test-id"';
  if (/name$/i.test(name)) return alternate ? '"Other"' : '"Test"';
  if (/email/i.test(name)) return alternate ? '"other@example.com"' : '"test@example.com"';
  if (/url/i.test(name) || /path/i.test(name)) return alternate ? '"/other"' : '"/test"';
  if (/amount/i.test(name) || /price/i.test(name) || /value/i.test(name))
    return alternate ? '200' : '100';
  if (/count/i.test(name) || /index/i.test(name)) return alternate ? '1' : '0';

  return '{}';
}

function contextualMock(name: string, type: string, alternate = false): string {
  if (type === 'string') {
    if (/date/i.test(name)) return alternate ? '"2025-06-15"' : '"2024-01-01"';
    if (/email/i.test(name)) return alternate ? '"other@example.com"' : '"test@example.com"';
    if (/url/i.test(name)) return alternate ? '"https://other.com"' : '"https://example.com"';
    if (/key/i.test(name)) return alternate ? '"other-key"' : '"test-key"';
    if (/format/i.test(name)) return alternate ? '"custom"' : '"default"';
    if (/type/i.test(name) || /kind/i.test(name) || /status/i.test(name) || /mode/i.test(name))
      return alternate ? '"secondary"' : '"primary"';
    if (/query/i.test(name) || /search/i.test(name) || /filter/i.test(name))
      return alternate ? '"other"' : '"test"';
    if (/token/i.test(name)) return alternate ? '"other-token"' : '"test-token"';
    if (/password/i.test(name)) return alternate ? '"other-pass"' : '"test-pass"';
    if (/currency/i.test(name)) return alternate ? '"EUR"' : '"USD"';
    return alternate ? '"other-value"' : '"test-value"';
  }
  if (type === 'number') {
    if (/amount/i.test(name) || /price/i.test(name)) return alternate ? '200' : '100';
    if (/page/i.test(name)) return alternate ? '2' : '1';
    if (/limit/i.test(name) || /size/i.test(name)) return alternate ? '20' : '10';
    if (/year/i.test(name)) return alternate ? '2025' : '2024';
    return alternate ? '2' : '1';
  }
  return '{}';
}

interface EdgeCase {
  label: string;
  value: string;
}

/**
 * Detect provider imports needed for hook tests.
 * When a hook uses useNotification, useAuth, etc., we need to import the corresponding providers.
 */
function detectHookProviderImports(
  sourceFile: SourceFile,
  sourceText: string,
  testFilePath: string
): string[] {
  const imports: string[] = [];
  const imported = new Set<string>();

  // Build context map from CONTEXT_DETECTION_CONFIG.customContexts — no hardcoded names
  const contextMap = CONTEXT_DETECTION_CONFIG.customContexts.flatMap((ctx) =>
    ctx.hooks.map((hook) => ({
      pattern: hook,
      providerName: ctx.providerName,
      contextFile: ctx.contextName,
    }))
  );

  for (const ctx of contextMap) {
    if (sourceText.includes(ctx.pattern) && !imported.has(ctx.providerName)) {
      // Find the actual import path from the source file
      for (const imp of sourceFile.getImportDeclarations()) {
        const moduleSpec = imp.getModuleSpecifierValue();
        for (const named of imp.getNamedImports()) {
          if (named.getName() === ctx.pattern || named.getName() === ctx.providerName) {
            const sourceDir = path.dirname(sourceFile.getFilePath());
            const testDir = path.dirname(testFilePath);

            // Handle path aliases like @/contexts, ~/contexts
            if (moduleSpec.startsWith('@/') || moduleSpec.startsWith('~/')) {
              // @/ typically maps to src/ — find the src root
              const aliasPath = moduleSpec.replace(/^[@~]\//, '');
              // Walk up from sourceDir to find the src root
              let srcRoot = sourceDir;
              while (
                srcRoot &&
                !fs.existsSync(path.join(srcRoot, aliasPath + '.ts')) &&
                !fs.existsSync(path.join(srcRoot, aliasPath + '.tsx')) &&
                !fs.existsSync(path.join(srcRoot, aliasPath, 'index.ts')) &&
                !fs.existsSync(path.join(srcRoot, aliasPath, 'index.tsx'))
              ) {
                const parent = path.dirname(srcRoot);
                if (parent === srcRoot) break;
                srcRoot = parent;
              }
              const resolvedPath = path.resolve(srcRoot, aliasPath);
              let relativePath = path.relative(testDir, resolvedPath).replace(/\\/g, '/');
              if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
              relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
              imports.push(`import { ${ctx.providerName} } from "${relativePath}";`);
              imported.add(ctx.providerName);
              break;
            }

            // Regular relative import
            const resolvedPath = path.resolve(sourceDir, moduleSpec);
            let relativePath = path.relative(testDir, resolvedPath).replace(/\\/g, '/');
            if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
            relativePath = relativePath.replace(/\.(tsx?|jsx?)$/, '');
            imports.push(`import { ${ctx.providerName} } from "${relativePath}";`);
            imported.add(ctx.providerName);
            break;
          }
        }
        if (imported.has(ctx.providerName)) break;
      }

      // Fallback: try to construct the import path from convention
      if (!imported.has(ctx.providerName)) {
        // Try common patterns: ../contexts/NotificationContext
        const testDir = path.dirname(testFilePath);
        const possiblePaths = [
          `../contexts/${ctx.contextFile}`,
          `../../contexts/${ctx.contextFile}`,
          `../context/${ctx.contextFile}`,
        ];
        for (const pp of possiblePaths) {
          const absPath = path.resolve(testDir, pp);
          const extensions = ['.tsx', '.ts', '.jsx', '.js'];
          for (const ext of extensions) {
            try {
              if (fs.existsSync(absPath + ext)) {
                imports.push(`import { ${ctx.providerName} } from "${pp}";`);
                imported.add(ctx.providerName);
                break;
              }
            } catch {
              /* ignore */
            }
          }
          if (imported.has(ctx.providerName)) break;
        }
      }
    }
  }

  return imports;
}

/**
 * Detect which providers a hook needs by analyzing its source text.
 */
/**
 * Detect if the source file imports from a local api module (e.g., './api', '../services/api')
 * Returns the import path as-is so we can mock it.
 */
function detectApiImportPath(sourceFile: SourceFile, testFilePath?: string): string | null {
  for (const imp of sourceFile.getImportDeclarations()) {
    const moduleSpec = imp.getModuleSpecifierValue();
    // Match local imports that look like api modules
    if (moduleSpec.startsWith('.') && /\bapi\b/i.test(moduleSpec)) {
      // If we have a testFilePath, resolve the module path relative to the test file location
      if (testFilePath) {
        const sourceDir = path.dirname(sourceFile.getFilePath());
        const resolvedModule = path.resolve(sourceDir, moduleSpec);
        const testDir = path.dirname(testFilePath);
        let relativePath = path.relative(testDir, resolvedModule).replace(/\\/g, '/');
        if (!relativePath.startsWith('.')) relativePath = './' + relativePath;
        return relativePath;
      }
      return moduleSpec;
    }
  }
  return null;
}

function detectRequiredProviders(sourceText: string): string[] {
  // Driven by CONTEXT_DETECTION_CONFIG.customContexts — no hardcoded names
  // Order matters: outermost providers first (as listed in config)
  const providers: string[] = [];
  for (const ctx of CONTEXT_DETECTION_CONFIG.customContexts) {
    if (ctx.hooks.some((h) => sourceText.includes(h))) {
      providers.push(ctx.providerName);
    }
  }
  return providers;
}

function getEdgeCases(param: ParamInfo): EdgeCase[] {
  const type = param.type.toLowerCase();
  const cases: EdgeCase[] = [];

  if (type === 'string' || type.includes('string')) {
    cases.push({ label: 'empty string', value: '""' });
    // Add long string case for truncation/overflow testing
    cases.push({ label: 'long string', value: '"' + 'a'.repeat(200) + '"' });
  }
  if (type === 'number' || type.includes('number')) {
    cases.push({ label: 'zero', value: '0' });
    cases.push({ label: 'negative number', value: '-1' });
    cases.push({ label: 'large number', value: '999999' });
  }
  if (type.includes('[]')) {
    cases.push({ label: 'empty array', value: '[]' });
    cases.push({ label: 'single item array', value: '[{ id: "1" }]' });
  }
  if (type.includes('boolean')) {
    cases.push({ label: 'false value', value: 'false' });
  }

  return cases;
}
