import path from 'path';
import { relativeImport } from '../utils/path';
import { ComponentInfo } from '../analyzer';

export interface TemplateOptions {
    testFilePath: string;
    sourceFilePath: string;
    usesUserEvent: boolean;
    needsScreen: boolean;
}

export function buildHeader(): string {
    return '/** @generated by react-testgen - deterministic output */';
}

export function buildImports(
    components: ComponentInfo[],
    options: TemplateOptions
): string {
    const defaultComponents = components.filter((c) => c.exportType === 'default');
    const namedComponents = components.filter((c) => c.exportType === 'named');
    const componentImport = relativeImport(options.testFilePath, options.sourceFilePath);

    const imports: string[] = [];
    const testUtilsImport = relativeImport(
        options.testFilePath,
        path.join(process.cwd(), 'src', 'test-utils', 'renderWithProviders.tsx')
    );
    const testingImports = ['renderWithProviders'];
    if (options.needsScreen) testingImports.push('screen');

    imports.push(`import { ${testingImports.join(', ')} } from "${testUtilsImport}";`);

    if (options.usesUserEvent) {
        imports.push('import userEvent from "@testing-library/user-event";');
    }

    if (defaultComponents.length > 0 && namedComponents.length > 0) {
        imports.push(
            `import ${defaultComponents[0].name}, { ${namedComponents
                .map((c) => c.name)
                .join(', ')} } from "${componentImport}";`
        );
    } else if (defaultComponents.length > 0) {
        imports.push(`import ${defaultComponents[0].name} from "${componentImport}";`);
    } else {
        imports.push(`import { ${namedComponents.map((c) => c.name).join(', ')} } from "${componentImport}";`);
    }

    return imports.join('\n');
}

export function buildDescribeStart(component: ComponentInfo): string {
    return `describe("${component.name}", () => {`;
}

export function buildDescribeEnd(): string {
    return '});';
}

export function buildTestBlock(title: string, bodyLines: string[]): string {
    const lines = [`  it("${title}", () => {`];
    for (const line of bodyLines) {
        lines.push(`    ${line}`);
    }
    lines.push('  });');
    return lines.join('\n');
}

export function buildAsyncTestBlock(title: string, bodyLines: string[]): string {
    const lines = [`  it("${title}", async () => {`];
    for (const line of bodyLines) {
        lines.push(`    ${line}`);
    }
    lines.push('  });');
    return lines.join('\n');
}

export function joinBlocks(blocks: string[]): string {
    return blocks.filter((b) => b.trim().length > 0).join('\n\n');
}

export function buildFileContent(parts: string[]): string {
    return parts.filter((p) => p.trim().length > 0).join('\n\n') + '\n';
}
