/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import BudgetProgress from "../BudgetProgress";

describe("BudgetProgress", () => {

  const defaultProps = {
  budgets: []
};

  const renderUI = (props = {}) =>
  render(<BudgetProgress {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
  });

});
