/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import RecentTransactions from "../RecentTransactions";

describe("RecentTransactions", () => {

  const defaultProps = {
  transactions: []
};

  const renderUI = (props = {}) =>
  render(<RecentTransactions {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
  });

});
