/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import RecentTransactions from "../RecentTransactions";

describe("RecentTransactions", () => {

  const defaultProps = {
  transactions: []
};

  const renderUI = (props = {}) =>
  renderWithProviders(<RecentTransactions {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
