/** @generated by react-testgen - deterministic output */

import { renderWithProviders, screen } from "../../../test-utils/renderWithProviders";
import userEvent from "@testing-library/user-event";
import ExpenseList from "../ExpenseList";

describe("ExpenseList", () => {

  const renderUI = () =>
  renderWithProviders(<ExpenseList />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Select all transactions/i)).toBeInTheDocument();
  });

});
