/** @generated by react-testgen - deterministic output */

import { renderWithProviders, screen } from "../../../test-utils/renderWithProviders";
import userEvent from "@testing-library/user-event";
import ExpenseFilters from "../ExpenseFilters";

describe("ExpenseFilters", () => {

  const defaultProps = {
  onSearch: "test-value"
};

  const renderUI = (props = {}) =>
  renderWithProviders(<ExpenseFilters {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Clear search/i)).toBeInTheDocument();
  });

});
