/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import EmptyState from "../EmptyState";

describe("EmptyState", () => {

  const defaultProps = {
  title: "test-value"
};

  const renderUI = (props = {}) =>
  renderWithProviders(<EmptyState {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
