/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Modal, { ConfirmModal } from "../Modal";

describe("Modal", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn(),
  children: <div />
};

  const renderUI = (props = {}) =>
  renderWithProviders(<Modal {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("ConfirmModal", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn(),
  onConfirm: jest.fn(),
  title: "test-value",
  message: "test-value"
};

  const renderUI = (props = {}) =>
  renderWithProviders(<ConfirmModal {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
