/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Pagination from "../Pagination";

describe("Pagination", () => {

  const defaultProps = {
  pagination: { page: 1, totalPages: 1, total: 0, limit: 10, hasNext: false, hasPrev: false },
  onPageChange: 1
};

  const renderUI = (props = {}) =>
  renderWithProviders(<Pagination {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
