/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Skeleton, { SkeletonCard, SkeletonTable, SkeletonStats } from "../Skeleton";

describe("Skeleton", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  renderWithProviders(<Skeleton {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("SkeletonCard", () => {

  const renderUI = () =>
  renderWithProviders(<SkeletonCard />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("SkeletonTable", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  renderWithProviders(<SkeletonTable {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("SkeletonStats", () => {

  const renderUI = () =>
  renderWithProviders(<SkeletonStats />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
