/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Spinner, { LoadingOverlay, LoadingPlaceholder } from "../Spinner";

describe("Spinner", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  renderWithProviders(<Spinner {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("LoadingOverlay", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  renderWithProviders(<LoadingOverlay {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("LoadingPlaceholder", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  renderWithProviders(<LoadingPlaceholder {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
