/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import ExpenseChart from "../ExpenseChart";

describe("ExpenseChart", () => {

  const defaultProps = {
  data: []
};

  const renderUI = (props = {}) =>
  renderWithProviders(<ExpenseChart {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
