/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import StatsCard from "../StatsCard";

describe("StatsCard", () => {

  const defaultProps = {
  title: "test-value",
  value: 1,
  icon: <div />
};

  const renderUI = (props = {}) =>
  renderWithProviders(<StatsCard {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
