/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Avatar from "../Avatar";

describe("Avatar", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  render(<Avatar {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
