/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Badge from "../Badge";

describe("Badge", () => {

  const defaultProps = {
  variant: undefined
};

  const renderUI = (props = {}) =>
  render(<Badge {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
