/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import DataTable from "../DataTable";

describe("DataTable", () => {

  const defaultProps = {
  data: [],
  columns: [],
  keyExtractor: "test-value"
};

  const renderUI = (props = {}) =>
  render(<DataTable {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Select all rows/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/`Select row \$\{index \+ 1\}`/i)).toBeInTheDocument();
  });

});
