/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import Modal, { ConfirmModal } from "../Modal";

describe("Modal", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn(),
  children: <div />
};

  const renderUI = (props = {}) =>
  render(<Modal {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Close modal/i)).toBeInTheDocument();
  });

});

describe("ConfirmModal", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn(),
  onConfirm: jest.fn(),
  title: "test-value",
  message: "test-value"
};

  const renderUI = (props = {}) =>
  render(<ConfirmModal {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
  });

});
