/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import Pagination from "../Pagination";

describe("Pagination", () => {

  const defaultProps = {
  pagination: undefined,
  onPageChange: 1
};

  const renderUI = (props = {}) =>
  render(<Pagination {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Go to first page/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/Go to previous page/i)).toBeInTheDocument();
  });

});
