/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Skeleton, { SkeletonCard, SkeletonTable, SkeletonStats } from "../Skeleton";

describe("Skeleton", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  render(<Skeleton {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("SkeletonCard", () => {

  const renderUI = () =>
  render(<SkeletonCard />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("SkeletonTable", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  render(<SkeletonTable {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("SkeletonStats", () => {

  const renderUI = () =>
  render(<SkeletonStats />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
