/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Spinner, { LoadingOverlay, LoadingPlaceholder } from "../Spinner";

describe("Spinner", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  render(<Spinner {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("LoadingOverlay", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  render(<LoadingOverlay {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("LoadingPlaceholder", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  render(<LoadingPlaceholder {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
