/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import ToastContainer from "../Toast";

describe("ToastContainer", () => {

  const renderUI = () =>
  render(<ToastContainer />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
