/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Avatar from "../Avatar";

describe("Avatar", () => {

  const defaultProps = {};

  const renderUI = (props = {}) =>
  renderWithProviders(<Avatar {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
