/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import DataTable from "../DataTable";

describe("DataTable", () => {

  const defaultProps = {
  data: [],
  columns: [],
  keyExtractor: "test-value"
};

  const renderUI = (props = {}) =>
  renderWithProviders(<DataTable {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
