/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import ToastContainer from "../Toast";

describe("ToastContainer", () => {

  const renderUI = () =>
  renderWithProviders(<ToastContainer />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
