/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../test-utils/renderWithProviders";
import ProtectedRoute, { PublicRoute } from "../ProtectedRoute";

describe("ProtectedRoute", () => {

  const defaultProps = {
  children: <div />
};

  const renderUI = (props = {}) =>
  renderWithProviders(<ProtectedRoute {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});

describe("PublicRoute", () => {

  const defaultProps = {
  children: <div />
};

  const renderUI = (props = {}) =>
  renderWithProviders(<PublicRoute {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
