/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import AuthLayout from "../AuthLayout";

describe("AuthLayout", () => {

  const defaultProps = {
  children: <div />,
  title: "test-value"
};

  const renderUI = (props = {}) =>
  renderWithProviders(<AuthLayout {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
