/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import MainLayout from "../MainLayout";

describe("MainLayout", () => {

  const defaultProps = {
  children: <div />
};

  const renderUI = (props = {}) =>
  renderWithProviders(<MainLayout {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
