/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Sidebar from "../Sidebar";

describe("Sidebar", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn()
};

  const renderUI = (props = {}) =>
  renderWithProviders(<Sidebar {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
