/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import BudgetProgress from "../BudgetProgress";

describe("BudgetProgress", () => {

  const defaultProps = {
  budgets: []
};

  const renderUI = (props = {}) =>
  renderWithProviders(<BudgetProgress {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
