/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import CategoryPieChart from "../CategoryPieChart";

describe("CategoryPieChart", () => {

  const defaultProps = {
  data: []
};

  const renderUI = (props = {}) =>
  renderWithProviders(<CategoryPieChart {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
