/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import QuickActions from "../QuickActions";

describe("QuickActions", () => {

  const defaultProps = {
  onAddExpense: jest.fn(),
  onAddIncome: jest.fn()
};

  const renderUI = (props = {}) =>
  renderWithProviders(<QuickActions {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
