import type { LlmProvider, LlmMessage } from './types';

/**
 * Takes a rule-based generated test and the original source code,
 * then asks the local LLM to generate ADDITIONAL test cases to append.
 *
 * Strategy: additive-only — the LLM outputs only new it() blocks,
 * which get spliced into the existing describe() block. This keeps
 * output tokens low (critical for CPU-only inference).
 *
 * If the LLM fails or returns garbage, the original test is returned unchanged.
 */
export async function enhanceTest(
  provider: LlmProvider,
  sourceCode: string,
  sourceFilePath: string,
  generatedTest: string
): Promise<{ enhanced: string; wasEnhanced: boolean; durationMs: number }> {
  const messages = buildPrompt(sourceCode, sourceFilePath, generatedTest);

  try {
    const response = await provider.chat(messages);
    const newTests = extractCodeBlock(response.content);

    if (!sanityCheckAdditions(newTests)) {
      console.warn('  ⚠️  LLM output failed sanity check — using rule-based test');
      return { enhanced: generatedTest, wasEnhanced: false, durationMs: response.durationMs };
    }

    const merged = spliceTests(generatedTest, newTests);
    return { enhanced: merged, wasEnhanced: true, durationMs: response.durationMs };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(`  ⚠️  LLM enhancement failed: ${message}`);
    return { enhanced: generatedTest, wasEnhanced: false, durationMs: 0 };
  }
}

// ---------------------------------------------------------------------------
// Prompt construction — additive strategy
// ---------------------------------------------------------------------------

function buildPrompt(
  sourceCode: string,
  sourceFilePath: string,
  generatedTest: string
): LlmMessage[] {
  return [
    {
      role: 'system',
      content: SYSTEM_PROMPT,
    },
    {
      role: 'user',
      content: [
        `## Source: ${sourceFilePath}`,
        '```tsx',
        sourceCode,
        '```',
        '',
        '## Existing tests:',
        '```tsx',
        generatedTest,
        '```',
        '',
        TASK,
      ].join('\n'),
    },
  ];
}

const SYSTEM_PROMPT = `You are a React testing expert. You write additional Jest + React Testing Library test cases.
You output ONLY new it() blocks — no imports, no describe(), no boilerplate.
Keep output SHORT — max 3-5 new test cases. Use the same renderUI() helper from the existing tests.`;

const TASK = `Write 3-5 additional it() blocks to improve coverage. Focus on:
- Edge cases (empty/null props, boundary values)
- Error states and loading states
- User interactions (clicks, typing)
- Things the existing tests missed

Output ONLY the new it() blocks in a \`\`\`tsx block. No imports, no describe wrapper. Example format:

\`\`\`tsx
  it("handles empty title prop", () => {
    const { container } = renderUI({ title: "" });
    expect(container).toBeInTheDocument();
  });

  it("shows loading skeleton when loading", () => {
    const { getByTestId } = renderUI({ loading: true });
    expect(screen.queryByText(/total/i)).not.toBeInTheDocument();
  });
\`\`\``;

// ---------------------------------------------------------------------------
// Response parsing
// ---------------------------------------------------------------------------

function extractCodeBlock(response: string): string {
  const fencePattern = /```(?:tsx?|typescript|javascript)?\s*\n([\s\S]*?)```/;
  const match = response.match(fencePattern);

  if (match?.[1]) {
    return match[1].trim();
  }

  // If no code fence, try the whole response if it looks like test code
  const trimmed = response.trim();
  if (trimmed.includes('it(') && trimmed.includes('expect(')) {
    return trimmed;
  }

  return '';
}

// ---------------------------------------------------------------------------
// Splice new tests into existing file
// ---------------------------------------------------------------------------

/**
 * Insert new it() blocks before the last `});` (closing of describe block).
 * Adds a comment separator so it's clear which tests are LLM-generated.
 */
function spliceTests(originalTest: string, newTests: string): string {
  // Update header to indicate enhancement
  let result = originalTest.replace(
    '/** @generated by react-testgen - deterministic output */',
    '/** @generated by react-testgen - enhanced by LLM */'
  );

  // Find the last `});` which closes the describe block
  const lastClose = result.lastIndexOf('});');
  if (lastClose === -1) {
    // Can't find describe close — append at end
    return result + '\n' + newTests + '\n';
  }

  // Indent the new tests to match existing indentation (2 spaces)
  const indented = newTests
    .split('\n')
    .map((line) => (line.trim() ? `  ${line}` : line))
    .join('\n');

  const before = result.substring(0, lastClose);
  const after = result.substring(lastClose);

  return (
    before +
    '\n  // --- LLM-generated additional tests ---\n\n' +
    indented +
    '\n\n' +
    after
  );
}

// ---------------------------------------------------------------------------
// Sanity check for additive output
// ---------------------------------------------------------------------------

function sanityCheckAdditions(newTests: string): boolean {
  if (!newTests || newTests.length < 20) return false;

  // Must contain at least one test case
  if (!newTests.includes('it(') && !newTests.includes('test(')) return false;
  if (!newTests.includes('expect(')) return false;

  // Should NOT contain full file structure (imports, describe)
  // — that means the LLM ignored the additive instruction
  if (newTests.includes('import ') && newTests.includes('describe(')) return false;

  // Check balanced braces
  const openBraces = (newTests.match(/{/g) || []).length;
  const closeBraces = (newTests.match(/}/g) || []).length;
  if (Math.abs(openBraces - closeBraces) > 1) return false;

  return true;
}
