/** @generated by react-testgen */
/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/*.test.{ts,tsx}', '**/*.test.{ts,tsx}'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|webp|svg|ico|bmp)$': '<rootDir>/src/test-utils/__mocks__/fileMock.js',
    '^react$': '<rootDir>/node_modules/react/index.js',
    '^react/(.*)$': '<rootDir>/node_modules/react/$1',
    '^react-dom$': '<rootDir>/node_modules/react-dom/index.js',
    '^react-dom/(.*)$': '<rootDir>/node_modules/react-dom/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        // Downgrade TypeScript errors to warnings so generated tests that use
        // approximate mock shapes still run and collect coverage.
        diagnostics: { warnOnly: true },
        tsconfig: {
          jsx: 'react-jsx',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          // Override Vite-specific options that ts-jest does not support
          moduleResolution: 'node',
          allowImportingTsExtensions: false,
        },
      },
    ],
  },
  // Transform ESM-only packages so Jest can load them
  transformIgnorePatterns: [
    '/node_modules/(?!(lucide-react|@tanstack|react-router|react-router-dom)/)',
  ],
  setupFilesAfterEnv: ['<rootDir>/src/test-utils/setupTests.ts'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/test-utils/**',
    '!src/main.tsx',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  clearMocks: true,
  restoreMocks: true,
  maxWorkers: '50%',
  forceExit: true,
};

module.exports = config;
