/** @generated by react-testgen - deterministic output */

import { renderWithProviders, screen } from "../../../test-utils/renderWithProviders";
import userEvent from "@testing-library/user-event";
import Header from "../Header";

describe("Header", () => {

  const defaultProps = {
  onMenuClick: jest.fn(),
  isSidebarOpen: true
};

  const renderUI = (props = {}) =>
  renderWithProviders(<Header {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getAllByRole("button")[0]).toBeInTheDocument();
    expect(screen.getAllByRole("button")[0]).toBeInTheDocument();
  });

});
