/** @generated by react-testgen - deterministic output */

import { renderWithProviders, screen } from "../../../test-utils/renderWithProviders";
import userEvent from "@testing-library/user-event";
import ExpenseForm from "../ExpenseForm";

describe("ExpenseForm", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn(),
  onSubmit: jest.fn()
};

  const renderUI = (props = {}) =>
  renderWithProviders(<ExpenseForm {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getAllByRole("button")[0]).toBeInTheDocument();
    expect(screen.getAllByRole("button")[0]).toBeInTheDocument();
    expect(screen.getAllByRole("textbox")[0]).toBeInTheDocument();
  });

});
