/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import ExpenseFilters from "../ExpenseFilters";

describe("ExpenseFilters", () => {

  const defaultProps = {
  onSearch: "test-value"
};

  const renderUI = (props = {}) =>
  render(<ExpenseFilters {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Clear search/i)).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Search transactions\.\.\./i)).toBeInTheDocument();
    expect(screen.getByRole("textbox")).toBeInTheDocument();
  });

});
