/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import ExpenseForm from "../ExpenseForm";

describe("ExpenseForm", () => {

  const defaultProps = {
  isOpen: true,
  onClose: jest.fn(),
  onSubmit: jest.fn()
};

  const renderUI = (props = {}) =>
  render(<ExpenseForm {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
    expect(screen.getByRole("textbox")).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Select a category/i)).toBeInTheDocument();
  });

});
