/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../test-utils/renderWithProviders";
import Dashboard from "../Dashboard";

describe("Dashboard", () => {

  const renderUI = () =>
  renderWithProviders(<Dashboard />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
