/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../test-utils/renderWithProviders";
import Expenses from "../Expenses";

describe("Expenses", () => {

  const renderUI = () =>
  renderWithProviders(<Expenses />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
