/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../test-utils/renderWithProviders";
import { ExpenseProvider } from "../ExpenseContext";

describe("ExpenseProvider", () => {

  const defaultProps = {
  children: <div />
};

  const renderUI = (props = {}) =>
  renderWithProviders(<ExpenseProvider {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
