/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import { ThemeProvider } from "../ThemeContext";

describe("ThemeProvider", () => {

  const defaultProps = {
  children: <div />
};

  const renderUI = (props = {}) =>
  render(<ThemeProvider {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
