/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Footer from "../Footer";

describe("Footer", () => {

  const renderUI = () =>
  render(<Footer />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
