/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../../../test-utils/renderWithProviders";
import Footer from "../Footer";

describe("Footer", () => {

  const renderUI = () =>
  renderWithProviders(<Footer />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
