/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import Header from "../Header";

describe("Header", () => {

  const defaultProps = {
  onMenuClick: jest.fn(),
  isSidebarOpen: true
};

  const renderUI = (props = {}) =>
  render(<Header {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/isSidebarOpen \? 'Close menu' : 'Open menu'/i)).toBeInTheDocument();
    expect(screen.getByLabelText(/`Switch to \$\{resolvedTheme === 'light' \? 'dark' : 'light'\} mode`/i)).toBeInTheDocument();
  });

});
