/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import MainLayout from "../MainLayout";

describe("MainLayout", () => {

  const defaultProps = {
  children: <div />
};

  const renderUI = (props = {}) =>
  render(<MainLayout {...defaultProps} {...props} />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
