/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Dashboard from "../Dashboard";

describe("Dashboard", () => {

  const renderUI = () =>
  render(<Dashboard />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
