/** @generated by react-testgen - deterministic output */

import { render } from "@testing-library/react";
import Expenses from "../Expenses";

describe("Expenses", () => {

  const renderUI = () =>
  render(<Expenses />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
