/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import Login from "../Login";

describe("Login", () => {

  const renderUI = () =>
  render(<Login />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/showPassword \? 'Hide password' : 'Show password'/i)).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Enter your email/i)).toBeInTheDocument();
    expect(screen.getByPlaceholderText(/Enter your password/i)).toBeInTheDocument();
  });

});
