/** @generated by react-testgen - deterministic output */

import { renderWithProviders, screen } from "../../test-utils/renderWithProviders";
import userEvent from "@testing-library/user-event";
import Profile from "../Profile";

describe("Profile", () => {

  const renderUI = () =>
  renderWithProviders(<Profile />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Change avatar/i)).toBeInTheDocument();
  });

});
