/** @generated by react-testgen - deterministic output */

import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import Profile from "../Profile";

describe("Profile", () => {

  const renderUI = () =>
  render(<Profile />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getByLabelText(/Change avatar/i)).toBeInTheDocument();
    expect(screen.getByRole("button")).toBeInTheDocument();
    expect(screen.getByRole("textbox")).toBeInTheDocument();
    expect(screen.getByRole("textbox")).toBeInTheDocument();
  });

});
