/** @generated by react-testgen - deterministic output */

import { renderWithProviders, screen } from "../../test-utils/renderWithProviders";
import userEvent from "@testing-library/user-event";
import Register from "../Register";

describe("Register", () => {

  const renderUI = () =>
  renderWithProviders(<Register />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

  it("renders key elements", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
    expect(screen.getAllByRole("button")[0]).toBeInTheDocument();
    expect(screen.getAllByRole("button")[0]).toBeInTheDocument();
    expect(screen.getAllByRole("textbox")[0]).toBeInTheDocument();
  });

});
