/**
 * Jest scaffold — creates missing Jest configuration files so testgen-generated
 * tests can actually run in projects that have no jest.config yet.
 *
 * Called automatically before test generation when the target project has no
 * jest.config.{js,ts,mjs,cjs} present.
 */
import fs from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

const JEST_CONFIG_FILES = [
  'jest.config.js',
  'jest.config.ts',
  'jest.config.mjs',
  'jest.config.cjs',
];

export function hasJestConfig(rootDir: string): boolean {
  return JEST_CONFIG_FILES.some((f) => fs.existsSync(path.join(rootDir, f)));
}

// ---------------------------------------------------------------------------
// Tsconfig path alias → Jest moduleNameMapper conversion
// ---------------------------------------------------------------------------

interface TsconfigLike {
  compilerOptions?: {
    paths?: Record<string, string[]>;
  };
}

/**
 * Reads tsconfig.app.json (or tsconfig.json) and returns Jest moduleNameMapper
 * entries for each path alias found.
 *
 * Example: "@/*": ["./src/*"]  →  { "^@/(.*)$": "<rootDir>/src/$1" }
 */
function readTsconfigPaths(rootDir: string): Record<string, string> {
  const candidates = ['tsconfig.app.json', 'tsconfig.json'];
  for (const name of candidates) {
    const tsconfigPath = path.join(rootDir, name);
    if (!fs.existsSync(tsconfigPath)) continue;
    try {
      const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, 'utf8')) as TsconfigLike;
      const rawPaths = tsconfig?.compilerOptions?.paths ?? {};
      const result: Record<string, string> = {};
      for (const [alias, targets] of Object.entries(rawPaths)) {
        if (!targets?.length) continue;
        // "@/*" → "^@/(.*)$"
        const escaped = alias.replace(/[.+^${}()|[\]\\]/g, '\\$&');
        const regexKey = `^${escaped.replace(/\*/g, '(.*)')}$`;
        // "./src/*" → "<rootDir>/src/$1"
        const targetValue =
          '<rootDir>/' + targets[0].replace(/^\.\//, '').replace(/\*$/, '$1');
        result[regexKey] = targetValue;
      }
      return result;
    } catch {
      // ignore parse errors — fall through to next candidate
    }
  }
  return {};
}

// ---------------------------------------------------------------------------
// File content builders
// ---------------------------------------------------------------------------

function buildJestConfigContent(rootDir: string): string {
  const pathMappings = readTsconfigPaths(rootDir);

  // When the project has its own node_modules/react (version differs from the
  // hoisted copy used by @testing-library), pin all React imports to the local
  // copy so there is only one React instance at runtime.
  // This handles both React 18 and React 19 projects in monorepo workspaces.
  const hasLocalReact = fs.existsSync(path.join(rootDir, 'node_modules', 'react'));
  const reactDedupEntries = hasLocalReact
    ? [
        `    '^react$': '<rootDir>/node_modules/react/index.js'`,
        `    '^react/(.*)$': '<rootDir>/node_modules/react/$1'`,
        `    '^react-dom$': '<rootDir>/node_modules/react-dom/index.js'`,
        `    '^react-dom/(.*)$': '<rootDir>/node_modules/react-dom/$1'`,
      ]
    : [];

  const staticEntries = [
    `    '\\\\.(css|less|scss|sass)$': 'identity-obj-proxy'`,
    `    '\\\\.(jpg|jpeg|png|gif|webp|svg|ico|bmp)$': '<rootDir>/src/test-utils/__mocks__/fileMock.js'`,
  ];
  const pathEntries = Object.entries(pathMappings).map(
    ([k, v]) => `    '${k}': '${v}'`,
  );
  const allEntries = [...staticEntries, ...reactDedupEntries, ...pathEntries].join(',\n');

  return `/** @generated by react-testgen */
/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/*.test.{ts,tsx}', '**/*.test.{ts,tsx}'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
${allEntries},
  },
  transform: {
    '^.+\\\\.(ts|tsx)$': [
      'ts-jest',
      {
        // Downgrade TypeScript errors to warnings so generated tests that use
        // approximate mock shapes still run and collect coverage.
        diagnostics: { warnOnly: true },
        tsconfig: {
          jsx: 'react-jsx',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          // Override Vite-specific options that ts-jest does not support
          moduleResolution: 'node',
          allowImportingTsExtensions: false,
        },
      },
    ],
  },
  // Transform ESM-only packages so Jest can load them
  transformIgnorePatterns: [
    '/node_modules/(?!(lucide-react|@tanstack|react-router|react-router-dom)/)',
  ],
  setupFilesAfterEnv: ['<rootDir>/src/test-utils/setupTests.ts'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/test-utils/**',
    '!src/main.tsx',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  clearMocks: true,
  restoreMocks: true,
  maxWorkers: '50%',
  forceExit: true,
};

module.exports = config;
`;
}

function buildSetupTestsContent(): string {
  return `import '@testing-library/jest-dom';

// Mock window.matchMedia (required by many UI components and recharts)
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(),
    removeListener: jest.fn(),
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

// Mock ResizeObserver (required by recharts and similar libs)
global.ResizeObserver = jest.fn().mockImplementation(() => ({
  observe: jest.fn(),
  unobserve: jest.fn(),
  disconnect: jest.fn(),
}));

// Mock IntersectionObserver
global.IntersectionObserver = jest.fn().mockImplementation(() => ({
  observe: jest.fn(),
  unobserve: jest.fn(),
  disconnect: jest.fn(),
}));
`;
}

function buildErrorBoundaryContent(): string {
  return `import React from 'react';

interface ErrorBoundaryProps {
  children: React.ReactNode;
  fallback?: React.ReactNode;
}

interface ErrorBoundaryState {
  hasError: boolean;
  error: Error | null;
}

/**
 * Test ErrorBoundary — wraps components to catch render errors so tests
 * can still assert on the container instead of crashing.
 * @generated by react-testgen
 */
export class TestErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  render(): React.ReactNode {
    if (this.state.hasError) {
      return this.props.fallback ?? (
        <div data-testid="error-boundary">
          Render error: {this.state.error?.message ?? 'Unknown error'}
        </div>
      );
    }
    return this.props.children;
  }
}
`;
}

function buildEnhancedPolyfills(): string {
  return `
// Mock window.scrollTo (used by many router/scroll components)
if (typeof window.scrollTo !== 'function' || !(window.scrollTo as unknown)) {
  window.scrollTo = jest.fn();
}

// Mock URL.createObjectURL / revokeObjectURL (used by file upload components)
if (!URL.createObjectURL) {
  URL.createObjectURL = jest.fn(() => 'blob:test-url');
}
if (!URL.revokeObjectURL) {
  URL.revokeObjectURL = jest.fn();
}

// Mock HTMLCanvasElement.getContext (used by chart libraries)
HTMLCanvasElement.prototype.getContext = jest.fn().mockReturnValue({
  fillRect: jest.fn(),
  clearRect: jest.fn(),
  getImageData: jest.fn(() => ({ data: new Array(4) })),
  putImageData: jest.fn(),
  createImageData: jest.fn(() => []),
  setTransform: jest.fn(),
  drawImage: jest.fn(),
  save: jest.fn(),
  fillText: jest.fn(),
  restore: jest.fn(),
  beginPath: jest.fn(),
  moveTo: jest.fn(),
  lineTo: jest.fn(),
  closePath: jest.fn(),
  stroke: jest.fn(),
  translate: jest.fn(),
  scale: jest.fn(),
  rotate: jest.fn(),
  arc: jest.fn(),
  fill: jest.fn(),
  measureText: jest.fn(() => ({ width: 0 })),
  transform: jest.fn(),
  rect: jest.fn(),
  clip: jest.fn(),
  canvas: { width: 0, height: 0 },
}) as unknown as typeof HTMLCanvasElement.prototype.getContext;

// Suppress act() warnings from React — noisy in generated tests
const originalError = console.error;
const originalWarn = console.warn;
beforeAll(() => {
  console.error = (...args: unknown[]) => {
    const msg = typeof args[0] === 'string' ? args[0] : '';
    if (msg.includes('act(') || msg.includes('ReactDOMTestUtils.act')) return;
    originalError.call(console, ...args);
  };
  console.warn = (...args: unknown[]) => {
    const msg = typeof args[0] === 'string' ? args[0] : '';
    if (msg.includes('act(') || msg.includes('ReactDOMTestUtils.act')) return;
    originalWarn.call(console, ...args);
  };
});
afterAll(() => {
  console.error = originalError;
  console.warn = originalWarn;
});
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Creates the minimum Jest scaffolding needed to run tests in a project with
 * no jest.config file. Safe to call on every run — no-ops when a config exists.
 *
 * Creates:
 *  - jest.config.cjs            (.cjs = always CommonJS, safe with "type":"module")
 *  - src/test-utils/setupTests.ts
 *  - src/test-utils/__mocks__/fileMock.js
 *  - src/test-utils/ErrorBoundary.tsx
 */
export function ensureJestScaffold(rootDir: string): void {
  if (hasJestConfig(rootDir)) return;

  const configPath = path.join(rootDir, 'jest.config.cjs');
  fs.writeFileSync(configPath, buildJestConfigContent(rootDir), 'utf8');
  console.log('  Created jest.config.cjs (no Jest config was found)');

  const setupDir = path.join(rootDir, 'src', 'test-utils');
  const setupPath = path.join(setupDir, 'setupTests.ts');
  if (!fs.existsSync(setupPath)) {
    fs.mkdirSync(setupDir, { recursive: true });
    fs.writeFileSync(setupPath, buildSetupTestsContent(), 'utf8');
    console.log('  Created src/test-utils/setupTests.ts');
  }

  // Append enhanced polyfills to setupTests if not already present
  if (fs.existsSync(setupPath)) {
    const existingContent = fs.readFileSync(setupPath, 'utf8');
    if (!existingContent.includes('scrollTo') && !existingContent.includes('createObjectURL')) {
      fs.appendFileSync(setupPath, buildEnhancedPolyfills(), 'utf8');
      console.log('  Enhanced src/test-utils/setupTests.ts with additional polyfills');
    }
  }

  const mocksDir = path.join(setupDir, '__mocks__');
  const fileMockPath = path.join(mocksDir, 'fileMock.js');
  if (!fs.existsSync(fileMockPath)) {
    fs.mkdirSync(mocksDir, { recursive: true });
    fs.writeFileSync(fileMockPath, `module.exports = 'test-file-stub';\n`, 'utf8');
    console.log('  Created src/test-utils/__mocks__/fileMock.js');
  }

  // Create ErrorBoundary component for test resilience
  const errorBoundaryPath = path.join(setupDir, 'ErrorBoundary.tsx');
  if (!fs.existsSync(errorBoundaryPath)) {
    fs.writeFileSync(errorBoundaryPath, buildErrorBoundaryContent(), 'utf8');
    console.log('  Created src/test-utils/ErrorBoundary.tsx');
  }
}
