/**
 * Jest scaffold — creates missing Jest configuration files so testgen-generated
 * tests can actually run in projects that have no jest.config yet.
 *
 * Called automatically before test generation when the target project has no
 * jest.config.{js,ts,mjs,cjs} present.
 */
import fs from 'node:fs';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

const JEST_CONFIG_FILES = [
  'jest.config.js',
  'jest.config.ts',
  'jest.config.mjs',
  'jest.config.cjs',
];

export function hasJestConfig(rootDir: string): boolean {
  return JEST_CONFIG_FILES.some((f) => fs.existsSync(path.join(rootDir, f)));
}

// ---------------------------------------------------------------------------
// Tsconfig path alias → Jest moduleNameMapper conversion
// ---------------------------------------------------------------------------

interface TsconfigLike {
  compilerOptions?: {
    paths?: Record<string, string[]>;
  };
}

/**
 * Reads tsconfig.app.json (or tsconfig.json) and returns Jest moduleNameMapper
 * entries for each path alias found.
 *
 * Example: "@/*": ["./src/*"]  →  { "^@/(.*)$": "<rootDir>/src/$1" }
 */
function readTsconfigPaths(rootDir: string): Record<string, string> {
  const candidates = ['tsconfig.app.json', 'tsconfig.json'];
  for (const name of candidates) {
    const tsconfigPath = path.join(rootDir, name);
    if (!fs.existsSync(tsconfigPath)) continue;
    try {
      const tsconfig = JSON.parse(fs.readFileSync(tsconfigPath, 'utf8')) as TsconfigLike;
      const rawPaths = tsconfig?.compilerOptions?.paths ?? {};
      const result: Record<string, string> = {};
      for (const [alias, targets] of Object.entries(rawPaths)) {
        if (!targets?.length) continue;
        // "@/*" → "^@/(.*)$"
        const escaped = alias.replace(/[.+^${}()|[\]\\]/g, '\\$&');
        const regexKey = `^${escaped.replace(/\*/g, '(.*)')}$`;
        // "./src/*" → "<rootDir>/src/$1"
        const targetValue =
          '<rootDir>/' + targets[0].replace(/^\.\//, '').replace(/\*$/, '$1');
        result[regexKey] = targetValue;
      }
      return result;
    } catch {
      // ignore parse errors — fall through to next candidate
    }
  }
  return {};
}

// ---------------------------------------------------------------------------
// File content builders
// ---------------------------------------------------------------------------

function buildJestConfigContent(rootDir: string): string {
  const pathMappings = readTsconfigPaths(rootDir);

  // When the project has its own node_modules/react (version differs from the
  // hoisted copy used by @testing-library), pin all React imports to the local
  // copy so there is only one React instance at runtime.
  // This handles both React 18 and React 19 projects in monorepo workspaces.
  const hasLocalReact = fs.existsSync(path.join(rootDir, 'node_modules', 'react'));
  const reactDedupEntries = hasLocalReact
    ? [
        `    '^react$': '<rootDir>/node_modules/react/index.js'`,
        `    '^react/(.*)$': '<rootDir>/node_modules/react/$1'`,
        `    '^react-dom$': '<rootDir>/node_modules/react-dom/index.js'`,
        `    '^react-dom/(.*)$': '<rootDir>/node_modules/react-dom/$1'`,
      ]
    : [];

  const staticEntries = [
    `    '\\\\.(css|less|scss|sass)$': 'identity-obj-proxy'`,
    `    '\\\\.(jpg|jpeg|png|gif|webp|svg|ico|bmp)$': '<rootDir>/src/test-utils/__mocks__/fileMock.js'`,
  ];
  const pathEntries = Object.entries(pathMappings).map(
    ([k, v]) => `    '${k}': '${v}'`,
  );
  const allEntries = [...staticEntries, ...reactDedupEntries, ...pathEntries].join(',\n');

  return `/** @generated by react-testgen */
/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/*.test.{ts,tsx}', '**/*.test.{ts,tsx}'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
${allEntries},
  },
  transform: {
    '^.+\\\\.(ts|tsx)$': [
      'ts-jest',
      {
        // Downgrade TypeScript errors to warnings so generated tests that use
        // approximate mock shapes still run and collect coverage.
        diagnostics: { warnOnly: true },
        tsconfig: {
          jsx: 'react-jsx',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          // Override Vite-specific options that ts-jest does not support
          moduleResolution: 'node',
          allowImportingTsExtensions: false,
        },
      },
    ],
  },
  // Transform ESM-only packages so Jest can load them
  transformIgnorePatterns: [
    '/node_modules/(?!(lucide-react|@tanstack|react-router|react-router-dom)/)',
  ],
  setupFilesAfterEnv: ['<rootDir>/src/test-utils/setupTests.ts'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/test-utils/**',
    '!src/main.tsx',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  clearMocks: true,
  restoreMocks: true,
  maxWorkers: '50%',
  forceExit: true,
};

module.exports = config;
`;
}

function buildSetupTestsContent(): string {
  return `import '@testing-library/jest-dom';

// Mock window.matchMedia (required by many UI components and recharts)
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation((query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(),
    removeListener: jest.fn(),
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

// Mock ResizeObserver (required by recharts and similar libs)
global.ResizeObserver = jest.fn().mockImplementation(() => ({
  observe: jest.fn(),
  unobserve: jest.fn(),
  disconnect: jest.fn(),
}));

// Mock IntersectionObserver
global.IntersectionObserver = jest.fn().mockImplementation(() => ({
  observe: jest.fn(),
  unobserve: jest.fn(),
  disconnect: jest.fn(),
}));
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Creates the minimum Jest scaffolding needed to run tests in a project with
 * no jest.config file. Safe to call on every run — no-ops when a config exists.
 *
 * Creates:
 *  - jest.config.cjs            (.cjs = always CommonJS, safe with "type":"module")
 *  - src/test-utils/setupTests.ts
 *  - src/test-utils/__mocks__/fileMock.js
 */
export function ensureJestScaffold(rootDir: string): void {
  if (hasJestConfig(rootDir)) return;

  const configPath = path.join(rootDir, 'jest.config.cjs');
  fs.writeFileSync(configPath, buildJestConfigContent(rootDir), 'utf8');
  console.log('  Created jest.config.cjs (no Jest config was found)');

  const setupDir = path.join(rootDir, 'src', 'test-utils');
  const setupPath = path.join(setupDir, 'setupTests.ts');
  if (!fs.existsSync(setupPath)) {
    fs.mkdirSync(setupDir, { recursive: true });
    fs.writeFileSync(setupPath, buildSetupTestsContent(), 'utf8');
    console.log('  Created src/test-utils/setupTests.ts');
  }

  const mocksDir = path.join(setupDir, '__mocks__');
  const fileMockPath = path.join(mocksDir, 'fileMock.js');
  if (!fs.existsSync(fileMockPath)) {
    fs.mkdirSync(mocksDir, { recursive: true });
    fs.writeFileSync(fileMockPath, `module.exports = 'test-file-stub';\n`, 'utf8');
    console.log('  Created src/test-utils/__mocks__/fileMock.js');
  }
}
