/** @generated by react-testgen - deterministic output */

import { renderWithProviders } from "../test-utils/renderWithProviders";
import App from "../App";

describe("App", () => {

  const renderUI = () =>
  renderWithProviders(<App />);

  it("renders without crashing", () => {
    const { container } = renderUI();
    expect(container).toBeInTheDocument();
  });

});
